In [1]:
import pandas as pd
import glob

# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer Woo/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_04_30/*.csv")

# 2. Use list comprehension to read all files and concat them
df = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1823 entries, 0 to 1822
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           1823 non-null   int64
 1   card_name              1822 non-null   object
 2   supertype              8 non-null      object
 3   subtype_a              117 non-null    object
 4   subtype_b              1769 non-null   object
 5   subtype_c              1231 non-null   object
 6   subtype_d              621 non-null    object
 7   subtype_e              47 non-null     object
 8   expansion_symbol       1822 non-null   object
 9   rarity                 1822 non-null   object
 10  artist_information     1819 non-null   object
 11  collectors_number      1822 non-null   object
 12  expansion_total_cards  1787 non-null   float64
 13  mana_cost              1773 non-null   object
 14  text_box               1766 non-null   object
 15  flavor_text            1308 non-null   object
 16  punch                  1058 non-null   object
 17  toughness              1057 non-null   object
 18  starting_loyalty       0 non-null      float64
 19  quantity               1817 non-null   object
dtypes: float64(2), int64(1), object(17)
memory usage: 285.0+ KB

In [3]:
df

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
0,1,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,Richard Kane Ferguson,69,383.0,U,Enchant Creature\nEnchanted creature gets +2+0...,Never underestimate the poweor of the soul unl...,NaN,NaN,NaN,1
1,2,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,Jeff A. Menges,73,383.0,XUU,Iceberg comes into play with X ice counters on...,NaN,NaN,NaN,NaN,1
2,3,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,Quinton Hoover,84,383.0,UU,B: Counter target spell that targets mistfolk.,"""Although my official log will state there is ...",1,2,NaN,1
3,4,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,"Ken Meyer, Jr.",100,383.0,1U,Enchant creature\nEnchanted creature has flyin...,"""Give me wings to fly and speed to strike. In ...",NaN,NaN,NaN,1
4,5,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,Tom Wänerstrand,310,383.0,2,"2, T: Target snow land is no longer snow.\n2, ...",NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,1818,Cultivate,NaN,NaN,Sorcery,NaN,NaN,NaN,M11,Common,Anthony Palumbo,168,249.0,2G,Search your library for up to two basic land c...,"All seeds share a common bond, calling to each...",NaN,NaN,NaN,1
1819,1819,Giant Growth,NaN,NaN,Instant,NaN,NaN,NaN,M11,Common,Matt Cavotta,178,249.0,G,Target creature gets +3/+3 until end of turn.,NaN,NaN,NaN,NaN,1
1820,1820,Primal Cocoon,NaN,NaN,Enchantment,Aura,NaN,NaN,M11,Common,Daniel Ljunggren,191,249.0,G,Enchant creature\nAt the beginning of your upk...,NaN,NaN,NaN,NaN,2
1821,1821,Sacred Wolf,NaN,NaN,Creature,Wolf,NaN,NaN,M11,Common,Matt Stewart,196,249.0,2G,Sacred Wolf can't be the target of spells or a...,"""I raised my bow, and the wolf stared at me. U...",3.0,1.0,NaN,1
1822,1822,Wall of Vines,NaN,NaN,Creature,Plant,Wall,NaN,M11,Common,John Stanko,199,249.0,G,Defender (This creature can't attack.)\nReach ...,"Like all jungle plants, the vines must fight a...",0.0,3.0,NaN,1

In [4]:
df['permanent_id'] = range(1, len(df) +1)

In [5]:
# 34 rows are missing expansion_total_cards
# Row 911 is completely empty

In [6]:
df[df['expansion_total_cards'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
6,7,Resistance Fighter,NaN,NaN,Creature,Soldier,NaN,NaN,Visions,Common,Cecil Fernando,18,NaN,W,Sacrifice Resistance Fighter: Target creature ...,"""My soldiers fought without hesitation, died w...",1,1,NaN,1
7,8,Fireblast,NaN,NaN,Instant,NaN,NaN,NaN,Visions,Common,Michael Danza,79,NaN,4RR,You may sacrifice two mountains instead of pay...,Embermages aren't well known for their diploma...,NaN,NaN,NaN,1
8,9,Lichenthrope,NaN,NaN,Creature,Lichenthrope,NaN,NaN,Visions,Common,Bob Eggleton,112,NaN,3GG,"For each 1 damage dealt to Lichenthrope, put a...",NaN,5,5,NaN,4
9,10,Quirion Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Visions,Common,Tom Kyffin,117,NaN,G,Return a forest you control to owners's hand: ...,"""Respect the earth, for it will one day be you...",1,1,NaN,2
10,11,Stampeding Wildebeests,NaN,NaN,Creature,Wildebeests,NaN,NaN,Visions,Common,Randy Gallegos,121,NaN,2GG,"Trample\nDuring your upkeep, return a green cr...",Prayers for rain are answered with the thunder...,5,4,NaN,1
11,12,Lava Axe,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,Adrian Smith,137,NaN,4R,Lava Axe deals 5 damage to your opponent,"Swing your axe as a broom, to sweep away the foe",NaN,NaN,NaN,1
12,13,Volcanic Hammer,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,Christopher Rush,154,NaN,1R,Volcanic Hammer deals 3 damage to any one crea...,"Cast the weight as though it were a die, to se...",NaN,NaN,NaN,1
13,14,Contemplation,NaN,NaN,Enchantment,NaN,NaN,NaN,Stronghold,Common,Brom,4,NaN,1WW,"Whenever you successfully cast a spell, gain 1...","""How fascinating it is to watch the machinatio...",NaN,NaN,NaN,1
14,15,Soul Warden,NaN,NaN,Creature,Ceric,NaN,NaN,Exodus,Uncommon,Randy Gallegos,21,NaN,W,"Whenever any other creature comes into play, g...",Count carefully the souls and see that none ar...,1,1,NaN,4
15,16,Talas Merchant,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,Lubov,50,NaN,1U,NaN,The trader let loose a laugh that made all aro...,1,3,NaN,2
16,17,Air Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Portal 2,Uncommon,Doug Chaffee,31,NaN,3UU,Flying,"As insubstantial, and as powerful, as the wind...",4,4,NaN,2
17,18,Touch of Brilliance,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,Kaja Foglio,58,NaN,3U,NaN,NaN,NaN,NaN,NaN,2
18,19,Talas Researcher,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Rare,Kaja Foglio,66,NaN,4U,"On your turn, before you attack, you may tap T...","From time, knowledge.\nFrom knowledge, power.",1,1,NaN,1
19,20,False Summoning,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,DiTerlizzi,40,NaN,1U,Play False Summoning only in response to anoth...,NaN,NaN,NaN,NaN,2
20,21,Talas Air Ship,NaN,NaN,Creature,Ship,NaN,NaN,Portal 2,Common,Mark Tedin,48,NaN,3U,Flying,"""Their ships pollute our air as they themselve...",3,2,NaN,2
21,22,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,Di'Terlizzi,41,NaN,1UU,Play Mystic Denial only in response to another...,NaN,NaN,NaN,NaN,2
22,23,Talas Scout,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Common,Heather Hudson,52,NaN,1U,Flying,"""Scouting a battle before you fight it is just...",1,2,NaN,2
23,24,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Uncommon,Christopher Rush,32,NaN,2U,"On your turn, before you attack, you may tap A...",NaN,1,1,NaN,2
24,25,Exhaustion,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,Kaja Foglio,37,NaN,2U,"At the beginning of your opponent's next turn,...",NaN,NaN,NaN,NaN,1
25,26,Talas Explorer,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,Douglas Shuler,49,NaN,1U,Flying,When Talas Explorer comes into play from your ...,1,1,NaN,2
26,27,Time Ebb,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,Sam Wood,57,NaN,2U,Return any one creature from play to the top o...,"""The ogre had come from out of the blue, so th...",NaN,NaN,NaN,2
27,28,Talas Warrior,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Rare,Douglas Shuler,53,NaN,1UU,Talas Warrior can't be blocked,The sea is in their blood. Literally.,2,2,NaN,1
28,29,Monstrous Growth,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,Una Fricker,133,NaN,1G,Any one creature gets +4/+4 until the end of t...,The nightstalker's little game of tease-the-sq...,NaN,NaN,NaN,2
29,30,Alluring Scent,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,Melissa A. Benson,121,NaN,1GG,"Choose any one creature. This turn, all creatu...",No earthly armor is protection against this sw...,NaN,NaN,NaN,1
30,31,Wild Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Uncommon,Jeffrey R. Busch,150,NaN,3G,Swampwalk (If defending player has any swamps ...,"It has the run of the swamps, and it knows it.",3,3,NaN,2
31,32,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,NaN,Portal 2,Uncommon,Ron Spencer,146,NaN,3GG,"If Sylvan Basilisk attacks and is blocked, des...",NaN,2,4,NaN,1
32,33,River Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Uncommon,Una Fricker,144,NaN,3G,Islandwalk (If defending player has any island...,The bears had been isolated on an island for h...,3,3,NaN,2
33,34,Norwood Riders,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,Rebecca Guay,139,NaN,3G,Norwood Riders can't be blocked by more than o...,"""Trade my moose? Sure—when I find a horse that...",3,3,NaN,2
34,35,Norwood Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Portal 2,Common,Ron Spencer,138,NaN,G,NaN,Some trees bear deadly fruit.,1,2,NaN,2
35,36,Norwood Archers,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,Rebecca Guay,136,NaN,3G,Norwood Archers can block creatures with flying.,"""'Air superiority?' Not while our archers scan...",3,3,NaN,2
36,37,Golden Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,Una Fricker,127,NaN,3G,NaN,The elvish scout was scrupulous about the trut...,4,3,NaN,2
37,38,Bear Cub,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,Ron Spencer,123,NaN,1G,NaN,Every little cub has its mother's teeth to gua...,2,2,NaN,3
38,39,Ironhoof Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Common,Una Fricker,130,NaN,3GG,Ironhoof Ox can't be blocked by more than one ...,The good news is it's vegetarian. The bad news...,4,4,NaN,2
39,40,Angel of Fury,NaN,NaN,Creature,Angel,NaN,NaN,Portal 2,Rare,Keith Parkinson,7,NaN,4WW,Flying\nIf Angel of Fury is put into your grav...,NaN,3,5,NaN,1
40,41,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,Jeffrey R. Busch,20,NaN,1WW,All your creatures get +2/+2 until the end of ...,NaN,NaN,NaN,NaN,1
911,912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.loc[df['expansion_symbol'] == 'Visions', 'expansion_total_cards'] = 167
df.loc[df['expansion_symbol'] == 'Portal', 'expansion_total_cards'] = 222
df.loc[df['expansion_symbol'] == 'Stronghold', 'expansion_total_cards'] = 143
df.loc[df['expansion_symbol'] == 'Exodus', 'expansion_total_cards'] = 143
df.loc[df['expansion_symbol'] == 'Portal 2', 'expansion_total_cards'] = 165

In [8]:
df = df.drop(911)

In [9]:
df['expansion_total_cards'] = df['expansion_total_cards'].astype(int)

In [10]:
df.tail()

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1818,1819,Cultivate,NaN,NaN,Sorcery,NaN,NaN,NaN,M11,Common,Anthony Palumbo,168,249,2G,Search your library for up to two basic land c...,"All seeds share a common bond, calling to each...",NaN,NaN,NaN,1
1819,1820,Giant Growth,NaN,NaN,Instant,NaN,NaN,NaN,M11,Common,Matt Cavotta,178,249,G,Target creature gets +3/+3 until end of turn.,NaN,NaN,NaN,NaN,1
1820,1821,Primal Cocoon,NaN,NaN,Enchantment,Aura,NaN,NaN,M11,Common,Daniel Ljunggren,191,249,G,Enchant creature\nAt the beginning of your upk...,NaN,NaN,NaN,NaN,2
1821,1822,Sacred Wolf,NaN,NaN,Creature,Wolf,NaN,NaN,M11,Common,Matt Stewart,196,249,2G,Sacred Wolf can't be the target of spells or a...,"""I raised my bow, and the wolf stared at me. U...",3.0,1.0,NaN,1
1822,1823,Wall of Vines,NaN,NaN,Creature,Plant,Wall,NaN,M11,Common,John Stanko,199,249,G,Defender (This creature can't attack.)\nReach ...,"Like all jungle plants, the vines must fight a...",0.0,3.0,NaN,1

In [11]:
import mysql.connector
try:
    # 1. Establish the connection
    db_connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="password",
        database="trading_card_database"
    )

    if db_connection.is_connected():
        print("Successfully connected to the database")

    # 2. Create a cursor to execute SQL queries
    cursor = db_connection.cursor()
    cursor.execute("SELECT DATABASE();")
    record = cursor.fetchone()
    print("You're connected to the database:", record)

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    # 3. Always close the connection
    if 'db-connection' in locals() and db_connection.is_connected():
        cursor.close()
        db_connection.close()
        print("MySQL connection is closed")

Error: 1049 (42000): Unknown database 'trading_card_database'

In [12]:
# 1. JUNCTION TABLE
# for each row, iterate through subtype columns
# if the subtype is nan, do nothing
# if the subtype is valid, add it to an array
# iterate through the array and query the parent table for the matching index
# insert the id and subtype into the junction table

In [13]:
cursor.execute("CREATE TABLE permanent_junction_subtype (permanent_id INT,subtype_id INT,PRIMARY KEY (permanent_id, subtype_id));")

NameError: name 'cursor' is not defined

In [ ]:
row_subtypes = df.iloc[1059, 3:8].to_numpy()

In [14]:
row_subtypes

NameError: name 'row_subtypes' is not defined

In [28]:
df.iloc[:, 1:1822] = df.iloc[:, 1:50].fillna(0)

0            NaN
1            NaN
2            NaN
3            NaN
4       Artifact
          ...
1818         NaN
1819         NaN
1820         NaN
1821         NaN
1822         NaN
Name: subtype_a, Length: 1822, dtype: object

In [ ]:
import math
import numpy as np

for i, row in enumerate(df, start=1):
    permanent_id = df.iloc[i, 1]
    subtypes = df.iloc[i, 3:8].to_numpy()
    for type in subtypes:
        #if math.isnan(type):
        if type == "":
            continue
        else:
            cursor.execute("SELECT subtype_id FROM subtype WHERE subtype = %s", (type))
            subtype_id = cursor.fetchone()[0]
            cursor.execute("INSERT INTO permanent_junction_subtype (permnent_id, subtype_id) VALUES (%s, %s)" (permanent_id, subtype_id))
            connection.commit()

In [12]:
import pandas as pd
import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_database"
)
cursor = db.cursor()

target_cols = ['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']

for index, row in df.iterrows():
    for col in target_cols:
        val = row[col]

        if pd.isna(val):
            continue

        query_parent = "SELECT subtype_id FROM subtype WHERE subtype = %s"
        cursor.execute(query_parent, (val,))
        result = cursor.fetchone()

        if result:
            parent_id = result[0]
            insert_child = "INSERT INTO child_table (parent_id, df_index) VALUES (%s, %s)"
            cursor.execute(insert_child, (parent_id, index))

db.commit()
cursor.close()
db.close()

ProgrammingError: 1146 (42S02): Table 'trading_card_database.subtype' doesn't exist

In [56]:
# 2. PARENT TABLE
# create a list of all unique subtypes in the dataframe
# remove any instances of nan or blank subtypes
# find the longest subtype
# create table declaring subtype as VARCHAR() use the length of the longest subtype as the parameter for varchar

In [15]:
df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect',
       'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Sliver',
       'Eye', 'Gargoyle', 'Orgg', 'Avatar', 'Fungus', 'Kithkin',
       'Merfolk', 'Gorgon', 'Leech', 'Kor', 'Encahntment', 'Serpent',
       'Homarid', 'Orc', 'Shapeshifter', 'Shade', 'Wraith', 'Cyclops',
       'Tribal', 'Forest', 'Ouphe', 'Myr', 'Treefolk', 'Instinct',
       'Island', 'Scarecrow', 'Hag', 'Noggle', 'Dwarf', 'Gobiln', 'Rhino',
       'Lizard', 'Artificer', 'Dragon', 'Unicorn', 'Vampire', 'Antelope',
       'Juggernaut', 'Vedalken', 'Ally', 'Funugs', 'Construct', 'Trap',
       'Kraken', 'Fish', 'Crocodile', 'Boar', 'Surrakar', 'Thopter'],
      dtype=object)

In [16]:
subtype_arr = df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

In [17]:
max(subtype_arr, key=len)

'Lichenthrope'

In [18]:
len(max(subtype_arr, key=len))

12

In [19]:
longest = len(max(subtype_arr, key=len))

In [20]:
# create a dataframe from the array of uniques

In [21]:
subtype_df = pd.DataFrame(subtype_arr)

In [22]:
subtype_df

               0
0    Enchantment
1           Aura
2       Creature
3       Illusion
4       Artifact
..           ...
131         Fish
132    Crocodile
133         Boar
134     Surrakar
135      Thopter

[136 rows x 1 columns]

In [23]:
subtype_df['subtype_id'] = range(1, len(subtype_df) + 1)

In [24]:
subtype_df

               0  subtype_id
0    Enchantment           1
1           Aura           2
2       Creature           3
3       Illusion           4
4       Artifact           5
..           ...         ...
131         Fish         132
132    Crocodile         133
133         Boar         134
134     Surrakar         135
135      Thopter         136

[136 rows x 2 columns]

In [25]:
subtype_df = subtype_df.rename(columns={0: 'subtype'})

In [26]:
subtype_df

         subtype  subtype_id
0    Enchantment           1
1           Aura           2
2       Creature           3
3       Illusion           4
4       Artifact           5
..           ...         ...
131         Fish         132
132    Crocodile         133
133         Boar         134
134     Surrakar         135
135      Thopter         136

[136 rows x 2 columns]

In [27]:
subtype_df = subtype_df[['subtype_id', 'subtype']]

In [28]:
subtype_df

     subtype_id      subtype
0             1  Enchantment
1             2         Aura
2             3     Creature
3             4     Illusion
4             5     Artifact
..          ...          ...
131         132         Fish
132         133    Crocodile
133         134         Boar
134         135     Surrakar
135         136      Thopter

[136 rows x 2 columns]

In [29]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_collection"
)
cursor = conn.cursor()

# Create the table manually
cursor.execute("""
    CREATE TABLE IF NOT EXISTS subtype (
        subtype_id INT,
        subtype VARCHAR(%s)
    )
    """, (longest,))

In [31]:
# Prepare the data as a list of tuples
data_to_insert = [tuple(x) for x in subtype_df.values]

# SQL query with placeholders
sql = "INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)"

# Execute and commit
cursor.executemany(sql, data_to_insert)
conn.commit() # Vital: changes won't save without this

print(f"{cursor.rowcount} records inserted.")
cursor.close()
conn.close()

136 records inserted.

In [ ]:
cursor.execute("CREATE TABLE IF NOT EXISTS subtype (subtype_id INT, subtype VARCHAR(%s) PRIMARY KEY", (longest,))

In [ ]:
for index, subtype in enumerate(subtypes, start=1):
    cursor.execute("INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)" (index, subtype))

In [37]:
df["expansion_symbol"].unique()

array(['Ice Age', 'Alliances', 'Visions', 'Portal', 'Stronghold',
       'Exodus', 'Portal 2', "Urza's Saga", "Urza's Legacy",
       'Starter 1999', 'Mercadian Masques', 'Sixth Edition', 'Nemesis',
       'Prophecy', 'Invasion', 'Seventh Edition', 'Planeshift', 'Odyssey',
       'Torment', 'Judgement', 'Legions', 'Scourge', 'Mirrodin',
       'Darksteel', 'Fifth Dawn', 'Fifth Dawn ', 'Champions of Kamigawa',
       'Betrayers of Kamigawa', 'Ninth Edition', 'Ravnica', 'Guildpact',
       'Eighth Edition', 'Dissension', 'Coldsnap', 'Time Spiral',
       'Time Spiral ', 'Time Sprial', 'Planar Chaos', 'Planar Chaos ',
       'Futuresight', 'Lorwyn', 'Morningtide', 'Shadowmoor', 'Shdaowmoor',
       'Eventide', 'Shards of Alara', 'Conflux', 'Alara Reborn', 'M10',
       'M10 ', 'Tenth Edition', 'Zendikar', 'Worldwake', 'Wordlwake',
       'Rise of Eldrazi', 'M11'], dtype=object)

In [38]:
expansion_symbol_arr = df["expansion_symbol"].unique()

In [39]:
expansion_symbol_df = pd.DataFrame(expansion_symbol_arr)

In [40]:
expansion_symbol_df

                        0
0                 Ice Age
1               Alliances
2                 Visions
3                  Portal
4              Stronghold
5                  Exodus
6                Portal 2
7             Urza's Saga
8           Urza's Legacy
9            Starter 1999
10      Mercadian Masques
11          Sixth Edition
12                Nemesis
13               Prophecy
14               Invasion
15        Seventh Edition
16             Planeshift
17                Odyssey
18                Torment
19              Judgement
20                Legions
21                Scourge
22               Mirrodin
23              Darksteel
24             Fifth Dawn
25            Fifth Dawn
26  Champions of Kamigawa
27  Betrayers of Kamigawa
28          Ninth Edition
29                Ravnica
30              Guildpact
31         Eighth Edition
32             Dissension
33               Coldsnap
34            Time Spiral
35           Time Spiral
36            Time Sprial
37           Planar Chaos
38          Planar Chaos
39            Futuresight
40                 Lorwyn
41            Morningtide
42             Shadowmoor
43             Shdaowmoor
44               Eventide
45        Shards of Alara
46                Conflux
47           Alara Reborn
48                    M10
49                   M10
50          Tenth Edition
51               Zendikar
52              Worldwake
53              Wordlwake
54        Rise of Eldrazi
55                    M11

In [41]:
expansion_symbol_df['expansion_symbol_id'] = range(1, len(expansion_symbol_df) + 1)

In [42]:
expansion_symbol_df

                        0  expansion_symbol_id
0                 Ice Age                    1
1               Alliances                    2
2                 Visions                    3
3                  Portal                    4
4              Stronghold                    5
5                  Exodus                    6
6                Portal 2                    7
7             Urza's Saga                    8
8           Urza's Legacy                    9
9            Starter 1999                   10
10      Mercadian Masques                   11
11          Sixth Edition                   12
12                Nemesis                   13
13               Prophecy                   14
14               Invasion                   15
15        Seventh Edition                   16
16             Planeshift                   17
17                Odyssey                   18
18                Torment                   19
19              Judgement                   20
20                Legions                   21
21                Scourge                   22
22               Mirrodin                   23
23              Darksteel                   24
24             Fifth Dawn                   25
25            Fifth Dawn                    26
26  Champions of Kamigawa                   27
27  Betrayers of Kamigawa                   28
28          Ninth Edition                   29
29                Ravnica                   30
30              Guildpact                   31
31         Eighth Edition                   32
32             Dissension                   33
33               Coldsnap                   34
34            Time Spiral                   35
35           Time Spiral                    36
36            Time Sprial                   37
37           Planar Chaos                   38
38          Planar Chaos                    39
39            Futuresight                   40
40                 Lorwyn                   41
41            Morningtide                   42
42             Shadowmoor                   43
43             Shdaowmoor                   44
44               Eventide                   45
45        Shards of Alara                   46
46                Conflux                   47
47           Alara Reborn                   48
48                    M10                   49
49                   M10                    50
50          Tenth Edition                   51
51               Zendikar                   52
52              Worldwake                   53
53              Wordlwake                   54
54        Rise of Eldrazi                   55
55                    M11                   56