In [193]:
import pandas as pd
import glob
# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17/*.csv")
# 2. Use list comprehension to read all files and concat them
ice_age_strixhaven = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [194]:
ice_age_strixhaven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3763 entries, 0 to 3762
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           3762 non-null   float64
 1   card_name              3761 non-null   object
 2   supertype              35 non-null     object
 3   subtype_a              332 non-null    object
 4   subtype_b              3619 non-null   object
 5   subtype_c              2326 non-null   object
 6   subtype_d              1093 non-null   object
 7   subtype_e              58 non-null     object
 8   expansion_symbol       3756 non-null   object
 9   rarity                 3751 non-null   object
 10  artist_information_a   3756 non-null   object
 11  artist_information_b   91 non-null     object
 12  collectors_number      3755 non-null   object
 13  expansion_total_cards  3715 non-null   float64
 14  mana_cost              3625 non-null   object
 15  text_box               3647 non-null   object
 16  flavor_text            2803 non-null   object
 17  punch                  2006 non-null   object
 18  toughness              2003 non-null   object
 19  starting_loyalty       9 non-null      object
 20  quantity               3748 non-null   object
dtypes: float64(2), object(19)
memory usage: 617.5+ KB

In [195]:
harry_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet1.csv")

In [196]:
harry_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              211 non-null    int64
 1   card_name                 211 non-null    object
 2   supertype                 28 non-null     object
 3   subtype_a                 211 non-null    object
 4   subtype_b                 119 non-null    object
 5   subtype_c                 65 non-null     object
 6   subtype_d                 2 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          211 non-null    object
 10  rarity                    211 non-null    object
 11  artist_information_a      210 non-null    object
 12  artist_information_b      8 non-null      object
 13  collectors_number         210 non-null    object
 14  expansion_total           202 non-null    float64
 15  mana_cost                 209 non-null    object
 16  text_box                  207 non-null    object
 17  flavor_text               125 non-null    object
 18  punch                     103 non-null    object
 19  toughness                 103 non-null    object
 20  quantity                  210 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           1 non-null      object
 29  split_mana_cost           1 non-null      object
 30  split_subtype_a           1 non-null      object
 31  split_text_box            1 non-null      object
 32  loyalty_cost_a            3 non-null      float64
 33  loyalty_ability_a         3 non-null      object
 34  loyalty_cost_b            4 non-null      object
 35  loyalty_ability_b         4 non-null      object
 36  loyalty_cost_c            4 non-null      float64
 37  loyalty_ability_c         4 non-null      object
 38  starting_loyalty          4 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       1 non-null      object
 48  transform_supertype       0 non-null      float64
 49  transform_subtype_a       1 non-null      object
 50  transform_subtype_b       1 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        1 non-null      object
 53  transform_flavor_text     0 non-null      float64
 54  transform_punch           1 non-null      float64
 55  transform_toughness       1 non-null      float64
 56  modal_card_name           4 non-null      object
 57  modal_mana_cost           4 non-null      object
 58  modal_supertype           2 non-null      object
 59  modal_subtype_c           4 non-null      object
 60  modal_subtype_b           2 non-null      object
 61  modal_subtype_a           2 non-null      object
 62  modal_text_box            4 non-null      object
 63  modal_punch               2 non-null      float64
 64  modal_toughness           2 non-null      float64
 65  saga_card_name            1 non-null      object
 66  lore_counter_a            1 non-null      object
 67  lore_text_box_a           1 non-null      object
 68  lore_counter_b            1 non-null      object
 69  lore_counter_text_box     1 non-null      object
 70  saga_supertype            1 non-null      object
 71  saga_subtype_a            1 non-null      object
 72  saga_subtype_b            1 non-null      object
 73  saga_subtype_c            1 non-null      object
 74  saga_subtype_d            1 non-null      object
 75  saga_punch                1 non-null      float64
 76  saga_toughness            1 non-null      float64
dtypes: float64(31), int64(1), object(45)
memory usage: 127.1+ KB

In [197]:
harry_binder = harry_binder.drop(columns='subtype_d.1')

In [198]:
harry_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [199]:
spencer_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet2.csv")

In [200]:
spencer_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              176 non-null    int64
 1   card_name                 176 non-null    object
 2   supertype                 16 non-null     object
 3   subtype_a                 176 non-null    object
 4   subtype_b                 111 non-null    object
 5   subtype_c                 56 non-null     object
 6   subtype_d                 3 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          176 non-null    object
 10  rarity                    176 non-null    object
 11  artist_information_a      169 non-null    object
 12  artist_information_b      5 non-null      object
 13  collectors_number         176 non-null    object
 14  expansion_total           176 non-null    int64
 15  mana_cost                 170 non-null    object
 16  text_box                  168 non-null    object
 17  flavor_text               96 non-null     object
 18  punch                     93 non-null     object
 19  toughness                 93 non-null     object
 20  quantity                  171 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           0 non-null      float64
 29  split_mana_cost           0 non-null      float64
 30  split_subtype_a           0 non-null      float64
 31  split_text_box            0 non-null      float64
 32  loyalty_cost_a            8 non-null      float64
 33  loyalty_ability_a         8 non-null      object
 34  loyalty_cost_b            8 non-null      object
 35  loyalty_ability_b         8 non-null      object
 36  loyalty_cost_c            8 non-null      float64
 37  loyalty_ability_c         8 non-null      object
 38  starting_loyalty          8 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       4 non-null      object
 48  transform_supertype       3 non-null      object
 49  transform_subtype_a       4 non-null      object
 50  transform_subtype_b       3 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        4 non-null      object
 53  transform_flavor_text     2 non-null      object
 54  transform_punch           4 non-null      float64
 55  transform_toughness       4 non-null      float64
 56  modal_card_name           0 non-null      float64
 57  modal_mana_cost           0 non-null      float64
 58  modal_supertype           0 non-null      float64
 59  modal_subtype_c           0 non-null      float64
 60  modal_subtype_b           0 non-null      float64
 61  modal_subtype_a           0 non-null      float64
 62  modal_text_box            0 non-null      float64
 63  modal_punch               0 non-null      float64
 64  modal_toughness           0 non-null      float64
 65  saga_card_name            0 non-null      float64
 66  lore_counter_a            0 non-null      float64
 67  lore_text_box_a           0 non-null      float64
 68  lore_counter_b            0 non-null      float64
 69  lore_counter_text_box     0 non-null      float64
 70  saga_supertype            0 non-null      float64
 71  saga_subtype_a            0 non-null      float64
 72  saga_subtype_b            0 non-null      float64
 73  saga_subtype_c            0 non-null      float64
 74  saga_subtype_d            0 non-null      float64
 75  saga_punch                0 non-null      float64
 76  saga_toughness            0 non-null      float64
dtypes: float64(49), int64(2), object(26)
memory usage: 106.0+ KB

In [201]:
spencer_binder.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_d.1', 'subtype_e',
       'expansion_symbol', 'rarity', 'artist_information_a',
       'artist_information_b', 'collectors_number', 'expansion_total',
       'mana_cost', 'text_box', 'flavor_text', 'punch', 'toughness',
       'quantity', 'flip_card_name', 'flip_subtype_a', 'flip_subtype_b',
       'flip_subtype_c', 'flip_subtype_d', 'flip_punch', 'flip_toughness',
       'split_card_name', 'split_mana_cost', 'split_subtype_a',
       'split_text_box', 'loyalty_cost_a', 'loyalty_ability_a',
       'loyalty_cost_b', 'loyalty_ability_b', 'loyalty_cost_c',
       'loyalty_ability_c', 'starting_loyalty', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness'],
      dtype='object')

In [202]:
spencer_binder = spencer_binder.drop(columns='subtype_d.1')

In [203]:
spencer_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [204]:
rise_of_eldrazi = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet3.csv")

In [205]:
rise_of_eldrazi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           130 non-null    int64
 1   card_name              130 non-null    object
 2   supertype              1 non-null      object
 3   subtype_a              4 non-null      object
 4   subtype_b              129 non-null    object
 5   subtype_c              91 non-null     object
 6   subtype_d              46 non-null     object
 7   subtype_e              0 non-null      float64
 8   expansion_symbol       130 non-null    object
 9   rarity                 130 non-null    object
 10  artist_information_a   130 non-null    object
 11  artist_information_b   6 non-null      object
 12  collectors_number      130 non-null    int64
 13  expansion_total_cards  130 non-null    int64
 14  mana_cost              129 non-null    object
 15  text_box               127 non-null    object
 16  flavor_text            99 non-null     object
 17  punch                  74 non-null     float64
 18  toughness              74 non-null     float64
 19  starting_loyalty       0 non-null      float64
 20  quantity               130 non-null    int64
dtypes: float64(4), int64(4), object(13)
memory usage: 21.5+ KB

In [206]:
rise_of_eldrazi.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity'],
      dtype='object')

In [207]:
import numpy as np
# Add columns to the eldrazi sheet, fill with nan
rise_of_eldrazi[['flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']] = np.nan

In [208]:
# Reorder the columns so starting loyalty is grouped with the planeswalker attributes
rise_of_eldrazi = rise_of_eldrazi[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [209]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [210]:
ice_age_strixhaven.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity'],
      dtype='object')

In [211]:
ice_age_strixhaven[['flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']] = np.nan

In [212]:
ice_age_strixhaven = ice_age_strixhaven[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [213]:
ice_age_strixhaven

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3758,2294.0,Stampeding Rhino,NaN,NaN,Creature,Rhino,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3759,2295.0,Titanic Growth,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3760,2296.0,Trollhide,NaN,NaN,Enchantment,Aura,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3761,2297.0,Vastwood Gorger,NaN,NaN,Creature,Wurm,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3762,2298.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [214]:
collection = pd.concat([ice_age_strixhaven, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

In [215]:
collection.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness'],
      dtype='object')

In [216]:
collection[collection.loc[:, 'card_name':'quantity'].isna().all(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
2009,3593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2375,912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [217]:
collection = collection.drop([2009, 2375])

In [218]:
collection[collection['artist_information_a'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
378,379.0,Suq'Ata Lancer,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Timeshifted Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,380.0,Tectonic Fiend,NaN,NaN,Creature,Elemental,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2109,3690.0,Cemetery Reaper,NaN,NaN,Creature,Zombie,NaN,NaN,M12,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3149,1685.0,Territorial Baloth,NaN,NaN,Creature,Beast,NaN,NaN,Zendikar,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3879,4049.0,Curse of Stalked Prey,NaN,Enchantment,Aura,Curse,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,4050.0,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3881,4051.0,Stormkirk Noble,NaN,Creature,Vampire,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3882,4052.0,Hellrider,NaN,Creature,Devil,NaN,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3883,4053.0,Markov Blademaster,NaN,Creature,Vampire,Warrior,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3884,4054.0,"Gisela, Blade of Goldnight",Legendary,Creature,Angel,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3885,4055.0,Hound of Griselbrand,NaN,Creature,Elemental,Hound,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [219]:
collection.at[378, 'artist_information_a'] = 'Jeff Miracola'
collection.at[379, 'artist_information_a'] = 'Mark Tedin'
collection.at[2109, 'artist_information_a'] = 'Dave Allsop'
collection.at[3149, 'artist_information_a'] = 'Jesper Ejsing'
collection.at[3879, 'artist_information_a'] = 'Christopher Moeller'
collection.at[3880, 'artist_information_a'] = 'David Rapoza'
collection.at[3881, 'artist_information_a'] = 'James Ryman'
collection.at[3882, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3883, 'artist_information_a'] = 'Jana Schirmer'
collection.at[3883, 'artist_information_b'] = 'Johannes Voss'
collection.at[3884, 'artist_information_a'] = 'Jason Chan'
collection.at[3885, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3948, 'artist_information_a'] = 'Christopher Moeller'

In [220]:
collection[collection['expansion_symbol'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1598,3219.0,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,3220.0,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,3221.0,Winter Orb,NaN,Artifact,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,3577.0,Brushland,NaN,NaN,Land,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [221]:
collection.loc[1598, ['subtype_b', 'subtype_c', 'subtype_d', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', np.nan, np.nan, 'Fourth Edition', 'Uncommon', 118, 378, '{1}{B}', 'Take target creature from any graveyard and put it directly into play under your control with -1/-0. Treat this creature as though it were just summoned. If Animate Dead is removed, bury the creature in its owner\'s graveyard.', 1]
collection.loc[1599, ['subtype_b', 'subtype_c', 'subtype_d', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', np.nan, np.nan, 'Revised Edition', 'Uncommon', 93, 306, '{1}{B}', 'Enchant creature card in a graveyard\nWhen this Aura enters, if it\'s on the battlefield, it loses "enchant creature card in a graveyard" and gains "enchant creature put onto the battlefield with this Aura." Return enchanted creature card to the battlefield under your control and attach this Aura to it. When this Aura leaves the battlefield, that creature\'s controller sacrifices it.', 1]
collection.loc[1600, ['subtype_b', 'expansion_symbol', 'rarity', 'artist_information_a','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Artifact', 'Revised Edition', 'Rare', 'Mark Tedin', 280, 306, '{2}', 'A player may not untap more than one land during the untap phase of each of his or her turns.', 1]
collection.loc[1757, ['subtype_b', 'subtype_c', 'expansion_symbol', 'rarity', 'artist_information_a', 'collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'punch', 'toughness', 'quantity']] = ['Creature', 'Ooze', 'M12', 'Uncommon', 'Karl Kopinski', 161, 249, '{3}{G}{G}', 'Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) When Acidic Slime enters the battlefield, destroy target artifact, enchantment, or land.', 2, 2, 1]
collection.loc[1993, ['card_name', 'subtype_b', 'expansion_symbol', 'rarity', 'artist_information_a', 'collectors_number', 'expansion_total_cards', 'text_box', 'quantity']] = ['Brushland', 'Land', 'Fifth Edition', 'Rare', 'Tom Wänerstrand', 414, 449, '{T}: Add one colorless mana to your mana pool.\n{T}: Add {G} or {W} to your mana pool.\nBrushland deals 1 damage to you.', 1]

In [222]:
collection[collection['expansion_total_cards'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
6,7.0,Resistance Fighter,NaN,NaN,Creature,Soldier,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8.0,Fireblast,NaN,NaN,Instant,NaN,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9.0,Lichenthrope,NaN,NaN,Creature,Lichenthrope,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10.0,Quirion Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11.0,Stampeding Wildebeests,NaN,NaN,Creature,Wildebeests,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12.0,Lava Axe,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13.0,Volcanic Hammer,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14.0,Contemplation,NaN,NaN,Enchantment,NaN,NaN,NaN,Stronghold,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15.0,Soul Warden,NaN,NaN,Creature,Ceric,NaN,NaN,Exodus,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16.0,Talas Merchant,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17.0,Air Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18.0,Touch of Brilliance,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19.0,Talas Researcher,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20.0,False Summoning,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21.0,Talas Air Ship,NaN,NaN,Creature,Ship,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22.0,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23.0,Talas Scout,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24.0,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25.0,Exhaustion,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26.0,Talas Explorer,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27.0,Time Ebb,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28.0,Talas Warrior,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29.0,Monstrous Growth,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30.0,Alluring Scent,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31.0,Wild Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32.0,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33.0,River Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34.0,Norwood Riders,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35.0,Norwood Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36.0,Norwood Archers,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37.0,Golden Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38.0,Bear Cub,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39.0,Ironhoof Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40.0,Angel of Fury,NaN,NaN,Creature,Angel,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41.0,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,3574.0,"Ishgard, the Holy See",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991,3575.0,"Lindblum, Industrial Regency",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028,3612.0,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,NaN,Starter 2000,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2097,3678.0,"Jill, Shiva's Dominant",Legendary,NaN,Creature,Human,Noble,Warrior,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,3721.0,The Darkness Crystal,Legendary,Artifact,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,NaN,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3722.0,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3976,3759.0,"Raubahn, Bull of Ala Mhigo",Legendary,Creature,Human,Warrior,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4054,3837.0,Summoner's Grimoire,NaN,Artifact,Equipment,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4055,3838.0,A Realm Reborn,NaN,Enchantment,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4100,3883.0,The Regalia,Legendary,Artifact,Vehicle,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4101,3884.0,"Ultima, Origin of Oblivion",Legendary,Creature,God,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4145,3928.0,"Sin, Spira's Punishment",Legendary,Creature,Leviathan,Avatar,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4146,3929.0,"Joshua, Phoenix's Dominant",Legendary,Creature,Human,Noble,Wizard,NaN,Universes Beyond: Final Fantasy,Rare,...,Rising Flames — Phoenix deals 2 damage to each...,III,Flames of Rebirth — Return any number of targe...,Legendary,Enchantment,Creature,Saga,Phoenix,4.0,4.0

In [223]:
collection.loc[collection['expansion_symbol'] == 'Visions', 'expansion_total_cards'] = 167
collection.loc[collection['expansion_symbol'] == 'Portal', 'expansion_total_cards'] = 222
collection.loc[collection['expansion_symbol'] == 'Stronghold', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Exodus', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Portal 2', 'expansion_total_cards'] = 165
collection.loc[collection['expansion_symbol'] == 'Universes Beyond: Final Fantasy', 'expansion_total_cards'] = 309
collection.loc[collection['expansion_symbol'] == 'Starter 2000', 'expansion_total_cards'] = 20
collection.loc[collection['expansion_symbol'] == 'Strixhaven', 'expansion_total_cards'] = 393
collection.loc[collection['expansion_symbol'] == 'Morningtide', 'expansion_total_cards'] = 150

In [224]:
# Some of the cards are double-faced and the collectors number is followed with an a or b depending on the face
collection[collection['collectors_number'].str.contains('[a-zA-Z]', na=False)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
5,6.0,Phantasmal Fiend,NaN,NaN,Creature,Illusion,NaN,NaN,Alliances,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,2299.0,Cloistered Youth,NaN,NaN,Creature,Human,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,2307.0,Civilized Scholar,NaN,NaN,Creature,Human,Advisor,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2321.0,Screeching Bat,NaN,NaN,Creature,Bat,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,2326.0,Hanweir Watchkeep,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,2333.0,Gatstaf Shepherd,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
717,2338.0,Ulvenwald Mystics,NaN,NaN,Creature,Human,Shaman,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
742,2363.0,Thraben Sentry,NaN,NaN,Creature,Human,Soldier,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,2418.0,Tormented Pariah,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,2421.0,Village Ironsmith,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,2429.0,Grizzled Outcasts,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,2439.0,Villagers of Estwald,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
826,2447.0,Chalice of Life,NaN,Artifact,NaN,NaN,NaN,NaN,Dark Ascension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,2458.0,Loyal Cathar,NaN,NaN,Creature,Human,Soldier,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936,2557.0,Afflicted Deserter,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,2563.0,Lambholt Elder,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,2584.0,Chosen of Markov,NaN,NaN,Creature,Human,NaN,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
975,2596.0,Hinterland Hermit,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984,2605.0,Scorned Villager,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,3373.0,Delver of Secrets,NaN,NaN,Creature,Human,Wizard,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3822,3992.0,Ludevic's Test Subject,NaN,Creature,Lizard,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3960,3743.0,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [225]:
collection.loc[5, ['collectors_number']] = 57
collection.loc[678, ['collectors_number']] = 8
collection.loc[686, ['collectors_number']] = 47
collection.loc[700, ['collectors_number']] = 114
collection.loc[705, ['collectors_number']] = 145
collection.loc[712, ['collectors_number']] = 182
collection.loc[717, ['collectors_number']] = 208
collection.loc[742, ['collectors_number']] = 38
collection.loc[797, ['collectors_number']] = 165
collection.loc[800, ['collectors_number']] = 168
collection.loc[808, ['collectors_number']] = 185
collection.loc[818, ['collectors_number']] = 209
collection.loc[826, ['collectors_number']] = 146
collection.loc[837, ['collectors_number']] = 13
collection.loc[936, ['collectors_number']] = 81
collection.loc[942, ['collectors_number']] = 122
collection.loc[963, ['collectors_number']] = 55
collection.loc[975, ['collectors_number']] = 94
collection.loc[984, ['collectors_number']] = 125
collection.loc[1752, ['collectors_number']] = 51
collection.loc[3822, ['collectors_number']] = 64
collection.loc[3960, ['collectors_number']] = 152

In [226]:
collection[collection['collectors_number'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
2028,3612.0,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,NaN,Starter 2000,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [227]:
collection.loc[2028, ['collectors_number']] = 3
collection.loc[3948, ['collectors_number']] = 110

In [228]:
collection

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [229]:
collection['collectors_number'] = collection['collectors_number'].astype(int)

In [230]:
collection['expansion_total_cards'] = collection['expansion_total_cards'].astype(int)

In [231]:
collection[collection['expansion_symbol'] == 'Lorwyn'].sort_values(by='collectors_number')

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
3777,3947.0,Ajani Goldmane,NaN,Planeswalker,Ajani,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2163,700.0,Avian Changeling,NaN,NaN,Creature,Shapeshifter,NaN,NaN,Lorwyn,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2287,824.0,Battle Mastery,NaN,NaN,Enchantment,Aura,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2045,3626.0,"Brigid, Hero of Kinsbaile",Legendary,NaN,Creature,Kithkin,Archer,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,825.0,Burrenton Forge-Tender,NaN,NaN,Creature,Kithkin,Wizard,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2283,820.0,Vivid Creek,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2284,821.0,Vivid Grove,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2285,822.0,Vivid Marsh,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2286,823.0,Vivid Meadow,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,3599.0,Windbrisk Heights,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [232]:
collection['permanent_id'] = range(1, len(collection) + 1)

In [233]:
collection.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4278 entries, 0 to 4279
Data columns (total 76 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              4278 non-null   int64
 1   card_name                 4278 non-null   object
 2   supertype                 80 non-null     object
 3   subtype_a                 723 non-null    object
 4   subtype_b                 3980 non-null   object
 5   subtype_c                 2537 non-null   object
 6   subtype_d                 1142 non-null   object
 7   subtype_e                 58 non-null     object
 8   expansion_symbol          4278 non-null   object
 9   rarity                    4273 non-null   object
 10  artist_information_a      4278 non-null   object
 11  artist_information_b      111 non-null    object
 12  collectors_number         4278 non-null   int64
 13  expansion_total_cards     4278 non-null   int64
 14  mana_cost                 4134 non-null   object
 15  text_box                  4150 non-null   object
 16  flavor_text               3123 non-null   object
 17  punch                     2277 non-null   object
 18  toughness                 2274 non-null   object
 19  quantity                  4260 non-null   object
 20  flip_card_name            0 non-null      float64
 21  flip_subtype_a            0 non-null      float64
 22  flip_subtype_b            0 non-null      float64
 23  flip_subtype_c            0 non-null      float64
 24  flip_subtype_d            0 non-null      float64
 25  flip_punch                0 non-null      float64
 26  flip_toughness            0 non-null      float64
 27  split_card_name           1 non-null      object
 28  split_mana_cost           1 non-null      object
 29  split_subtype_a           1 non-null      object
 30  split_text_box            1 non-null      object
 31  loyalty_cost_a            11 non-null     float64
 32  loyalty_ability_a         11 non-null     object
 33  loyalty_cost_b            12 non-null     object
 34  loyalty_ability_b         12 non-null     object
 35  loyalty_cost_c            12 non-null     float64
 36  loyalty_ability_c         12 non-null     object
 37  starting_loyalty          12 non-null     float64
 38  leveler_tier_a            0 non-null      float64
 39  leveler_text_box_a        0 non-null      float64
 40  leveler_tier_a_punch      0 non-null      float64
 41  leveler_tier_a_toughness  0 non-null      float64
 42  leveler_tier_b            0 non-null      float64
 43  leveler_text_box_b        0 non-null      float64
 44  leveler_tier_b_punch      0 non-null      float64
 45  leveler_tier_b_toughness  0 non-null      float64
 46  transform_card_name       5 non-null      object
 47  transform_supertype       3 non-null      object
 48  transform_subtype_a       5 non-null      object
 49  transform_subtype_b       4 non-null      object
 50  transform_subtype_c       0 non-null      float64
 51  transform_text_box        5 non-null      object
 52  transform_flavor_text     2 non-null      object
 53  transform_punch           5 non-null      float64
 54  transform_toughness       5 non-null      float64
 55  modal_card_name           4 non-null      object
 56  modal_mana_cost           4 non-null      object
 57  modal_supertype           2 non-null      object
 58  modal_subtype_c           4 non-null      object
 59  modal_subtype_b           2 non-null      object
 60  modal_subtype_a           2 non-null      object
 61  modal_text_box            4 non-null      object
 62  modal_punch               2 non-null      float64
 63  modal_toughness           2 non-null      float64
 64  saga_card_name            1 non-null      object
 65  lore_counter_a            1 non-null      object
 66  lore_text_box_a           1 non-null      object
 67  lore_counter_b            1 non-null      object
 68  lore_counter_text_box     1 non-null      object
 69  saga_supertype            1 non-null      object
 70  saga_subtype_a            1 non-null      object
 71  saga_subtype_b            1 non-null      object
 72  saga_subtype_c            1 non-null      object
 73  saga_subtype_d            1 non-null      object
 74  saga_punch                1 non-null      float64
 75  saga_toughness            1 non-null      float64
dtypes: float64(25), int64(3), object(48)
memory usage: 2.6+ MB

In [234]:
collection[collection['rarity'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1601,1602,Terror,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1602,1603,Storm Crow,NaN,NaN,Creature,Bird,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1603,1604,Counterspell,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1604,1605,Unsummon,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1605,1606,Boomerang,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [235]:
collection.loc[1601, ['rarity']] = 'Common'
collection.loc[1602, ['rarity']] = 'Common'
collection.loc[1603, ['rarity']] = 'Common'
collection.loc[1604, ['rarity']] = 'Common'
collection.loc[1605, ['rarity']] = 'Common'

In [236]:
collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Legend', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound',
       'Insect', 'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Snow',
       'Sliver', 'Legendary', 'Eye', 'Gargoyle', 'Orgg', 'Avatar',
       'Fungus', 'Kithkin', 'Merfolk', 'Gorgon', 'Leech', 'Kor',
       'Encahntment', 'Serpent', 'Homarid', 'Orc', 'Shapeshifter',
       'Shade', 'Wraith', 'Cyclops', 'Tribal', 'Forest', 'Ouphe', 'Myr',
       'Vampire', 'Bat', 'Curse', 'Werewolf', 'Treefolk', 'Juggernaut',
       'Construct', 'Fox', 'Homunculus', 'Devil', 'Boar', 'Scarecrow',
       'Elk', 'Demon', 'Lizard', 'Kraken', 'Gate', 'Fish', 'Leviathan',
       'Jellyfish', 'Hommunculus', 'Vedalken', 'Crocodile', 'Eldrazi',
       'Drone', 'Ally', 'Planeswalker', 'Venser', 'Sphinx', 'Slith',
       'Worm', 'Koth', 'Thopter', 'Enchatment', 'Common', 'Dragon',
       'Encahantment', "Urza's", 'Jace', 'Praetor', 'Ooze', 'Archon',
       'Rhino', 'Gideon', 'Tamiyo', 'Mana Source', 'Ajani', 'Desert',
       'Lesson', 'Dog', 'Djinn', 'Warlock', 'Specter', 'Fog', 'Dwarf',
       'Squirrel', 'Relic', 'Town', 'Legendary ', 'Noble', 'Rowan',
       'Instinct', 'Island', 'Hag', 'Noggle', 'Gobiln', 'Artificer',
       'Unicorn', 'Antelope', 'Funugs', 'Trap', 'Surrakar', 'Horse',
       'Gremlin', 'Hellion', 'Siren', 'Dragon ', 'Salamander', 'Creatue',
       'Lord', 'Legendary Creature', 'Sorin', 'Phoenix', 'Legedary',
       'Chandra', 'Tibalt', 'Equpiment', 'Manticore', 'Efreet', 'Hydra',
       'Garruk', 'Vehicle', 'God', 'Elder', 'Scorpion', 'Blast'],
      dtype=object)

In [292]:
df_subtype = pd.DataFrame({'subtype':collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()})

In [293]:
df_subtype['subtype_id'] = range(1, len(df_subtype) + 1)

In [296]:
df_subtype = df_subtype[['subtype_id', 'subtype']]

In [299]:
df_subtype

     subtype_id       subtype
0             1   Enchantment
1             2          Aura
2             3      Creature
3             4      Illusion
4             5      Artifact
5             6       Soldier
6             7       Instant
7             8  Lichenthrope
8             9           Elf
9            10   Wildebeests
10           11       Sorcery
11           12         Ceric
12           13      Merchant
13           14     Elemental
14           15        Wizard
15           16          Ship
16           17        Pirate
17           18            Ox
18           19      Basilisk
19           20          Bear
20           21         Elves
21           22         Angel
22           23        Cleric
23           24           Imp
24           25      Viashino
25           26          Wolf
26           27        Knight
27           28       Griffin
28           29         Thief
29           30        Zombie
30           31           Rat
31           32         Rebel
32           33       Pegasus
33           34          Bird
34           35         Drake
35           36        Thrull
36           37      Skeleton
37           38        Horror
38           39         Ghost
39           40      Minotaur
40           41         Tiger
41           42          Wall
42           43        Spider
43           44           Cat
44           45       Warrior
45           46          Wurm
46           47      Elephant
47           48         Golem
48           49     Mercenary
49           50   Spellshaper
50           51          Land
51           52        Legend
52           53         Beast
53           54          Kavu
54           55         Nomad
55           56        Mystic
56           57         Hound
57           58        Insect
58           59         Druid
59           60   Incarnation
60           61     Nightmare
61           62          Crab
62           63     Barbarian
63           64       Centaur
64           65        Spirit
65           66     Equipment
66           67         Troll
67           68         Human
68           69        Shaman
69           70        Arcane
70           71          Monk
71           72        Turtle
72           73        Goblin
73           74       Advisor
74           75         Dryad
75           76      Assassin
76           77          Ogre
77           78     Berserker
78           79         Rogue
79           80        Archer
80           81         Giant
81           82          Frog
82           83        Mutant
83           84        Faerie
84           85         Scout
85           86         Snake
86           87         Plant
87           88          Snow
88           89        Sliver
89           90     Legendary
90           91           Eye
91           92      Gargoyle
92           93          Orgg
93           94        Avatar
94           95        Fungus
95           96       Kithkin
96           97       Merfolk
97           98        Gorgon
98           99         Leech
99          100           Kor
100         101   Encahntment
101         102       Serpent
102         103       Homarid
103         104           Orc
104         105  Shapeshifter
105         106         Shade
106         107        Wraith
107         108       Cyclops
108         109        Tribal
109         110        Forest
110         111         Ouphe
111         112           Myr
112         113       Vampire
113         114           Bat
114         115         Curse
115         116      Werewolf
116         117      Treefolk
117         118    Juggernaut
118         119     Construct
119         120           Fox
120         121    Homunculus
121         122         Devil
122         123          Boar
123         124     Scarecrow
124         125           Elk
125         126         Demon
126         127        Lizard
127         128        Kraken
128         129          Gate
129         130          Fish
130         131     Leviathan
131         132     Jellyfish
132         133   Hommunculus
133         134      Vedalken
134         135     Crocodile
135         136       Eldrazi
136         137         Drone
137         138          Ally
138         139  Planeswalker
139         140        Venser
140         141        Sphinx
141         142         Slith
142         143          Worm
143         144          Koth
144         145       Thopter
145         146    Enchatment
146         147        Common
147         148        Dragon
148         149  Encahantment
149         150        Urza's
150         151          Jace
151         152       Praetor
152         153          Ooze
153         154        Archon
154         155         Rhino
155         156        Gideon
156         157        Tamiyo
157         158   Mana Source
158         159         Ajani
159         160        Desert
160         161        Lesson
161         162           Dog
162         163         Djinn
163         164       Warlock
164         165       Specter
165         166           Fog
166         167         Dwarf
167         168      Squirrel
168         169         Relic
169         170          Town
170         171    Legendary
171         172         Noble
172         173         Rowan
173         174      Instinct
174         175        Island
175         176           Hag
176         177        Noggle
177         178        Gobiln
178         179     Artificer
179         180       Unicorn
180         181      Antelope
181         182        Funugs
182         183          Trap
183         184      Surrakar
184         185         Horse
185         186       Gremlin
186         187       Hellion
187         188         Siren
188         189       Dragon
189         190    Salamander
190         191       Creatue
191         192          Lord
192         193         Sorin
193         194       Phoenix
194         195      Legedary
195         196       Chandra
196         197        Tibalt
197         198     Equpiment
198         199     Manticore
199         200        Efreet
200         201         Hydra
201         202        Garruk
202         203       Vehicle
203         204           God
204         205         Elder
205         206      Scorpion
206         207         Blast

In [302]:

collection[collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].eq('Common').any(axis=1)]

Empty DataFrame
Columns: [permanent_id, card_name, supertype, subtype_a, subtype_b, subtype_c, subtype_d, subtype_e, expansion_symbol, rarity, artist_information_a, artist_information_b, collectors_number, expansion_total_cards, mana_cost, text_box, flavor_text, punch, toughness, quantity, flip_card_name, flip_subtype_a, flip_subtype_b, flip_subtype_c, flip_subtype_d, flip_punch, flip_toughness, split_card_name, split_mana_cost, split_subtype_a, split_text_box, loyalty_cost_a, loyalty_ability_a, loyalty_cost_b, loyalty_ability_b, loyalty_cost_c, loyalty_ability_c, starting_loyalty, leveler_tier_a, leveler_text_box_a, leveler_tier_a_punch, leveler_tier_a_toughness, leveler_tier_b, leveler_text_box_b, leveler_tier_b_punch, leveler_tier_b_toughness, transform_card_name, transform_supertype, transform_subtype_a, transform_subtype_b, transform_subtype_c, transform_text_box, transform_flavor_text, transform_punch, transform_toughness, modal_card_name, modal_mana_cost, modal_supertype, modal_subtype_c, modal_subtype_b, modal_subtype_a, modal_text_box, modal_punch, modal_toughness, saga_card_name, lore_counter_a, lore_text_box_a, lore_counter_b, lore_counter_text_box, saga_supertype, saga_subtype_a, saga_subtype_b, saga_subtype_c, saga_subtype_d, saga_punch, saga_toughness, transform_subtype_d, transform_subtype_e, flip_supertype, modal_subtype_d, modal_flavor_text, flip_text_box, split_subtype_b]
Index: []

In [301]:
collection.loc[1573, ['supertype']] = np.nan

In [239]:
# Korlash's supertype and subtype were entered as a single string
collection[collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].apply(lambda x: x.str.contains('Legendary Creature', case=False, na=False)).any(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
3834,3833,"Korlash, Heir to Blackblade",Legendary Creature,Zombie,Warrior,NaN,NaN,NaN,Futuresight,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [240]:
# The data has to be atomic to be compliant with 1NF
collection.loc[3834, ['supertype', 'subtype_a', 'subtype_b', 'subtype_c']] = ['Legendary', 'Creature', 'Zombie', 'Warrior']

In [241]:
collection[collection['card_name'].str.contains('&', regex=False)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1175,1176,Alive & Well,NaN,NaN,Sorcery,NaN,NaN,NaN,Dragon's Maze,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176,1177,Armed & Dangerous,NaN,NaN,Sorcery,NaN,NaN,NaN,Dragon's Maze,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1177,1178,Down & Dirty,NaN,NaN,Sorcery,NaN,NaN,NaN,Dragon's Maze,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [242]:
collection[collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].apply(lambda x: x.str.contains('Planeswalker', case=False, na=False)).any(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1463,1464,"Venser, the Sojourner",NaN,NaN,Planeswalker,Venser,NaN,NaN,Duel Decks: Venser vs. Koth,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1499,1500,Koth of the Hammer,NaN,NaN,Planeswalker,Koth,NaN,NaN,Duel Decks: Venser vs. Koth,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1631,1632,Jace Beleren,NaN,NaN,Planeswalker,Jace,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1745,1746,Gideon Jura,NaN,NaN,Planeswalker,Gideon,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1762,1763,"Tamiyo, the Moon Sage",NaN,NaN,Planeswalker,Tamiyo,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1777,1778,Ajani Vengeant,NaN,NaN,Planeswalker,Ajani,NaN,NaN,Shards of Alara,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2141,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3777,3776,Ajani Goldmane,NaN,Planeswalker,Ajani,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3783,3782,"Venser, the Sojourner",NaN,Planeswalker,Venser,NaN,NaN,NaN,Scars of Mirrodin,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3789,3788,Gideon Jura,NaN,Planeswalker,Gideon,NaN,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3812,3811,"Jace, Memory Adept",NaN,Planeswalker,Jace,NaN,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3831,3830,"Tamiyo, the Moon Sage",NaN,Planeswalker,Tamiyo,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3842,3841,Sorin Markov,NaN,Planeswalker,Sorin,NaN,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3862,3861,Chandra Nalaar,NaN,Planeswalker,Chandra,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3889,3888,"Tibalt, the Fiend Blooded",NaN,Planeswalker,Tibalt,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3938,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3940,3939,Chandra Nalaar,NaN,Planeswalker,Chandra,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3941,3940,"Tibalt, the Fiend-Blooded",NaN,Planeswalker,Tibalt,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,4003,Garruk Wildspeaker,NaN,Planeswalker,Garruk,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [243]:
collection[collection['card_name'].isin(['Akki Lavamancer', 'Budoka Gardener', 'Bushi Tenderfoot', 'Initiate of Blood', 'Jushi Apprentice', 'Kitsune Mystic', 'Nezumi Graverobber', 'Nezumi Shortfang', 'Orochi Eggwatcher', 'Student of Elements', 'Tide of War',
                                         'Research', 'Rise', 'Supply', 'Trial', 'Hit', 'Bound', 'Crime', 'Hide', 'Odds', 'Pure',
                                         'Alive', 'Armed', 'Beck', 'Breaking', 'Catch', 'Down', 'Far', 'Flesh', 'Give', 'Profit', 'Protect', 'Ready', 'Toil', 'Turn', 'Wear',
                                         'Beastbreaker of Bala Ged', 'Brimstone Mage', 'Caravan Escort', 'Coralhelm Commander', 'Echo Mage', 'Enclave Cryptologist', 'Guul Draz Assassin', 'Hada Spy Patrol', 'Halimar Wavewatch', 'Hedron-Field Purists', 'Hexdrinker', 'Ikral Outrider', 'Joraga Treespeaker', 'Kabira Vindicator', 'Kargan Dragonlord', 'Kazandu Tuskcaller', 'Knight of Cliffhaven', 'Lighthouse Chronologist', 'Lord of Shatterskull Pass', 'Nirkana Cutthroat', 'Null Champion', 'Skywatcher Adept', 'Student of Warfare', 'Transcendent Master', 'Zulaport Enforcer', 'Under-Construction Skyscraper',
                                         'Wandering Archaic', 'Augmenter Pugilist', 'Blex, Vexing Pest', 'Extus, Oriq Overlord', 'Flamescroll Celebrant', 'Jadzi, Oracle of Arcavios', 'Kianne, Dean of Substance', 'Mila, Crafty Companion', 'Pestilent Cauldron', 'Plargg, Dean of Chaos', 'Rowan, Scholar of Sparks', 'Selfless Glyphweaver', 'Shaile, Dean of Radiance', 'Torrent Sculptor', 'Uvilda, Dean of Perfection', 'Valentin, Dean of the Vein',
                                         'Bane of Hanweir', 'Bloodline Keeper', 'Civilized Scholar', 'Cloistered Youth', 'Daybreak Ranger', 'Delver of Secrets', 'Garruk Relentless', 'Gatsaf Howler', 'Gatstaf Shepherd', 'Grizzled Outcasts', 'Hanweir Watchkeep', 'Homicidal Brute', 'Howlpack Alpha', 'Howlpack of Estwald', 'Instigator Gang', 'Ironfang', 'Krallenhorde Wantons', 'Kruin Outlaw', 'Ludevic\'s Test Subject', 'Mayor of Avabruck', 'Merciless Predator', 'Moonmist', 'Nightfall Predator', 'Rampaging Werewolf', 'Reckless Waif', 'Screeching Bat', 'Stlking Vampire', 'Terror of Kruin Pass', 'Thraben Sentry', 'Tormented Pariah', 'Ulvenwald Mystics', 'Ulvenwald Primordials', 'Village Ironsmith', 'Villagers of Estwald', 'Wildwood Pack'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
312,313,Trial,NaN,NaN,Instant,NaN,NaN,NaN,Dissension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,679,Cloistered Youth,NaN,NaN,Creature,Human,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,687,Civilized Scholar,NaN,NaN,Creature,Human,Advisor,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,701,Screeching Bat,NaN,NaN,Creature,Bat,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,706,Hanweir Watchkeep,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,713,Gatstaf Shepherd,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
717,718,Ulvenwald Mystics,NaN,NaN,Creature,Human,Shaman,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
742,743,Thraben Sentry,NaN,NaN,Creature,Human,Soldier,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,798,Tormented Pariah,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,801,Village Ironsmith,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,809,Grizzled Outcasts,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810,811,Moonmist,NaN,NaN,Instant,NaN,NaN,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,819,Villagers of Estwald,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1614,1615,Kitsune Mystic,NaN,NaN,Creature,Fox,Wizard,NaN,Champions of Kamigawa,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,1753,Delver of Secrets,NaN,NaN,Creature,Human,Wizard,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026,2026,Student of Warfare,NaN,NaN,Creature,Human,Knight,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2057,2057,Selfless Glyphweaver,NaN,NaN,Creature,Human,Cleric,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2058,2058,Flamescroll Celebrant,NaN,NaN,Creature,Human,Shaman,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2095,2095,Torrent Sculptor,NaN,NaN,Creature,Merfolk,Wizard,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2141,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3268,3267,Joraga Treespeaker,NaN,NaN,Creature,Elf,Druid,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3822,3821,Ludevic's Test Subject,NaN,Creature,Lizard,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,3879,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3901,3900,Daybreak Ranger,NaN,Creature,Human,Archer,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3938,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3960,3959,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4047,4046,"Kianne, Dean of Substance",Legendary,Creature,Elf,Druid,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4049,4048,"Valentin, Dean of the Vein",Legendary,Creature,Vampire,Warlock,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4053,4052,Pestilent Cauldron,NaN,Artifact,NaN,NaN,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4094,4093,Wandering Archaic,NaN,Creature,Avatar,NaN,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4144,4143,Beck,NaN,Sorcery,NaN,NaN,NaN,NaN,Dragon's Maze,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4155,4154,Hada Spy Patrol,NaN,NaN,Creature,Human,Rogue,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4156,4155,Enclave Cryptologist,NaN,NaN,Creature,Merfolk,Wizard,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4162,4161,Nirkana Cutthroat,NaN,NaN,Creature,Vampire,Warrior,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4166,4165,Brimstone Mage,NaN,NaN,Creature,Human,Shaman,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4170,4169,Beastbreaker of Bala Ged,NaN,NaN,Creature,Human,Warrior,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4183,4182,Caravan Escort,NaN,NaN,Creature,Human,Knight,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4191,4190,Knight of Cliffhaven,NaN,NaN,Creature,Kor,Knight,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4208,4207,Halimar Wavewatch,NaN,NaN,Creature,Merfolk,Soldier,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4218,4217,Skywatcher Adept,NaN,NaN,Creature,Merfolk,Wizard,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4230,4229,Null Champion,NaN,NaN,Creature,Zombie,Warrior,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4235,4234,Zulaport Enforcer,NaN,NaN,Creature,Human,Warrior,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [244]:
collection['transform_subtype_d'] = np.nan
collection['transform_subtype_e'] = np.nan
collection['flip_supertype'] = np.nan
collection['modal_subtype_d'] = np.nan
collection['modal_flavor_text'] = np.nan

In [245]:
collection.loc[312, ['split_card_name', 'split_mana_cost', 'split_subtype_a', 'split_text_box']] = ['Error', '{U}{B}', 'Instant', 'Counter target multicolored spell.']
collection.loc[678, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Unholy Fiend', 'Creature', 'Horror', 'At the beginning of your end step, you lose 1 life.', 'The fiend tormented them by recounting the girl\'s memories, as if some part of her remained inside that twisted shell.', 3, 3]
collection.loc[686, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Homicidal Brute', 'Creature', 'Human', 'Mutant', 'At the beginning of your end step, if Homicidal Brute didn\'t attack this turn, tap Homicidal Brute, then transform it.', 'For a moment his basest desires run free, unshackled by reason or conscience.', 5, 1]
collection.loc[700, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Stalking Vampire', 'Creature', 'Vampire', 'At the beginning of your upkeep, you may pay {2}{B}{B}. If you do, transform Stalking Vampire.', 'Each form she takes is an exploration of the senses.', 5, 5]
collection.loc[705, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Bane of Hanweir', 'Creature', 'Werewolf', 'This creature attacks each combat if able.\nAt the beginning of each upkeep, if a player cast two or more spells last turn, transform this creature.', 'Technically he never left his post. He looks after hte wolf wherever it goes.', 5, 5]
collection.loc[712, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_punch', 'transform_toughness']] = ['Gatstaf Howler', 'Creature', 'Werewolf', 'Intimidate (This creature can\'t be blocked except by artifact creatures and/or creatures that share a color with it.)\nAt the  beginning of each upkeep, if a player cast two or more spells last turn, transform Gatstaf Howler.', 3 ,3]
collection.loc[717, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Ulvenwald Primordials', 'Creature', 'Werewolf', '{G}: Regenerate Ulvenwald Primordials.\nAt the beginning of each upkeep, if a player cast two or more spells last turn, transform Ulvenwald Primordials.', '"...and embrace the ancient ferocity of the undying Wild."', 5, 5]
collection.loc[742, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Thraben Militia', 'Creature', 'Human', 'Soldier', 'Trample', '"The time for grief is over. The time for retribution has begun."', 5, 4]
collection.loc[797, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_subtype_e', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Tormented Pariah', 'Creature', 'Human', 'Warrior', 'Werewolf', 'At the beginning of each upkeep, if no spells were cast last turn, transform Tormented Pariah.', '"Hey lads, the moon\'s rising. All the better to watch him beg for mercy."', 3, 2]
collection.loc[800, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Ironfang', 'Creature', 'Werewolf', 'First strike/nAt the beginning of each upkeep, if a player cast two or more spells last turn, transform Ironfang.', 'Each morning, he repairs the front door.', 3, 1]
collection.loc[808, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Kallenhorde Wantons', 'Creature', 'Werewolf', 'At the beginning of each upkeep, if a player cast two or more spells last turn, transform Kallenhorde Wantons.', 'The boot prints became paw prints, and they led right back into town.', 7, 7]
collection.loc[818, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Howlpack of Estwald', 'Creature', 'Werewolf', 'At the beginning of each upkeep, if a player cast two or more spells last turn, transform this creature.', 'Estwald\'s citizens don\'t dislike outsiders—they taste just fine.', 4, 6]
collection.loc[1614, ['flip_card_name', 'flip_supertype', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_text_box', 'flip_punch', 'flip_toughness']] = ['Autumn—Tail, Kitsune Sage', 'Legendary', 'Creature', 'Fox', 'Wizard', '{1}: Move target enchantment enchanting a creature to another creature.', 4, 5]
collection.loc[1752, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Insectile Aberration', 'Creature', 'Human', 'Insect', 'Flying', '"Unfortunately, all my test animals have died or escaped, so I shall be the final subject. I feel no fear. This is a momentous night."\n—Laboratory notes, final entry', 3, 2]
collection.loc[2026, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['2-6', 'First strike', 3, 3, '7+', 'Double strike', 4, 4]
collection.loc[2057, ['modal_card_name', 'modal_mana_cost', 'modal_subtype_b', 'modal_text_box', 'modal_flavor_text']] = ['Deadly Vanity', '{5}{B}{B}{B}', 'Sorcery', 'Choose a creature or planeswalker, then destroy all other creatures and planeswalkers.', 'She cast a spell to purge all weakness. When the ink cleared, she stood alone.']
collection.loc[2058, ['modal_card_name', 'modal_mana_cost', 'modal_subtype_b', 'modal_text_box', 'modal_flavor_text']] = ['Revel in Silence', '{W}{W}', 'Instant', 'Your opponents can\'t cast spells or activate planeswalkers\' loyalty abilities this turn.\nExile Revel in Silence.', '"Sit down and listen."']
collection.loc[2095, ['modal_card_name', 'modal_mana_cost', 'modal_subtype_b', 'modal_text_box', 'modal_flavor_text']] = ['Flamethrower Sonata', '{1}{R}', 'Sorcery', 'Discard a card, then draw a card. When you discard an instant or sorcery card this way, Flamethrower Sonata deals damage equal to that card\'s mana value to target creature or planeswalker you don\'t control.', 'He channels his heart\'s passion into every fiery note.']
#collection.loc[2141, ['modal_card_name', 'modal_mana_cost', 'modal_supertype', 'modal_subtype_b', 'modal_subtype_c', '
collection.loc[3268, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-4', '{T}: Add {G}{G} to your mana pool.', 1, 2, '5+', 'Elves you control have "{T}: Add {G}{G} to your mana pool."', 1, 4]
collection.loc[3822, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Ludevic\'s Abomination', 'Creature', 'Lizard', 'Horror', 'Trample', 'After several frustrating experiments, the visionary Ludevic realized he needed to create a monster that fed on torch-wielding mobs.', 13, 13]
collection.loc[3880, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_punch', 'transform_toughness']] = ['Terror of Kruin Pass', 'Creature', 'Werewolf', 'Double strike\nWerewolves you control have menace.(A creature with menace can\'t be blocked except by two or more creatures.)\nAt the  beginning of each upkeep, if a player cast two or more spells last turn, transform this creature.', 3, 3]
collection.loc[4047, ['modal_card_name', 'modal_mana_cost', 'modal_supertype', 'modal_subtype_b', 'modal_subtype_c', 'modal_subtype_d', 'modal_text_box', 'modal_punch', 'modal_toughness']] = ['Imbraham, Dean of Theory', '{2}{U}{U}', 'Legendary', 'Creature', 'Bird', 'Wizard', 'Flying\n{X}{U}{U}, {T}: Exile the top X cards of your library and put a study counter on each of them. Then you may put a card you own in exile with a study counter on it into your hand.', 3, 3]
collection.loc[4049, ['modal_card_name', 'modal_mana_cost', 'modal_supertype', 'modal_subtype_b', 'modal_subtype_c', 'modal_subtype_d', 'modal_text_box', 'modal_flavor_text','modal_punch', 'modal_toughness']] = ['Lisette, Dean of the Root', '{2}{G}{G}', 'Legendary', 'Creature', 'Human', 'Druid', 'Whenever you gain life, you may pay {1}. If you do, put a +1/+1 counter on each creature you control and those creatures gain trample until end of turn.', 'Life is as fleeting as it is vibrant. Embrace the brief blessing of a flower before it withers."', 4, 4]
collection.loc[4053, ['modal_card_name', 'modal_mana_cost', 'modal_subtype_b', 'modal_text_box', 'modal_flavor_text']] = ['Restorative Burst', '{3}{G}{G}', 'Sorcery', 'Return up to two target creature, land, and/or planeswalker cards from your graveyard to your hand. Each player gains 4 life. Exile Restorative Burst.', '"Death? Everyone doeso death. Let me show you something actually impressive."']
collection.loc[4094, ['modal_card_name', 'modal_mana_cost', 'modal_subtype_b', 'modal_text_box']] = ['Explore the Vastlands', '{3}', 'Sorcery', 'Each player looks at the top five cards of their library, reveals a land card and/or an instant or sorcery card from among them, then puts the cards they revealed this way into their hand and the rest on the bottom of their library in a random order. Each player gains 3 life.']
collection.loc[4144, ['split_card_name', 'split_mana_cost', 'split_subtype_b', 'split_text_box']] = ['Call', '{4}{W}{U}', 'Sorcery', 'Put four 1/1 white Bird creature tokens with flying onto the battlefield.']
collection.loc[4155, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-2', 'Hada Spy Patrol can\'t be blocked', 2, 2, '3+', 'Shroud/nHada Spy Patrol can\'t be blocked.', 3, 3]
collection.loc[4156, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-2', '{T}: Draw a card, then discard a card.', 0, 1, '3+', '{T}: Draw a card.', 0, 1]
collection.loc[4162, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-2', 'Deathtouch', 4, 3, '3+', 'First strike, deathtouch', 5, 4]
collection.loc[4166, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-2', '{T}: Brimstone Mage deals 1 damage to target creature or player.', 2, 3, '3+', '{T}: Brimstone Mage deals 3 damage to target creature or player.', 2, 4]
collection.loc[4170, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-3', '', 4, 4, '4+', 'Trample', 6, 6]
collection.loc[4183, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-4', '', 2, 2, '5+', 'First strike', 5, 5]
collection.loc[4191, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-3', 'Flying', 2, 3, '4+', 'Flying, vigilance', 4, 4]
collection.loc[4208, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-4', '', 0, 6, '5+', 'Islandwalk', 6, 6]
collection.loc[4218, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-2', 'Flying', 2, 2, '3+', 'Flying', 4, 2]
collection.loc[4230, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-3', '', 4, 2, '4+', '{B}: Regenerate Null Champion', 7, 3]
collection.loc[4235, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['1-2', '', 3, 3, '3+', 'Zulaport Enforcer can\'t be blocked except by black creatures.', 5, 5]

C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Horror' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[678, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Unholy Fiend', 'Creature', 'Horror', 'At the beginning of your end step, you lose 1 life.', 'The fiend tormented them by recounting the girl\'s memories, as if some part of her remained inside that twisted shell.', 3, 3]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Mutant' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[686, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Homicidal Brute', 'Creature', 'Human', 'Mutant', 'At the beginning of your end step, if Homicidal Brute didn\'t attack this turn, tap Homicidal Brute, then transform it.', 'For a moment his basest desires run free, unshackled by reason or conscience.', 5, 1]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Werewolf' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[797, ['transform_card_name', 'transform_subtype_b', 'transform_subtype_c', 'transform_subtype_d', 'transform_subtype_e', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness']] = ['Tormented Pariah', 'Creature', 'Human', 'Warrior', 'Werewolf', 'At the beginning of each upkeep, if no spells were cast last turn, transform Tormented Pariah.', '"Hey lads, the moon\'s rising. All the better to watch him beg for mercy."', 3, 2]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Autumn—Tail, Kitsune Sage' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[1614, ['flip_card_name', 'flip_supertype', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_text_box', 'flip_punch', 'flip_toughness']] = ['Autumn—Tail, Kitsune Sage', 'Legendary', 'Creature', 'Fox', 'Wizard', '{1}: Move target enchantment enchanting a creature to another creature.', 4, 5]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Legendary' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[1614, ['flip_card_name', 'flip_supertype', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_text_box', 'flip_punch', 'flip_toughness']] = ['Autumn—Tail, Kitsune Sage', 'Legendary', 'Creature', 'Fox', 'Wizard', '{1}: Move target enchantment enchanting a creature to another creature.', 4, 5]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Creature' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[1614, ['flip_card_name', 'flip_supertype', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_text_box', 'flip_punch', 'flip_toughness']] = ['Autumn—Tail, Kitsune Sage', 'Legendary', 'Creature', 'Fox', 'Wizard', '{1}: Move target enchantment enchanting a creature to another creature.', 4, 5]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Fox' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[1614, ['flip_card_name', 'flip_supertype', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_text_box', 'flip_punch', 'flip_toughness']] = ['Autumn—Tail, Kitsune Sage', 'Legendary', 'Creature', 'Fox', 'Wizard', '{1}: Move target enchantment enchanting a creature to another creature.', 4, 5]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Wizard' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[1614, ['flip_card_name', 'flip_supertype', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_text_box', 'flip_punch', 'flip_toughness']] = ['Autumn—Tail, Kitsune Sage', 'Legendary', 'Creature', 'Fox', 'Wizard', '{1}: Move target enchantment enchanting a creature to another creature.', 4, 5]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2-6' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[2026, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['2-6', 'First strike', 3, 3, '7+', 'Double strike', 4, 4]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'First strike' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[2026, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['2-6', 'First strike', 3, 3, '7+', 'Double strike', 4, 4]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '7+' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[2026, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['2-6', 'First strike', 3, 3, '7+', 'Double strike', 4, 4]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Double strike' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[2026, ['leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness']] = ['2-6', 'First strike', 3, 3, '7+', 'Double strike', 4, 4]
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'She cast a spell to purge all weakness. When the ink cleared, she stood alone.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[2057, ['modal_card_name', 'modal_mana_cost', 'modal_subtype_b', 'modal_text_box', 'modal_flavor_text']] = ['Deadly Vanity', '{5}{B}{B}{B}', 'Sorcery', 'Choose a creature or planeswalker, then destroy all other creatures and planeswalkers.', 'She cast a spell to purge all weakness. When the ink cleared, she stood alone.']
C:\Users\Spencer\AppData\Local\Temp\ipykernel_3048\41382023.py:23: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Wizard' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  collection.loc[4047, ['modal_card_name', 'modal_mana_cost', 'modal_supertype', 'modal_subtype_b', 'modal_subtype_c', 'modal_subtype_d', 'modal_text_box', 'modal_punch', 'modal_toughness']] = ['Imbraham, Dean of Theory', '{2}{U}{U}', 'Legendary', 'Creature', 'Bird', 'Wizard', 'Flying\n{X}{U}{U}, {T}: Exile the top X cards of your library and put a study counter on each of them. Then you may put a card you own in exile with a study counter on it into your hand.', 3, 3]

In [246]:
collection.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4278 entries, 0 to 4279
Data columns (total 83 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              4278 non-null   int64
 1   card_name                 4278 non-null   object
 2   supertype                 80 non-null     object
 3   subtype_a                 723 non-null    object
 4   subtype_b                 3980 non-null   object
 5   subtype_c                 2538 non-null   object
 6   subtype_d                 1142 non-null   object
 7   subtype_e                 58 non-null     object
 8   expansion_symbol          4278 non-null   object
 9   rarity                    4278 non-null   object
 10  artist_information_a      4278 non-null   object
 11  artist_information_b      111 non-null    object
 12  collectors_number         4278 non-null   int64
 13  expansion_total_cards     4278 non-null   int64
 14  mana_cost                 4134 non-null   object
 15  text_box                  4150 non-null   object
 16  flavor_text               3123 non-null   object
 17  punch                     2277 non-null   object
 18  toughness                 2274 non-null   object
 19  quantity                  4260 non-null   object
 20  flip_card_name            1 non-null      object
 21  flip_subtype_a            0 non-null      float64
 22  flip_subtype_b            1 non-null      object
 23  flip_subtype_c            1 non-null      object
 24  flip_subtype_d            1 non-null      object
 25  flip_punch                1 non-null      float64
 26  flip_toughness            1 non-null      float64
 27  split_card_name           2 non-null      object
 28  split_mana_cost           2 non-null      object
 29  split_subtype_a           2 non-null      object
 30  split_text_box            2 non-null      object
 31  loyalty_cost_a            11 non-null     float64
 32  loyalty_ability_a         11 non-null     object
 33  loyalty_cost_b            12 non-null     object
 34  loyalty_ability_b         12 non-null     object
 35  loyalty_cost_c            12 non-null     float64
 36  loyalty_ability_c         12 non-null     object
 37  starting_loyalty          12 non-null     float64
 38  leveler_tier_a            13 non-null     object
 39  leveler_text_box_a        13 non-null     object
 40  leveler_tier_a_punch      13 non-null     float64
 41  leveler_tier_a_toughness  13 non-null     float64
 42  leveler_tier_b            13 non-null     object
 43  leveler_text_box_b        13 non-null     object
 44  leveler_tier_b_punch      13 non-null     float64
 45  leveler_tier_b_toughness  13 non-null     float64
 46  transform_card_name       17 non-null     object
 47  transform_supertype       3 non-null      object
 48  transform_subtype_a       5 non-null      object
 49  transform_subtype_b       17 non-null     object
 50  transform_subtype_c       14 non-null     object
 51  transform_text_box        17 non-null     object
 52  transform_flavor_text     13 non-null     object
 53  transform_punch           17 non-null     float64
 54  transform_toughness       17 non-null     float64
 55  modal_card_name           7 non-null      object
 56  modal_mana_cost           7 non-null      object
 57  modal_supertype           2 non-null      object
 58  modal_subtype_c           4 non-null      object
 59  modal_subtype_b           7 non-null      object
 60  modal_subtype_a           2 non-null      object
 61  modal_text_box            7 non-null      object
 62  modal_punch               2 non-null      float64
 63  modal_toughness           2 non-null      float64
 64  saga_card_name            1 non-null      object
 65  lore_counter_a            1 non-null      object
 66  lore_text_box_a           1 non-null      object
 67  lore_counter_b            1 non-null      object
 68  lore_counter_text_box     1 non-null      object
 69  saga_supertype            1 non-null      object
 70  saga_subtype_a            1 non-null      object
 71  saga_subtype_b            1 non-null      object
 72  saga_subtype_c            1 non-null      object
 73  saga_subtype_d            1 non-null      object
 74  saga_punch                1 non-null      float64
 75  saga_toughness            1 non-null      float64
 76  transform_subtype_d       5 non-null      object
 77  transform_subtype_e       1 non-null      object
 78  flip_supertype            1 non-null      object
 79  modal_subtype_d           2 non-null      object
 80  modal_flavor_text         5 non-null      object
 81  flip_text_box             1 non-null      object
 82  split_subtype_b           1 non-null      object
dtypes: float64(16), int64(3), object(64)
memory usage: 2.9+ MB

In [298]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [248]:
#pd.reset_option('display.max_rows')
#pd.reset_option('display.max_columns')

In [249]:
collection['expansion_symbol'].unique()

array(['Ice Age', 'Alliances', 'Visions', 'Portal', 'Stronghold',
       'Exodus', 'Portal 2', "Urza's Saga", "Urza's Legacy",
       'Starter 1999', 'Mercadian Masques', 'Sixth Edition', 'Nemesis',
       'Prophecy', 'Invasion', 'Seventh Edition', 'Planeshift', 'Odyssey',
       'Torment', 'Judgement', 'Legions', 'Scourge', 'Mirrodin',
       'Darksteel', 'Fifth Dawn', 'Fifth Dawn ', 'Champions of Kamigawa',
       'Betrayers of Kamigawa', 'Ninth Edition', 'Ravnica', 'Guildpact',
       'Eighth Edition', 'Dissension', 'Coldsnap', 'Time Spiral',
       'Time Spiral ', 'Time Sprial', 'Planar Chaos', 'Planar Chaos ',
       'Futuresight', 'Innistrad', 'Dark Ascension', 'Avacyn Restored',
       'M13', 'Return to Ravnica', "Dragon's Maze", 'Gatecrash',
       'Gatecraash', 'Modern Masters', 'Conspiracy',
       'Battle for Zendikar', 'Duel Decks: Elves vs. Goblins',
       'Duel Decks: Sorin vs. Tibalt', 'Duel Decks: Venser vs. Koth',
       'Commander: Political Puppets', 'Conflux',
       'Duel Decks: Phyrexia vs. the Coalition',
       'Friday Night Magic 2008', 'Fourth Edition', 'Revised Edition',
       'Apocalypse', 'M12', 'Tenth Edition', 'Lorwyn', 'Shadowmoor',
       'Eventide', 'Shards of Alara', 'M10', 'Zendikar', 'M11',
       'Scars of Mirrodin', 'Mirrodin Besieged', 'New Phyrexia',
       '8th Edition', 'Strixhaven', 'Strixhaven: Mystical Archive',
       'Universes Beyond: Final Fantasy', 'Fifth Edition', 'Morningtide',
       'Land', 'Worldwake', 'Rise of Eldrazi', 'Starter 2000',
       'Avaycn Restored', 'Planar Chos', 'Shdaowmoor', 'Alara Reborn',
       'M10 ', 'Wordlwake', 'Rise of the Eldrazi', 'Judgment'],
      dtype=object)

In [250]:
df_expansion_symbol = pd.DataFrame({'expansion_symbol':collection['expansion_symbol'].unique()})

In [251]:
df_expansion_symbol

       expansion_symbol
0               Ice Age
1             Alliances
2               Visions
3                Portal
4            Stronghold
..                  ...
86         Alara Reborn
87                 M10
88            Wordlwake
89  Rise of the Eldrazi
90             Judgment

[91 rows x 1 columns]

In [252]:
collection[collection['expansion_symbol'] == '8th Edition']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
1775,1776,Coat of Arms,NaN,Artifact,NaN,NaN,NaN,NaN,8th Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [253]:
collection.loc[1775, ['expansion_symbol']] = ['Eighth Edition']

In [254]:
# Some of the cards from Judgment were inserted with the expansion misspelled with an e
collection[collection['expansion_symbol'] == 'Judgement']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
144,145,Commander Eesha,Legend,NaN,Creature,Bird,Soldier,NaN,Judgement,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,146,Selfless Exorcist,NaN,NaN,Creature,Cleric,NaN,NaN,Judgement,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,147,Battle Screech,NaN,NaN,Sorcery,NaN,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,148,Spurmage Advocate,NaN,NaN,Creature,Nomad,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,149,Unquestioned Authority,NaN,NaN,Enchantment,NaN,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,150,Valor,NaN,NaN,Creature,Incarnation,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,151,Wormfang Turtle,NaN,NaN,Creature,Nightmare,Beast,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,152,Wormfang Crab,NaN,NaN,Creature,Nightmare,Crab,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,153,Tunneler Wurm,NaN,NaN,Creature,Wurm,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,154,Exoskeletal Armor,NaN,NaN,Enchantment,NaN,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,155,Brawn,NaN,NaN,Creature,Incarnation,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,156,Anurid Swarmsnapper,NaN,NaN,Creature,Beast,NaN,NaN,Judgement,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,157,Benevolent Bodyguard,NaN,NaN,Creature,Cleric,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,158,Funeral Pyre,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,159,Guided Strike,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,160,Lead Astray,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,161,Prismatic Strands,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,162,Shieldmage Advocate,NaN,NaN,Creature,Cleric,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,163,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,164,Defy Gravity,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,165,Arcane Teachings,NaN,NaN,Enchantment,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,166,Barbarian Bully,NaN,NaN,Creature,Barbarian,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,167,Lava Dart,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,168,Spellgorger Barbarian,NaN,NaN,Creature,Nightmare,Barbarian,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,169,Anurid Barkripper,NaN,NaN,Creature,Beast,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,170,Battlefield Scrounger,NaN,NaN,Creature,Centaur,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,171,Giant Warthog,NaN,NaN,Creature,Beast,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,172,Harvester Druid,NaN,NaN,Creature,Druid,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,173,Krosan Wayfarer,NaN,NaN,Creature,Druid,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,174,Nantuko Tracer,NaN,NaN,Creature,Insect,Druid,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,175,Phantom Tiger,NaN,NaN,Creature,Cat,Spirit,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,176,Sudden Strength,NaN,NaN,Instant,NaN,NaN,NaN,Judgement,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [255]:
collection['expansion_symbol'] = collection['expansion_symbol'].str.replace('Judgement', 'Judgment', regex=False)

In [256]:
# Fifth Dawn was spelled with an additional space
collection[collection['expansion_symbol'] == 'Fifth Dawn ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
200,201,Spark Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Fifth Dawn,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [257]:
collection.loc[200, ['expansion_symbol']] = ['Fifth Dawn']

In [258]:
# Time Spiral was spelled here with an additional space
collection[collection['expansion_symbol'] == 'Time Spiral ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
395,396,Terramorphic Expanse,NaN,NaN,Land,NaN,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [259]:
collection.loc[395, ['expansion_symbol']] = ['Time Spiral']

In [260]:
# Here, the r and i are interchanged
collection[collection['expansion_symbol'] == 'Time Sprial']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
422,423,Snapback,NaN,NaN,Instant,NaN,NaN,NaN,Time Sprial,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [261]:
collection.loc[422, ['expansion_symbol']] = ['Time Spiral']

In [262]:
collection[collection['expansion_symbol'] == 'Planar Chaos ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
571,572,Vitaspore Thallid,NaN,NaN,Creature,Fungus,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,588,Kor Dirge,NaN,NaN,Instant,NaN,NaN,NaN,Planar Chaos,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [263]:
collection.loc[[571, 587], 'expansion_symbol'] = 'Planar Chaos'

In [264]:
collection[collection['expansion_symbol'] == 'Gatecraash']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
1291,1292,Disciple of the Old Ways,NaN,NaN,Creature,Human,Warrior,NaN,Gatecraash,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [265]:
collection.loc[1291, ['expansion_symbol']] = ['Gatecrash']

In [266]:
collection[collection['expansion_symbol'] == 'Land']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
2010,2010,Wanderwine Hub,NaN,NaN,Land,NaN,NaN,NaN,Land,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [267]:
collection.loc[2010, ['subtype_b', 'expansion_symbol']] = ['Land', 'Lorwyn']

In [268]:
collection[collection['expansion_symbol'] == 'Avaycn Restored']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
2047,2047,Riders of Gavony,NaN,NaN,Creature,Human,Knight,NaN,Avaycn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [269]:
collection.loc[2047, ['expansion_symbol']] = ['Avacyn Restored']

In [270]:
collection[collection['expansion_symbol'] == 'Planar Chos']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
2126,2126,Mirri the Cursed,Legendary,NaN,Creature,Vampire,Cat,NaN,Planar Chos,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [271]:
collection.loc[2126, ['expansion_symbol']] = ['Planar Chaos']

In [272]:
collection[collection['expansion_symbol'] == 'Shdaowmoor']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
2575,2574,Firespout,NaN,NaN,Sorcery,NaN,NaN,NaN,Shdaowmoor,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [273]:
collection.loc[2575, ['expansion_symbol']] = ['Shadowmoor']

In [274]:
collection[collection['expansion_symbol'] == 'M10 ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
2974,2973,Panic Attack,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [275]:
collection.loc[2974, ['expansion_symbol']] = ['M10']

In [276]:
collection[collection['expansion_symbol'] == 'Wordlwake']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
3214,3213,Loam Lion,NaN,NaN,Creature,Cat,NaN,NaN,Wordlwake,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [277]:
collection.loc[3214, ['expansion_symbol']] = ['Worldwake']

In [278]:
collection[collection['expansion_symbol'] == 'Rise of Eldrazi']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
2026,2026,Student of Warfare,NaN,NaN,Creature,Human,Knight,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2036,2036,Nomads' Assembly,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2041,2041,Near-Death Experience,NaN,NaN,Enchantment,NaN,NaN,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2049,2049,Kor Spiritdancer,NaN,NaN,Creature,Kor,Wizard,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2082,2082,Renegade Doppelganger,NaN,NaN,Creature,Shapeshifter,NaN,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4271,4270,Stomper Cub,NaN,NaN,Creature,Beast,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4272,4271,Wildheart Invoker,NaN,NaN,Creature,Elf,Shaman,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4273,4272,Hand of Emrakul,NaN,NaN,Creature,Eldrazi,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4274,4273,Reinforced Bulwark,NaN,Artifact,Creature,Wall,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4275,4274,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [279]:
collection['expansion_symbol'] = collection['expansion_symbol'].str.replace('Rise of Eldrazi', 'Rise of the Eldrazi', regex=False)

In [280]:
collection[collection['expansion_symbol'] == 'Portal 2']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,saga_subtype_d,saga_punch,saga_toughness,transform_subtype_d,transform_subtype_e,flip_supertype,modal_subtype_d,modal_flavor_text,flip_text_box,split_subtype_b
15,16,Talas Merchant,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Air Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,Touch of Brilliance,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,Talas Researcher,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,False Summoning,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,Talas Air Ship,NaN,NaN,Creature,Ship,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,Talas Scout,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,Exhaustion,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,Talas Explorer,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,Time Ebb,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,Talas Warrior,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,Monstrous Growth,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,Alluring Scent,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,Wild Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,River Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,Norwood Riders,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,Norwood Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,Norwood Archers,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,Golden Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,Bear Cub,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,Ironhoof Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,Angel of Fury,NaN,NaN,Creature,Angel,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [281]:
collection['expansion_symbol'] = collection['expansion_symbol'].str.replace('Portal 2', 'Portal Second Age', regex=False)

In [282]:
df_expansion_symbol = pd.DataFrame({'expansion_symbol':collection['expansion_symbol'].unique()})

In [283]:
df_expansion_symbol['release_date'] = ['6/1/1995', '6/10/1996', '2/3/1997', '6/1/1997', '3/2/1998', '6/15/1998', '6/1/1998', '10/12/1998', '2/15/1999', '7/1/1999', '10/4/1999', '4/28/1999', '2/14/2000', '6/5/2000', '10/2/2000', '4/11/2001', '2/5/2001', '10/1/2001', '2/4/2002', '5/27/2002', '2/3/2003', '5/26/2003', '10/2/2003', '2/6/2004', '6/4/2004', '10/1/2004', '2/4/2005', '7/29/2005', '10/7/2005', '2/3/2006', '7/28/2003', '5/5/2006', '7/21/2006', '10/6/2006', '2/2/2007', '5/4/2007', '9/30/2011', '2/3/2012', '5/4/2012', '7/13/2012', '10/5/2012', '5/3/2013', '2/1/2013', '6/7/2013', '6/6/2014', '10/2/2015', '11/16/2007', '3/15/2013', '3/30/2012', '6/17/2011', '2/6/2009', '3/19/2010', '1/4/2008', '4/1/1995', '4/11/1994', '6/4/2001', '7/15/2011', '7/13/2007', '10/12/2007', '5/2/2008', '7/25/2008', '10/3/2008', '7/7/2009', '10/2/2009', '7/16/2010', '10/1/2010', '2/4/2011', '5/13/2011', '4/23/2021', '4/23/2021', '6/13/2025', '3/24/1997', '2/1/2008', '2/5/2010', '4/23/2010', '7/1/2000', '4/30/2009']

In [284]:
df_expansion_symbol['expansion_symbol_id'] = range(1, len(df_expansion_symbol) + 1)

In [285]:
df_expansion_symbol = df_expansion_symbol[['expansion_symbol_id', 'expansion_symbol', 'release_date']]

In [286]:
df_expansion_symbol

    expansion_symbol_id     expansion_symbol release_date
0                     1              Ice Age     6/1/1995
1                     2            Alliances    6/10/1996
2                     3              Visions     2/3/1997
3                     4               Portal     6/1/1997
4                     5           Stronghold     3/2/1998
..                  ...                  ...          ...
72                   73          Morningtide     2/1/2008
73                   74            Worldwake     2/5/2010
74                   75  Rise of the Eldrazi    4/23/2010
75                   76         Starter 2000     7/1/2000
76                   77         Alara Reborn    4/30/2009

[77 rows x 3 columns]

In [287]:
# Remember, the release dates were entered as strings, they need to be casted as dates
df_expansion_symbol['release_date'] = pd.to_datetime(df_expansion_symbol['release_date'])

In [288]:
df_expansion_symbol.sort_values(by='release_date')

    expansion_symbol_id                 expansion_symbol release_date
54                   55                  Revised Edition   1994-04-11
53                   54                   Fourth Edition   1995-04-01
0                     1                          Ice Age   1995-06-01
1                     2                        Alliances   1996-06-10
2                     3                          Visions   1997-02-03
..                  ...                              ...          ...
44                   45                       Conspiracy   2014-06-06
45                   46              Battle for Zendikar   2015-10-02
68                   69                       Strixhaven   2021-04-23
69                   70     Strixhaven: Mystical Archive   2021-04-23
70                   71  Universes Beyond: Final Fantasy   2025-06-13

[77 rows x 3 columns]