In [2]:
import pandas as pd
import glob
# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17/*.csv")
# 2. Use list comprehension to read all files and concat them
ice_age_strixhaven = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [3]:
ice_age_strixhaven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3763 entries, 0 to 3762
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           3762 non-null   float64
 1   card_name              3761 non-null   object
 2   supertype              35 non-null     object
 3   subtype_a              332 non-null    object
 4   subtype_b              3619 non-null   object
 5   subtype_c              2326 non-null   object
 6   subtype_d              1093 non-null   object
 7   subtype_e              58 non-null     object
 8   expansion_symbol       3756 non-null   object
 9   rarity                 3751 non-null   object
 10  artist_information_a   3756 non-null   object
 11  artist_information_b   91 non-null     object
 12  collectors_number      3755 non-null   object
 13  expansion_total_cards  3715 non-null   float64
 14  mana_cost              3625 non-null   object
 15  text_box               3647 non-null   object
 16  flavor_text            2803 non-null   object
 17  punch                  2006 non-null   object
 18  toughness              2003 non-null   object
 19  starting_loyalty       9 non-null      object
 20  quantity               3748 non-null   object
dtypes: float64(2), object(19)
memory usage: 617.5+ KB

In [4]:
harry_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet1.csv")

In [5]:
harry_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              211 non-null    int64
 1   card_name                 211 non-null    object
 2   supertype                 28 non-null     object
 3   subtype_a                 211 non-null    object
 4   subtype_b                 119 non-null    object
 5   subtype_c                 65 non-null     object
 6   subtype_d                 2 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          211 non-null    object
 10  rarity                    211 non-null    object
 11  artist_information_a      210 non-null    object
 12  artist_information_b      8 non-null      object
 13  collectors_number         210 non-null    object
 14  expansion_total           202 non-null    float64
 15  mana_cost                 209 non-null    object
 16  text_box                  207 non-null    object
 17  flavor_text               125 non-null    object
 18  punch                     103 non-null    object
 19  toughness                 103 non-null    object
 20  quantity                  210 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           1 non-null      object
 29  split_mana_cost           1 non-null      object
 30  split_subtype_a           1 non-null      object
 31  split_text_box            1 non-null      object
 32  loyalty_cost_a            3 non-null      float64
 33  loyalty_ability_a         3 non-null      object
 34  loyalty_cost_b            4 non-null      object
 35  loyalty_ability_b         4 non-null      object
 36  loyalty_cost_c            4 non-null      float64
 37  loyalty_ability_c         4 non-null      object
 38  starting_loyalty          4 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       1 non-null      object
 48  transform_supertype       0 non-null      float64
 49  transform_subtype_a       1 non-null      object
 50  transform_subtype_b       1 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        1 non-null      object
 53  transform_flavor_text     0 non-null      float64
 54  transform_punch           1 non-null      float64
 55  transform_toughness       1 non-null      float64
 56  modal_card_name           4 non-null      object
 57  modal_mana_cost           4 non-null      object
 58  modal_supertype           2 non-null      object
 59  modal_subtype_c           4 non-null      object
 60  modal_subtype_b           2 non-null      object
 61  modal_subtype_a           2 non-null      object
 62  modal_text_box            4 non-null      object
 63  modal_punch               2 non-null      float64
 64  modal_toughness           2 non-null      float64
 65  saga_card_name            1 non-null      object
 66  lore_counter_a            1 non-null      object
 67  lore_text_box_a           1 non-null      object
 68  lore_counter_b            1 non-null      object
 69  lore_counter_text_box     1 non-null      object
 70  saga_supertype            1 non-null      object
 71  saga_subtype_a            1 non-null      object
 72  saga_subtype_b            1 non-null      object
 73  saga_subtype_c            1 non-null      object
 74  saga_subtype_d            1 non-null      object
 75  saga_punch                1 non-null      float64
 76  saga_toughness            1 non-null      float64
dtypes: float64(31), int64(1), object(45)
memory usage: 127.1+ KB

In [6]:
harry_binder = harry_binder.drop(columns='subtype_d.1')

In [7]:
harry_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [8]:
spencer_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet2.csv")

In [9]:
spencer_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              176 non-null    int64
 1   card_name                 176 non-null    object
 2   supertype                 16 non-null     object
 3   subtype_a                 176 non-null    object
 4   subtype_b                 111 non-null    object
 5   subtype_c                 56 non-null     object
 6   subtype_d                 3 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          176 non-null    object
 10  rarity                    176 non-null    object
 11  artist_information_a      169 non-null    object
 12  artist_information_b      5 non-null      object
 13  collectors_number         176 non-null    object
 14  expansion_total           176 non-null    int64
 15  mana_cost                 170 non-null    object
 16  text_box                  168 non-null    object
 17  flavor_text               96 non-null     object
 18  punch                     93 non-null     object
 19  toughness                 93 non-null     object
 20  quantity                  171 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           0 non-null      float64
 29  split_mana_cost           0 non-null      float64
 30  split_subtype_a           0 non-null      float64
 31  split_text_box            0 non-null      float64
 32  loyalty_cost_a            8 non-null      float64
 33  loyalty_ability_a         8 non-null      object
 34  loyalty_cost_b            8 non-null      object
 35  loyalty_ability_b         8 non-null      object
 36  loyalty_cost_c            8 non-null      float64
 37  loyalty_ability_c         8 non-null      object
 38  starting_loyalty          8 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       4 non-null      object
 48  transform_supertype       3 non-null      object
 49  transform_subtype_a       4 non-null      object
 50  transform_subtype_b       3 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        4 non-null      object
 53  transform_flavor_text     2 non-null      object
 54  transform_punch           4 non-null      float64
 55  transform_toughness       4 non-null      float64
 56  modal_card_name           0 non-null      float64
 57  modal_mana_cost           0 non-null      float64
 58  modal_supertype           0 non-null      float64
 59  modal_subtype_c           0 non-null      float64
 60  modal_subtype_b           0 non-null      float64
 61  modal_subtype_a           0 non-null      float64
 62  modal_text_box            0 non-null      float64
 63  modal_punch               0 non-null      float64
 64  modal_toughness           0 non-null      float64
 65  saga_card_name            0 non-null      float64
 66  lore_counter_a            0 non-null      float64
 67  lore_text_box_a           0 non-null      float64
 68  lore_counter_b            0 non-null      float64
 69  lore_counter_text_box     0 non-null      float64
 70  saga_supertype            0 non-null      float64
 71  saga_subtype_a            0 non-null      float64
 72  saga_subtype_b            0 non-null      float64
 73  saga_subtype_c            0 non-null      float64
 74  saga_subtype_d            0 non-null      float64
 75  saga_punch                0 non-null      float64
 76  saga_toughness            0 non-null      float64
dtypes: float64(49), int64(2), object(26)
memory usage: 106.0+ KB

In [10]:
spencer_binder.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_d.1', 'subtype_e',
       'expansion_symbol', 'rarity', 'artist_information_a',
       'artist_information_b', 'collectors_number', 'expansion_total',
       'mana_cost', 'text_box', 'flavor_text', 'punch', 'toughness',
       'quantity', 'flip_card_name', 'flip_subtype_a', 'flip_subtype_b',
       'flip_subtype_c', 'flip_subtype_d', 'flip_punch', 'flip_toughness',
       'split_card_name', 'split_mana_cost', 'split_subtype_a',
       'split_text_box', 'loyalty_cost_a', 'loyalty_ability_a',
       'loyalty_cost_b', 'loyalty_ability_b', 'loyalty_cost_c',
       'loyalty_ability_c', 'starting_loyalty', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness'],
      dtype='object')

In [11]:
spencer_binder = spencer_binder.drop(columns='subtype_d.1')

In [12]:
spencer_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [13]:
rise_of_eldrazi = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet3.csv")

In [14]:
rise_of_eldrazi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           130 non-null    int64
 1   card_name              130 non-null    object
 2   supertype              1 non-null      object
 3   subtype_a              4 non-null      object
 4   subtype_b              129 non-null    object
 5   subtype_c              91 non-null     object
 6   subtype_d              46 non-null     object
 7   subtype_e              0 non-null      float64
 8   expansion_symbol       130 non-null    object
 9   rarity                 130 non-null    object
 10  artist_information_a   130 non-null    object
 11  artist_information_b   6 non-null      object
 12  collectors_number      130 non-null    int64
 13  expansion_total_cards  130 non-null    int64
 14  mana_cost              129 non-null    object
 15  text_box               127 non-null    object
 16  flavor_text            99 non-null     object
 17  punch                  74 non-null     float64
 18  toughness              74 non-null     float64
 19  starting_loyalty       0 non-null      float64
 20  quantity               130 non-null    int64
dtypes: float64(4), int64(4), object(13)
memory usage: 21.5+ KB

In [15]:
rise_of_eldrazi.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity'],
      dtype='object')

In [16]:
import numpy as np
# Add columns to the eldrazi sheet, fill with nan
rise_of_eldrazi[['flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']] = np.nan

In [17]:
# Reorder the columns so starting loyalty is grouped with the planeswalker attributes
rise_of_eldrazi = rise_of_eldrazi[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [18]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
ice_age_strixhaven.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity'],
      dtype='object')

In [20]:
ice_age_strixhaven[['flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']] = np.nan

In [21]:
ice_age_strixhaven = ice_age_strixhaven[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [22]:
ice_age_strixhaven

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3758,2294.0,Stampeding Rhino,NaN,NaN,Creature,Rhino,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3759,2295.0,Titanic Growth,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3760,2296.0,Trollhide,NaN,NaN,Enchantment,Aura,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3761,2297.0,Vastwood Gorger,NaN,NaN,Creature,Wurm,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3762,2298.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
collection = pd.concat([ice_age_strixhaven, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

In [24]:
collection[collection.loc[:, 'card_name':'quantity'].isna().all(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
2009,3593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2375,912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
collection = collection.drop([2009, 2375])

In [26]:
collection[collection['artist_information_a'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
378,379.0,Suq'Ata Lancer,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Timeshifted Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,380.0,Tectonic Fiend,NaN,NaN,Creature,Elemental,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2109,3690.0,Cemetery Reaper,NaN,NaN,Creature,Zombie,NaN,NaN,M12,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3149,1685.0,Territorial Baloth,NaN,NaN,Creature,Beast,NaN,NaN,Zendikar,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3879,4049.0,Curse of Stalked Prey,NaN,Enchantment,Aura,Curse,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,4050.0,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3881,4051.0,Stormkirk Noble,NaN,Creature,Vampire,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3882,4052.0,Hellrider,NaN,Creature,Devil,NaN,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3883,4053.0,Markov Blademaster,NaN,Creature,Vampire,Warrior,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3884,4054.0,"Gisela, Blade of Goldnight",Legendary,Creature,Angel,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3885,4055.0,Hound of Griselbrand,NaN,Creature,Elemental,Hound,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
collection.at[378, 'artist_information_a'] = 'Jeff Miracola'
collection.at[379, 'artist_information_a'] = 'Mark Tedin'
collection.at[2109, 'artist_information_a'] = 'Dave Allsop'
collection.at[3149, 'artist_information_a'] = 'Jesper Ejsing'
collection.at[3879, 'artist_information_a'] = 'Christopher Moeller'
collection.at[3880, 'artist_information_a'] = 'David Rapoza'
collection.at[3881, 'artist_information_a'] = 'James Ryman'
collection.at[3882, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3883, 'artist_information_a'] = 'Jana Schirmer'
collection.at[3883, 'artist_information_b'] = 'Johannes Voss'
collection.at[3884, 'artist_information_a'] = 'Jason Chan'
collection.at[3885, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3948, 'artist_information_a'] = 'Christopher Moeller'

In [28]:
collection[collection['expansion_symbol'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1598,3219.0,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,3220.0,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,3221.0,Winter Orb,NaN,Artifact,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,3577.0,Brushland,NaN,NaN,Land,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
collection.loc[1598, ['subtype_b', 'subtype_c', 'subtype_d', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', np.nan, np.nan, 'Fourth Edition', 'Uncommon', 118, 378, '{1}{B}', 'Take target creature from any graveyard and put it directly into play under your control with -1/-0. Treat this creature as though it were just summoned. If Animate Dead is removed, bury the creature in its owner\'s graveyard.', 1]
collection.loc[1599, ['subtype_b', 'subtype_c', 'subtype_d', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', np.nan, np.nan, 'Revised Edition', 'Uncommon', 93, 306, '{1}{B}', 'Enchant creature card in a graveyard\nWhen this Aura enters, if it\'s on the battlefield, it loses "enchant creature card in a graveyard" and gains "enchant creature put onto the battlefield with this Aura." Return enchanted creature card to the battlefield under your control and attach this Aura to it. When this Aura leaves the battlefield, that creature\'s controller sacrifices it.', 1]
collection.loc[1600, ['subtype_b', 'expansion_symbol', 'rarity', 'artist_information_a','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Artifact', 'Revised Edition', 'Rare', 'Mark Tedin', 280, 306, '{2}', 'A player may not untap more than one land during the untap phase of each of his or her turns.', 1]
collection.loc[1757, ['subtype_b', 'subtype_c', 'expansion_symbol', 'rarity', 'artist_information_a', 'collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'punch', 'toughness', 'quantity']] = ['Creature', 'Ooze', 'M12', 'Uncommon', 'Karl Kopinski', 161, 249, '{3}{G}{G}', 'Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) When Acidic Slime enters the battlefield, destroy target artifact, enchantment, or land.', 2, 2, 1]
collection.loc[1993, ['card_name', 'subtype_b', 'expansion_symbol', 'rarity', 'artist_information', 'collectors_number', 'expansion_total_cards', 'text_box', 'quantity']] = ['Brushland', 'Land', 'Fifth Edition', 'Rare', 'Tom Wänerstrand', 414, 449, '{T}: Add one colorless mana to your mana pool.\n{T}: Add {G} or {W} to your mana pool.\nBrushland deals 1 damage to you.', 1]

In [30]:
collection[collection['expansion_total_cards'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
6,7.0,Resistance Fighter,NaN,NaN,Creature,Soldier,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8.0,Fireblast,NaN,NaN,Instant,NaN,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9.0,Lichenthrope,NaN,NaN,Creature,Lichenthrope,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10.0,Quirion Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11.0,Stampeding Wildebeests,NaN,NaN,Creature,Wildebeests,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12.0,Lava Axe,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13.0,Volcanic Hammer,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14.0,Contemplation,NaN,NaN,Enchantment,NaN,NaN,NaN,Stronghold,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15.0,Soul Warden,NaN,NaN,Creature,Ceric,NaN,NaN,Exodus,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16.0,Talas Merchant,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17.0,Air Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18.0,Touch of Brilliance,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19.0,Talas Researcher,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20.0,False Summoning,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21.0,Talas Air Ship,NaN,NaN,Creature,Ship,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22.0,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23.0,Talas Scout,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24.0,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25.0,Exhaustion,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26.0,Talas Explorer,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27.0,Time Ebb,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28.0,Talas Warrior,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29.0,Monstrous Growth,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30.0,Alluring Scent,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31.0,Wild Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32.0,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33.0,River Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34.0,Norwood Riders,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35.0,Norwood Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36.0,Norwood Archers,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37.0,Golden Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38.0,Bear Cub,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39.0,Ironhoof Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40.0,Angel of Fury,NaN,NaN,Creature,Angel,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41.0,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,3574.0,"Ishgard, the Holy See",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991,3575.0,"Lindblum, Industrial Regency",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028,3612.0,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,NaN,Starter 2000,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2097,3678.0,"Jill, Shiva's Dominant",Legendary,NaN,Creature,Human,Noble,Warrior,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,3721.0,The Darkness Crystal,Legendary,Artifact,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,NaN,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3722.0,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3976,3759.0,"Raubahn, Bull of Ala Mhigo",Legendary,Creature,Human,Warrior,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4054,3837.0,Summoner's Grimoire,NaN,Artifact,Equipment,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4055,3838.0,A Realm Reborn,NaN,Enchantment,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4100,3883.0,The Regalia,Legendary,Artifact,Vehicle,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4101,3884.0,"Ultima, Origin of Oblivion",Legendary,Creature,God,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4145,3928.0,"Sin, Spira's Punishment",Legendary,Creature,Leviathan,Avatar,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4146,3929.0,"Joshua, Phoenix's Dominant",Legendary,Creature,Human,Noble,Wizard,NaN,Universes Beyond: Final Fantasy,Rare,...,III,Flames of Rebirth — Return any number of targe...,Legendary,Enchantment,Creature,Saga,Phoenix,4.0,4.0,NaN

In [31]:
collection.loc[collection['expansion_symbol'] == 'Visions', 'expansion_total_cards'] = 167
collection.loc[collection['expansion_symbol'] == 'Portal', 'expansion_total_cards'] = 222
collection.loc[collection['expansion_symbol'] == 'Stronghold', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Exodus', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Portal 2', 'expansion_total_cards'] = 165
collection.loc[collection['expansion_symbol'] == 'Universes Beyond: Final Fantasy', 'expansion_total_cards'] = 309
collection.loc[collection['expansion_symbol'] == 'Starter 2000', 'expansion_total_cards'] = 20
collection.loc[collection['expansion_symbol'] == 'Strixhaven', 'expansion_total_cards'] = 393
collection.loc[collection['expansion_symbol'] == 'Morningtide', 'expansion_total_cards'] = 150

In [32]:
# Some of the cards are double-faced and the collectors number is followed with an a or b depending on the face
collection[collection['collectors_number'].str.contains('[a-zA-Z]', na=False)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
5,6.0,Phantasmal Fiend,NaN,NaN,Creature,Illusion,NaN,NaN,Alliances,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,2299.0,Cloistered Youth,NaN,NaN,Creature,Human,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,2307.0,Civilized Scholar,NaN,NaN,Creature,Human,Advisor,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2321.0,Screeching Bat,NaN,NaN,Creature,Bat,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,2326.0,Hanweir Watchkeep,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,2333.0,Gatstaf Shepherd,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
717,2338.0,Ulvenwald Mystics,NaN,NaN,Creature,Human,Shaman,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
742,2363.0,Thraben Sentry,NaN,NaN,Creature,Human,Soldier,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,2418.0,Tormented Pariah,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,2421.0,Village Ironsmith,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,2429.0,Grizzled Outcasts,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,2439.0,Villagers of Estwald,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
826,2447.0,Chalice of Life,NaN,Artifact,NaN,NaN,NaN,NaN,Dark Ascension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,2458.0,Loyal Cathar,NaN,NaN,Creature,Human,Soldier,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936,2557.0,Afflicted Deserter,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,2563.0,Lambholt Elder,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
963,2584.0,Chosen of Markov,NaN,NaN,Creature,Human,NaN,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
975,2596.0,Hinterland Hermit,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984,2605.0,Scorned Villager,NaN,NaN,Creature,Human,Werewolf,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,3373.0,Delver of Secrets,NaN,NaN,Creature,Human,Wizard,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3822,3992.0,Ludevic's Test Subject,NaN,Creature,Lizard,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3960,3743.0,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
collection.loc[5, ['collectors_number']] = 57
collection.loc[678, ['collectors_number']] = 8
collection.loc[686, ['collectors_number']] = 47
collection.loc[700, ['collectors_number']] = 114
collection.loc[705, ['collectors_number']] = 145
collection.loc[712, ['collectors_number']] = 182
collection.loc[717, ['collectors_number']] = 208
collection.loc[742, ['collectors_number']] = 38
collection.loc[797, ['collectors_number']] = 165
collection.loc[800, ['collectors_number']] = 168
collection.loc[808, ['collectors_number']] = 185
collection.loc[818, ['collectors_number']] = 209
collection.loc[826, ['collectors_number']] = 146
collection.loc[837, ['collectors_number']] = 13
collection.loc[936, ['collectors_number']] = 81
collection.loc[942, ['collectors_number']] = 122
collection.loc[963, ['collectors_number']] = 55
collection.loc[975, ['collectors_number']] = 94
collection.loc[984, ['collectors_number']] = 125
collection.loc[1752, ['collectors_number']] = 51
collection.loc[3822, ['collectors_number']] = 64
collection.loc[3960, ['collectors_number']] = 152

In [34]:
collection[collection['collectors_number'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
2028,3612.0,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,NaN,Starter 2000,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
collection.loc[2028, ['collectors_number']] = 3
collection.loc[3948, ['collectors_number']] = 110

In [36]:
collection

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
collection['collectors_number'] = collection['collectors_number'].astype(int)

In [38]:
collection['expansion_total_cards'] = collection['expansion_total_cards'].astype(int)

In [39]:
collection[collection['expansion_symbol'] == 'Lorwyn'].sort_values(by='collectors_number')

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
3777,3947.0,Ajani Goldmane,NaN,Planeswalker,Ajani,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2163,700.0,Avian Changeling,NaN,NaN,Creature,Shapeshifter,NaN,NaN,Lorwyn,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2287,824.0,Battle Mastery,NaN,NaN,Enchantment,Aura,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2045,3626.0,"Brigid, Hero of Kinsbaile",Legendary,NaN,Creature,Kithkin,Archer,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2288,825.0,Burrenton Forge-Tender,NaN,NaN,Creature,Kithkin,Wizard,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2283,820.0,Vivid Creek,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2284,821.0,Vivid Grove,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2285,822.0,Vivid Marsh,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2286,823.0,Vivid Meadow,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,3599.0,Windbrisk Heights,NaN,NaN,Land,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
collection['permanent_id'] = range(1, len(collection) + 1)

In [41]:
collection.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4278 entries, 0 to 4279
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              4278 non-null   int64
 1   card_name                 4278 non-null   object
 2   supertype                 80 non-null     object
 3   subtype_a                 723 non-null    object
 4   subtype_b                 3980 non-null   object
 5   subtype_c                 2537 non-null   object
 6   subtype_d                 1142 non-null   object
 7   subtype_e                 58 non-null     object
 8   expansion_symbol          4278 non-null   object
 9   rarity                    4273 non-null   object
 10  artist_information_a      4278 non-null   object
 11  artist_information_b      111 non-null    object
 12  collectors_number         4278 non-null   int64
 13  expansion_total_cards     4278 non-null   int64
 14  mana_cost                 4134 non-null   object
 15  text_box                  4150 non-null   object
 16  flavor_text               3123 non-null   object
 17  punch                     2277 non-null   object
 18  toughness                 2274 non-null   object
 19  quantity                  4260 non-null   object
 20  flip_card_name            0 non-null      float64
 21  flip_subtype_a            0 non-null      float64
 22  flip_subtype_b            0 non-null      float64
 23  flip_subtype_c            0 non-null      float64
 24  flip_subtype_d            0 non-null      float64
 25  flip_punch                0 non-null      float64
 26  flip_toughness            0 non-null      float64
 27  split_card_name           1 non-null      object
 28  split_mana_cost           1 non-null      object
 29  split_subtype_a           1 non-null      object
 30  split_text_box            1 non-null      object
 31  loyalty_cost_a            11 non-null     float64
 32  loyalty_ability_a         11 non-null     object
 33  loyalty_cost_b            12 non-null     object
 34  loyalty_ability_b         12 non-null     object
 35  loyalty_cost_c            12 non-null     float64
 36  loyalty_ability_c         12 non-null     object
 37  starting_loyalty          12 non-null     float64
 38  leveler_tier_a            0 non-null      float64
 39  leveler_text_box_a        0 non-null      float64
 40  leveler_tier_a_punch      0 non-null      float64
 41  leveler_tier_a_toughness  0 non-null      float64
 42  leveler_tier_b            0 non-null      float64
 43  leveler_text_box_b        0 non-null      float64
 44  leveler_tier_b_punch      0 non-null      float64
 45  leveler_tier_b_toughness  0 non-null      float64
 46  transform_card_name       5 non-null      object
 47  transform_supertype       3 non-null      object
 48  transform_subtype_a       5 non-null      object
 49  transform_subtype_b       4 non-null      object
 50  transform_subtype_c       0 non-null      float64
 51  transform_text_box        5 non-null      object
 52  transform_flavor_text     2 non-null      object
 53  transform_punch           5 non-null      float64
 54  transform_toughness       5 non-null      float64
 55  modal_card_name           4 non-null      object
 56  modal_mana_cost           4 non-null      object
 57  modal_supertype           2 non-null      object
 58  modal_subtype_c           4 non-null      object
 59  modal_subtype_b           2 non-null      object
 60  modal_subtype_a           2 non-null      object
 61  modal_text_box            4 non-null      object
 62  modal_punch               2 non-null      float64
 63  modal_toughness           2 non-null      float64
 64  saga_card_name            1 non-null      object
 65  lore_counter_a            1 non-null      object
 66  lore_text_box_a           1 non-null      object
 67  lore_counter_b            1 non-null      object
 68  lore_counter_text_box     1 non-null      object
 69  saga_supertype            1 non-null      object
 70  saga_subtype_a            1 non-null      object
 71  saga_subtype_b            1 non-null      object
 72  saga_subtype_c            1 non-null      object
 73  saga_subtype_d            1 non-null      object
 74  saga_punch                1 non-null      float64
 75  saga_toughness            1 non-null      float64
 76  artist_information        1 non-null      object
dtypes: float64(25), int64(3), object(49)
memory usage: 2.7+ MB

In [42]:
collection[collection['rarity'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
1601,1602,Terror,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1602,1603,Storm Crow,NaN,NaN,Creature,Bird,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1603,1604,Counterspell,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1604,1605,Unsummon,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1605,1606,Boomerang,NaN,NaN,Instant,NaN,NaN,NaN,Sixth Edition,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
collection.loc[1601, ['rarity']] = 'Common'
collection.loc[1602, ['rarity']] = 'Common'
collection.loc[1603, ['rarity']] = 'Common'
collection.loc[1604, ['rarity']] = 'Common'
collection.loc[1605, ['rarity']] = 'Common'

In [44]:
collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Legend', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound',
       'Insect', 'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Snow',
       'Sliver', 'Legendary', 'Eye', 'Gargoyle', 'Orgg', 'Avatar',
       'Fungus', 'Kithkin', 'Merfolk', 'Gorgon', 'Leech', 'Kor',
       'Encahntment', 'Serpent', 'Homarid', 'Orc', 'Shapeshifter',
       'Shade', 'Wraith', 'Cyclops', 'Tribal', 'Forest', 'Ouphe', 'Myr',
       'Vampire', 'Bat', 'Curse', 'Werewolf', 'Treefolk', 'Juggernaut',
       'Construct', 'Fox', 'Homunculus', 'Devil', 'Boar', 'Scarecrow',
       'Elk', 'Demon', 'Lizard', 'Kraken', 'Gate', 'Fish', 'Leviathan',
       'Jellyfish', 'Hommunculus', 'Vedalken', 'Crocodile', 'Eldrazi',
       'Drone', 'Ally', 'Planeswalker', 'Venser', 'Sphinx', 'Slith',
       'Worm', 'Koth', 'Thopter', 'Enchatment', 'Common', 'Dragon',
       'Encahantment', "Urza's", 'Jace', 'Praetor', 'Ooze', 'Archon',
       'Rhino', 'Gideon', 'Tamiyo', 'Mana Source', 'Ajani', 'Desert',
       'Lesson', 'Dog', 'Djinn', 'Warlock', 'Specter', 'Fog', 'Dwarf',
       'Squirrel', 'Relic', 'Town', 'Legendary ', 'Noble', 'Rowan',
       'Instinct', 'Island', 'Hag', 'Noggle', 'Gobiln', 'Artificer',
       'Unicorn', 'Antelope', 'Funugs', 'Trap', 'Surrakar', 'Horse',
       'Gremlin', 'Hellion', 'Siren', 'Dragon ', 'Salamander', 'Creatue',
       'Lord', 'Legendary Creature', 'Sorin', 'Phoenix', 'Legedary',
       'Chandra', 'Tibalt', 'Equpiment', 'Manticore', 'Efreet', 'Hydra',
       'Garruk', 'Vehicle', 'God', 'Elder', 'Scorpion', 'Blast'],
      dtype=object)

In [45]:
# Korlash's supertype and subtype were entered as a single string
collection[collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].apply(lambda x: x.str.contains('Legendary Creature', case=False, na=False)).any(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
3834,3833,"Korlash, Heir to Blackblade",Legendary Creature,Zombie,Warrior,NaN,NaN,NaN,Futuresight,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
# The data has to be atomic to be compliant with 1NF
collection.loc[3834, ['supertype', 'subtype_a', 'subtype_b', 'subtype_c']] = ['Legendary', 'Creature', 'Zombie', 'Warrior']

In [55]:
collection[collection['card_name'].str.contains('&', regex=False)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
1175,1176,Alive & Well,NaN,NaN,Sorcery,NaN,NaN,NaN,Dragon's Maze,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176,1177,Armed & Dangerous,NaN,NaN,Sorcery,NaN,NaN,NaN,Dragon's Maze,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1177,1178,Down & Dirty,NaN,NaN,Sorcery,NaN,NaN,NaN,Dragon's Maze,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
collection[collection[['supertype', 'subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].apply(lambda x: x.str.contains('Planeswalker', case=False, na=False)).any(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
1463,1464,"Venser, the Sojourner",NaN,NaN,Planeswalker,Venser,NaN,NaN,Duel Decks: Venser vs. Koth,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1499,1500,Koth of the Hammer,NaN,NaN,Planeswalker,Koth,NaN,NaN,Duel Decks: Venser vs. Koth,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1631,1632,Jace Beleren,NaN,NaN,Planeswalker,Jace,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1745,1746,Gideon Jura,NaN,NaN,Planeswalker,Gideon,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1762,1763,"Tamiyo, the Moon Sage",NaN,NaN,Planeswalker,Tamiyo,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1777,1778,Ajani Vengeant,NaN,NaN,Planeswalker,Ajani,NaN,NaN,Shards of Alara,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2141,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3777,3776,Ajani Goldmane,NaN,Planeswalker,Ajani,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3783,3782,"Venser, the Sojourner",NaN,Planeswalker,Venser,NaN,NaN,NaN,Scars of Mirrodin,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3789,3788,Gideon Jura,NaN,Planeswalker,Gideon,NaN,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3812,3811,"Jace, Memory Adept",NaN,Planeswalker,Jace,NaN,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3831,3830,"Tamiyo, the Moon Sage",NaN,Planeswalker,Tamiyo,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3842,3841,Sorin Markov,NaN,Planeswalker,Sorin,NaN,NaN,NaN,M12,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3862,3861,Chandra Nalaar,NaN,Planeswalker,Chandra,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3889,3888,"Tibalt, the Fiend Blooded",NaN,Planeswalker,Tibalt,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3938,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3940,3939,Chandra Nalaar,NaN,Planeswalker,Chandra,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3941,3940,"Tibalt, the Fiend-Blooded",NaN,Planeswalker,Tibalt,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,4003,Garruk Wildspeaker,NaN,Planeswalker,Garruk,NaN,NaN,NaN,Lorwyn,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
collection[collection['card_name'].isin(['Akki Lavamancer', 'Budoka Gardener', 'Bushi Tenderfoot', 'Initiate of Blood', 'Jushi Apprentice', 'Kitsune Mystic', 'Nezumi Graverobber', 'Nezumi Shortfang', 'Orochi Eggwatcher', 'Student of Elements', 'Tide of War',
                                         'Research', 'Rise', 'Supply', 'Trial', 'Hit', 'Bound', 'Crime', 'Hide', 'Odds', 'Pure',
                                         'Alive', 'Armed', 'Beck', 'Breaking', 'Catch', 'Down', 'Far', 'Flesh', 'Give', 'Profit', 'Protect', 'Ready', 'Toil', 'Turn', 'Wear',
                                         'Beastbreaker of Bala Ged', 'Brimstone Mage', 'Caravan Escort', 'Coralhelm Commander', 'Echo Mage', 'Enclave Cryptologist', 'Guul Draz Assassin', 'Hada Spy Patrol', 'Halimar Wavewatch', 'Hedron-Field Purists', 'Hexdrinker', 'Ikral Outrider', 'Joraga Treespeaker', 'Kabira Vindicator', 'Kargan Dragonlord', 'Kazandu Tuskcaller', 'Knight of Cliffhaven', 'Lighthouse Chronologist', 'Lord of Shatterskull Pass', 'Nirkana Cutthroat', 'Null Champion', 'Skywatcher Adept', 'Student of Warfare', 'Transcendent Master', 'Zulaport Enforcer', 'Under-Construction Skyscraper',
                                         'Wandering Archaic', 'Augmenter Pugilist', 'Blex, Vexing Pest', 'Extus, Oriq Overlord', 'Flamescroll Celebrant', 'Jadzi, Oracle of Arcavios', 'Kianne, Dean of Substance', 'Mila, Crafty Companion', 'Pestilent Cauldron', 'Plargg, Dean of Chaos', 'Rowan, Scholar of Sparks', 'Selfless Glyphweaver', 'Shaile, Dean of Radiance', 'Torrent Sculptor', 'Uvilda, Dean of Perfection', 'Valentin, Dean of the Vein',
                                         'Bane of Hanweir', 'Bloodline Keeper', 'Civilized Scholar', 'Cloistered Youth', 'Daybreak Ranger', 'Delver of Secrets', 'Garruk Relentless', 'Gatsaf Howler', 'Gatstaf Shepherd', 'Grizzled Outcasts', 'Hanweir Watchkeep', 'Homicidal Brute', 'Howlpack Alpha', 'Howlpack of Estwald', 'Instigator Gang', 'Ironfang', 'Krallenhorde Wantons', 'Kruin Outlaw', 'Ludevic\'s Test Subject', 'Mayor of Avabruck', 'Merciless Predator', 'Moonmist', 'Nightfall Predator', 'Rampaging Werewolf', 'Reckless Waif', 'Screeching Bat', 'Stlking Vampire', 'Terror of Kruin Pass', 'Thraben Sentry', 'Tormented Pariah', 'Ulvenwald Mystics', 'Ulvenwald Primordials', 'Village Ironsmith', 'Villagers of Estwald', 'Wildwood Pack'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
312,313,Trial,NaN,NaN,Instant,NaN,NaN,NaN,Dissension,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,679,Cloistered Youth,NaN,NaN,Creature,Human,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,687,Civilized Scholar,NaN,NaN,Creature,Human,Advisor,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,701,Screeching Bat,NaN,NaN,Creature,Bat,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,706,Hanweir Watchkeep,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,713,Gatstaf Shepherd,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
717,718,Ulvenwald Mystics,NaN,NaN,Creature,Human,Shaman,Werewolf,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
742,743,Thraben Sentry,NaN,NaN,Creature,Human,Soldier,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,798,Tormented Pariah,NaN,NaN,Creature,Human,Warrior,Werewolf,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,801,Village Ironsmith,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,809,Grizzled Outcasts,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810,811,Moonmist,NaN,NaN,Instant,NaN,NaN,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,819,Villagers of Estwald,NaN,NaN,Creature,Human,Werewolf,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1614,1615,Kitsune Mystic,NaN,NaN,Creature,Fox,Wizard,NaN,Champions of Kamigawa,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,1753,Delver of Secrets,NaN,NaN,Creature,Human,Wizard,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026,2026,Student of Warfare,NaN,NaN,Creature,Human,Knight,NaN,Rise of Eldrazi,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2057,2057,Selfless Glyphweaver,NaN,NaN,Creature,Human,Cleric,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2058,2058,Flamescroll Celebrant,NaN,NaN,Creature,Human,Shaman,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2095,2095,Torrent Sculptor,NaN,NaN,Creature,Merfolk,Wizard,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2141,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3268,3267,Joraga Treespeaker,NaN,NaN,Creature,Elf,Druid,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3822,3821,Ludevic's Test Subject,NaN,Creature,Lizard,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,3879,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3901,3900,Daybreak Ranger,NaN,Creature,Human,Archer,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3938,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3960,3959,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4047,4046,"Kianne, Dean of Substance",Legendary,Creature,Elf,Druid,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4049,4048,"Valentin, Dean of the Vein",Legendary,Creature,Vampire,Warlock,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4053,4052,Pestilent Cauldron,NaN,Artifact,NaN,NaN,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4094,4093,Wandering Archaic,NaN,Creature,Avatar,NaN,NaN,NaN,Strixhaven,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4144,4143,Beck,NaN,Sorcery,NaN,NaN,NaN,NaN,Dragon's Maze,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4155,4154,Hada Spy Patrol,NaN,NaN,Creature,Human,Rogue,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4156,4155,Enclave Cryptologist,NaN,NaN,Creature,Merfolk,Wizard,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4162,4161,Nirkana Cutthroat,NaN,NaN,Creature,Vampire,Warrior,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4166,4165,Brimstone Mage,NaN,NaN,Creature,Human,Shaman,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4170,4169,Beastbreaker of Bala Ged,NaN,NaN,Creature,Human,Warrior,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4183,4182,Caravan Escort,NaN,NaN,Creature,Human,Knight,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4191,4190,Knight of Cliffhaven,NaN,NaN,Creature,Kor,Knight,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4208,4207,Halimar Wavewatch,NaN,NaN,Creature,Merfolk,Soldier,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4218,4217,Skywatcher Adept,NaN,NaN,Creature,Merfolk,Wizard,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4230,4229,Null Champion,NaN,NaN,Creature,Zombie,Warrior,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4235,4234,Zulaport Enforcer,NaN,NaN,Creature,Human,Warrior,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

In [49]:
#pd.reset_option('display.max_rows')
#pd.reset_option('display.max_columns')