In [70]:
import pandas as pd
import glob

# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17/*.csv")

# 2. Use list comprehension to read all files and concat them
df = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3763 entries, 0 to 3762
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           3762 non-null   float64
 1   card_name              3761 non-null   object
 2   supertype              35 non-null     object
 3   subtype_a              332 non-null    object
 4   subtype_b              3619 non-null   object
 5   subtype_c              2326 non-null   object
 6   subtype_d              1093 non-null   object
 7   subtype_e              58 non-null     object
 8   expansion_symbol       3756 non-null   object
 9   rarity                 3751 non-null   object
 10  artist_information_a   3592 non-null   object
 11  artist_information_b   91 non-null     object
 12  collectors_number      3755 non-null   object
 13  expansion_total_cards  3715 non-null   float64
 14  mana_cost              3625 non-null   object
 15  text_box               3647 non-null   object
 16  flavor_text            2803 non-null   object
 17  punch                  2006 non-null   object
 18  toughness              2003 non-null   object
 19  starting_loyalty       9 non-null      object
 20  quantity               3748 non-null   object
 21  artist_information     164 non-null    object
dtypes: float64(2), object(20)
memory usage: 646.9+ KB

In [72]:
harry_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet1.csv")

In [73]:
harry_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              211 non-null    int64
 1   card_name                 211 non-null    object
 2   supertype                 28 non-null     object
 3   subtype_a                 211 non-null    object
 4   subtype_b                 119 non-null    object
 5   subtype_c                 65 non-null     object
 6   subtype_d                 2 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          211 non-null    object
 10  rarity                    211 non-null    object
 11  artist_information_a      210 non-null    object
 12  artist_information_b      8 non-null      object
 13  collectors_number         210 non-null    object
 14  expansion_total           202 non-null    float64
 15  mana_cost                 209 non-null    object
 16  text_box                  207 non-null    object
 17  flavor_text               125 non-null    object
 18  punch                     103 non-null    object
 19  toughness                 103 non-null    object
 20  quantity                  210 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           1 non-null      object
 29  split_mana_cost           1 non-null      object
 30  split_subtype_a           1 non-null      object
 31  split_text_box            1 non-null      object
 32  loyalty_cost_a            3 non-null      float64
 33  loyalty_ability_a         3 non-null      object
 34  loyalty_cost_b            4 non-null      object
 35  loyalty_ability_b         4 non-null      object
 36  loyalty_cost_c            4 non-null      float64
 37  loyalty_ability_c         4 non-null      object
 38  starting_loyalty          4 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       1 non-null      object
 48  transform_supertype       0 non-null      float64
 49  transform_subtype_a       1 non-null      object
 50  transform_subtype_b       1 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        1 non-null      object
 53  transform_flavor_text     0 non-null      float64
 54  transform_punch           1 non-null      float64
 55  transform_toughness       1 non-null      float64
 56  modal_card_name           4 non-null      object
 57  modal_mana_cost           4 non-null      object
 58  modal_supertype           2 non-null      object
 59  modal_subtype_c           4 non-null      object
 60  modal_subtype_b           2 non-null      object
 61  modal_subtype_a           2 non-null      object
 62  modal_text_box            4 non-null      object
 63  modal_punch               2 non-null      float64
 64  modal_toughness           2 non-null      float64
 65  saga_card_name            1 non-null      object
 66  lore_counter_a            1 non-null      object
 67  lore_text_box_a           1 non-null      object
 68  lore_counter_b            1 non-null      object
 69  lore_counter_text_box     1 non-null      object
 70  saga_supertype            1 non-null      object
 71  saga_subtype_a            1 non-null      object
 72  saga_subtype_b            1 non-null      object
 73  saga_subtype_c            1 non-null      object
 74  saga_subtype_d            1 non-null      object
 75  saga_punch                1 non-null      float64
 76  saga_toughness            1 non-null      float64
dtypes: float64(31), int64(1), object(45)
memory usage: 127.1+ KB

In [74]:
harry_binder = harry_binder.drop(columns='subtype_d.1')

In [75]:
spencer_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet2.csv")

In [76]:
spencer_binder

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_d.1,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total,mana_cost,text_box,flavor_text,punch,toughness,quantity,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,starting_loyalty,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,3933,Angel's Grace,NaN,Instant,NaN,NaN,NaN,NaN,NaN,Time Spiral,Rare,Mark Zug,NaN,3,301,{W},Split Second (As long as this spell is on the ...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3934,Chronosavant,NaN,Creature,Giant,NaN,NaN,NaN,NaN,Time Spiral,Rare,Pete Venters,NaN,9,301,{5}{W},{1}{W}: Return Chronosavant from your graveyar...,"""In my dreams, I hear the voices of my future ...",5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3935,Mangara of Corondor,Legendary,Creature,Human,Wizard,NaN,NaN,NaN,Time Spiral,Rare,Zoltan Boros,Gabor Szikszai,28,301,{1}{W}{W},{T}: Remove Mangara of Corondor and target per...,"""I have been brought to this place and I canno...",1,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3936,Opal Guardian,NaN,Enchantment,NaN,NaN,NaN,NaN,NaN,Time Spiral,Rare,Christopher Rush,NaN,30,301,{W}{W}{W},"When an opponent plays a creature spell, if Op...","It was a moment in time, cast in stone—a momen...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3937,Heroes Remembered,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Time Spiral,Rare,Michael Phillippi,NaN,7,165,{6}{W}{W}{W},You gain 20 life.\nSuspend 10—{W} (Rather than...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3938,Restore Balance,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Planar Chaos,Rare,Mark Poole,NaN,38,301,NaN,Restore Balance is white.\nSuspend 6—{W}\nEach...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3939,Weathered Bodyguards,NaN,Creature,Human,Soldier,NaN,NaN,NaN,Time Spiral,Rare,Wayne Reynolds,NaN,46,301,{5}{W},"As long as Weathered Bodyguards is untapped, a...",NaN,2,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,3940,Angel of Salvation,NaN,Creature,Angel,NaN,NaN,NaN,NaN,Futuresight,Rare,D. Alexander Gregory,NaN,1,180,{6}{W}{W},Flash convoke (Each creature you tap while pla...,NaN,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,3941,Magus of the Moat,NaN,Creature,Human,Wizard,NaN,NaN,NaN,Futuresight,Rare,John Avon,NaN,12,180,{2}{W}{W},Creatures without flying can't attack.,"""The spirits of the mythic ones ever circle th...",0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3942,Magus of the Tabernacle,NaN,Creature,Human,Wizard,NaN,NaN,NaN,Planar Chaos,Rare,Randy Gallegos,NaN,8,165,{3}{W},"All creatures have ""At the beginning of your u...",The Tabernacle's disciples channel the emanati...,2,6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3943,"Oriss, Samite Guardian",Legendary,Creature,Human,Cleric,NaN,NaN,NaN,Futuresight,Rare,Michael Komarck,NaN,28,180,{1}{W}{W},{T}: Prevent all damage that would be dealt to...,NaN,1,3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3944,"Crovax, Ascendant Hero",Legendary,Creature,Human,Lord,NaN,NaN,NaN,Planar Chaos,Rare,Pete Venters,NaN,3,165,{4}{W}{W},Other white creatures get +1/+1.\nNonwhite cre...,"Crovax was destined for an angel's curse, but ...",4,4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3945,Pulmonic Sliver,NaN,Creature,Sliver,NaN,NaN,NaN,NaN,Time Spiral,Rare,Jeff Easley,NaN,36,301,{3}{W}{W},"All Slivers have flying and ""If this creature ...","Like a great bellows it hisses, and its kin, b...",3,3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3946,Retether,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Planar Chaos,Rare,Dan Scott,NaN,13,165,{3}{W},Return each Aura card from your graveyard to p...,"The rifts reach into infinite time streams, br...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3947,Ajani Goldmane,NaN,Planeswalker,Ajani,NaN,NaN,NaN,NaN,Lorwyn,Rare,Aleksi Briclot,NaN,1,301,{2}{W}{W},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,You gain 2 life.,-1,Put a +1/+1 counter on each creature you contr...,-6.0,Put a white Avatar creature token into play wi...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,3948,Favor of the Mighty,NaN,Tribal,Enchantment,Giant,NaN,NaN,NaN,Lorwyn,Rare,Larry MacDougall,NaN,14,301,{1}{W},Each creature with the highest converted mana ...,"""What does a mountain fear of a fly? Giants ar...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3949,Mirror Entity,NaN,Creature,Shapeshifter,NaN,NaN,NaN,NaN,Lorwyn,Rare,Zoltan Boros,Gabor Szikszai,31,301,{2}{W},Changeling (This card is every creature type a...,"Unaware of Lorwyn's diversity, it sees only it...",1,1,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,3950,Preeminent Captain,NaN,Creature,Kithkin,Soldier,NaN,NaN,NaN,Morningtide,Rare,Greg Staples,NaN,20,150,{2}{W},First strike\nWhenever Preeminent Captain atta...,"""If you need an example to lead others to the ...",2,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,3951,Order of Whiteclay,NaN,Creature,Kithkin,Cleric,NaN,NaN,NaN,Shadowmoor,Rare,Steven Belledin,NaN,16,301,{1}{W}{W},"{1}{W}{W}, {Q}: Return target creature card wi...","Made from the clay of burial mounds, the face ...",1,4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,3952,Divinity of Pride,NaN,Creature,Spirit,Avatar,NaN,NaN,NaN,Eventide,Rare,Greg Staples,NaN,86,180,{W/B}{W/B}{W/B}{W/B}{W/B},"Flying, lifelink\nDivinity of Pride gets +4/+4...","""She spoke of mystery and portent, of such unf...",4,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,3953,"Venser, the Sojourner",NaN,Planeswalker,Venser,NaN,NaN,NaN,NaN,Scars of Mirrodin,Mythic,Eric Deschamps,NaN,135,249,{3}{W}{U},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Exile target permanent you own. Return it to t...,-1,Creatures are unblockable this turn.,-8.0,"You get an emblem with ""Whenever you cast a sp...",3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,3954,Phyrexian Rebirth,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Mirrodin Besieged,Rare,Scott Chou,NaN,15,155,{4}{W}{W},"Destroy all creatures, then put an X/X colorle...","As long as one drop of the oil exists, the joy...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,3955,White Sun's Zenith,NaN,Instant,NaN,NaN,NaN,NaN,NaN,Mirrodin Besieged,Rare,Mike Bierek,NaN,19,155,{X}{W}{W}{W},Put X 2/2 white Cat creature tokens onto the b...,"After the Battle of Liet Field, the white sun ...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3956,Puresteel Paladin,NaN,Creature,Human,Knight,NaN,NaN,NaN,New Phyrexia,Rare,Jason Chan,NaN,20,175,{W}{W},Whenever an Equipment enters the battlefield u...,NaN,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,3957,Aegis Angel,NaN,Creature,Angel,NaN,NaN,NaN,NaN,M12,Rare,Aleksi Briclot,NaN,1,249,{4}{W}{W},Flying\nWhen Aegis Angel enters the battlefiel...,NaN,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,3958,Day of Judgment,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,M12,Rare,Vincent Proce,NaN,12,249,{2}{W}{W},Destroy all creatures.,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,3959,Gideon Jura,NaN,Planeswalker,Gideon,NaN,NaN,NaN,NaN,M12,Mythic,Aleksi Briclot,NaN,16,249,{3}{W}{W},NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,"During target opponent's next turn, creatures ...",-2,Destroy target tapped creature,0.0,"Until end of turn, Gideon Jura becomes a 6/6 H...",6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,3960,Gideon's Avenger,NaN,Creature,Human,Soldier,NaN,NaN,NaN,M12,Rare,Randy Gallegos,NaN,17,249,{1}{W}{W},Whenever a creature an opponent controls becom...,"""The good don't sit and wait fo rthe evil to a...",2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,3961,Grand Abolisher,NaN,Creature,Human,Cleric,NaN,NaN,NaN,M12,Rare,Eric Deschamps,NaN,19,249,{W}{W},"During your turn, your opponents can't cast sp...","""Your superstitious and mumblings are useless ...",2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,3962,Mesa Enchantress,NaN,Creature,Human,Druid,NaN,NaN,NaN,M12,Rare,Randy Gallegos,NaN,25,249,{1}{W}{W},"Whenever you cast an enchantment spell, you ma...","""Scholars seek to understand the way the world...",0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,3963,Nevermore,NaN,Enchantment,NaN,NaN,NaN,NaN,NaN,Innistrad,Rare,Jason A. Engle,NaN,25,264,{1}{W}{W},"As Nevermore enters the battlefield, name a no...","""By the law of Avacyn, the following thoughts,...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,3964,Seance,NaN,Enchantment,NaN,NaN,NaN,NaN,NaN,Dark Ascension,Rare,David Rapoza,NaN,20,158,{2}{W}{W},"At the beginning of each upkeep, you may exile...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,3965,Sudden Disappearance,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Dark Ascension,Rare,Cliff Childs,NaN,23,158,{5}{W},Exile all nonland permanents target player con...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,3966,Increasing Devotion,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Dark Ascension,Rare,Daniel Ljunggren,NaN,11,158,{3}{W}{W},Put five 1/1 white Human creature tokens onto ...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,3967,Angel of Glory's Rise,NaN,Creature,Angel,NaN,NaN,NaN,NaN,Avacyn Restored,Rare,James Ryman,NaN,1,244,{5}{W}{W},Flying\nWhen Angel of Glory's Rise enters the ...,"""Justice isn't done until undeath is undone.""",4,6,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,3968,"Bruna, Light of Alabaster",Legendary,Creature,Angel,NaN,NaN,NaN,NaN,Avacyn Restored,Mythic,Winona Nelson,NaN,208,244,{3}{W}{W}{U},"Flying, vigilance\nWhenever Bruna, Light of Al...",NaN,5,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,3969,Cathar's Crusade,NaN,Enchantment,NaN,NaN,NaN,NaN,NaN,Avacyn Restored,Rare,Karl Kopinski,NaN,10,244,{3}{W}{W},Whenever a creature enters the battlefield und...,Avacyn's holy warriors kept hope alive in heir...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,3970,Divine Deflection,NaN,Instant,NaN,NaN,NaN,NaN,NaN,Avacyn Restored,Rare,Steve Prescott,NaN,18,244,{X}{W},Prevent the next X damage that would be dealt ...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,3971,Entreat the Angels,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Avacyn Restored,Mythic,Todd Lockwood,NaN,20,244,{X}{X}{W}{W}{W},Put X 4/4 white Angel creature tokens with fly...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,3972,Herald of War,NaN,Creature,Angel,NaN,NaN,NaN,NaN,Avacyn Restored,Rare,Eric Deschamps,NaN,24,244,{3}{W}{W},"Flying\nWhenever Herald of War attacks, put a ...",NaN,3,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,3973,Silverblade Paladin,NaN,Creature,Human,Knight,NaN,NaN,NaN,Avacyn Restored,Rare,Jason Chan,NaN,36,244,{1}{W}{W},Soulbond (You may pair this creature with anot...,NaN,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,3974,Deep-Sea Kraken,NaN,Creature,Kraken,NaN,NaN,NaN,NaN,Time Spiral,Rare,Christopher Moeller,NaN,56,301,{7}{U}{U}{U},Deep-Sea Kraken is unblockable.\nSuspend 9—{2}...,"The rift remained open for days, slicing ancie...",6,6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,3975,Nix,NaN,Instant,NaN,NaN,NaN,NaN,NaN,Futuresight,Rare,Brian Despain,NaN,55,180,{U},Counter target spell if no mana was spent to p...,"""There is no shortcut to work done true and we...",NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
spencer_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              176 non-null    int64
 1   card_name                 176 non-null    object
 2   supertype                 16 non-null     object
 3   subtype_a                 176 non-null    object
 4   subtype_b                 111 non-null    object
 5   subtype_c                 56 non-null     object
 6   subtype_d                 3 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          176 non-null    object
 10  rarity                    176 non-null    object
 11  artist_information_a      169 non-null    object
 12  artist_information_b      5 non-null      object
 13  collectors_number         176 non-null    object
 14  expansion_total           176 non-null    int64
 15  mana_cost                 170 non-null    object
 16  text_box                  168 non-null    object
 17  flavor_text               96 non-null     object
 18  punch                     93 non-null     object
 19  toughness                 93 non-null     object
 20  quantity                  171 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           0 non-null      float64
 29  split_mana_cost           0 non-null      float64
 30  split_subtype_a           0 non-null      float64
 31  split_text_box            0 non-null      float64
 32  loyalty_cost_a            8 non-null      float64
 33  loyalty_ability_a         8 non-null      object
 34  loyalty_cost_b            8 non-null      object
 35  loyalty_ability_b         8 non-null      object
 36  loyalty_cost_c            8 non-null      float64
 37  loyalty_ability_c         8 non-null      object
 38  starting_loyalty          8 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       4 non-null      object
 48  transform_supertype       3 non-null      object
 49  transform_subtype_a       4 non-null      object
 50  transform_subtype_b       3 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        4 non-null      object
 53  transform_flavor_text     2 non-null      object
 54  transform_punch           4 non-null      float64
 55  transform_toughness       4 non-null      float64
 56  modal_card_name           0 non-null      float64
 57  modal_mana_cost           0 non-null      float64
 58  modal_supertype           0 non-null      float64
 59  modal_subtype_c           0 non-null      float64
 60  modal_subtype_b           0 non-null      float64
 61  modal_subtype_a           0 non-null      float64
 62  modal_text_box            0 non-null      float64
 63  modal_punch               0 non-null      float64
 64  modal_toughness           0 non-null      float64
 65  saga_card_name            0 non-null      float64
 66  lore_counter_a            0 non-null      float64
 67  lore_text_box_a           0 non-null      float64
 68  lore_counter_b            0 non-null      float64
 69  lore_counter_text_box     0 non-null      float64
 70  saga_supertype            0 non-null      float64
 71  saga_subtype_a            0 non-null      float64
 72  saga_subtype_b            0 non-null      float64
 73  saga_subtype_c            0 non-null      float64
 74  saga_subtype_d            0 non-null      float64
 75  saga_punch                0 non-null      float64
 76  saga_toughness            0 non-null      float64
dtypes: float64(49), int64(2), object(26)
memory usage: 106.0+ KB

In [77]:
spencer_binder = spencer_binder.drop(columns='subtype_d.1')

In [78]:
rise_of_eldrazi = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet3.csv")

In [79]:
rise_of_eldrazi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           130 non-null    int64
 1   card_name              130 non-null    object
 2   supertype              1 non-null      object
 3   subtype_a              4 non-null      object
 4   subtype_b              129 non-null    object
 5   subtype_c              91 non-null     object
 6   subtype_d              46 non-null     object
 7   subtype_e              0 non-null      float64
 8   expansion_symbol       130 non-null    object
 9   rarity                 130 non-null    object
 10  artist_information_a   130 non-null    object
 11  artist_information_b   6 non-null      object
 12  collectors_number      130 non-null    int64
 13  expansion_total_cards  130 non-null    int64
 14  mana_cost              129 non-null    object
 15  text_box               127 non-null    object
 16  flavor_text            99 non-null     object
 17  punch                  74 non-null     float64
 18  toughness              74 non-null     float64
 19  starting_loyalty       0 non-null      float64
 20  quantity               130 non-null    int64
dtypes: float64(4), int64(4), object(13)
memory usage: 21.5+ KB

In [53]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,Ryan Pancoast,NaN,14,248,{2}{W},Flash\nWhen Affa Guard Hound enters the battle...,"Once a welcoming hub for explorers, Affa becam...",2.0,2.0,NaN,2
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,Mike Bierek,NaN,35,248,{2}{W},Enchant creature\nWhenever enchanted creature ...,"""If destiny's champions have arisen to fight t...",NaN,NaN,NaN,4
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,Howard Lyon,NaN,37,248,{4}{W},Enchant creature\nEnchanted creature gets +3/+...,NaN,NaN,NaN,NaN,1
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,Erica Yang,NaN,45,248,{4}{W},"Defender, flying",The kor's most righteous dead are given the gr...,4.0,5.0,NaN,2
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,Scott Chou,NaN,48,248,{2}{W},You gain 2 life. Then if you have more life th...,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,Steven Belledin,NaN,228,248,NaN,"{T}, Sacrifice Evolving Wilds: Search your lib...","Every wordl is an organism, able to grow new l...",NaN,NaN,NaN,1
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,Matthew D. Wilson,NaN,35,383,{6}{W}{W}{W},"Flying\nAt the beginning of your upkeep, you m...","""You have not died until I consent.""",4.0,6.0,NaN,1
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,Greg Hildebrandt,NaN,189,383,{3}{R}{R},Beacon of Destruction deals 5 damage to target...,The Great Furnace's blessing is a spectacular ...,NaN,NaN,NaN,1
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,Heather Hudson,NaN,50,383,{W},Flying (This creature can't be blocked except ...,"Its eye the glaring sun, its cry the keening w...",1.0,1.0,NaN,3
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,Zoltan Boros,Gabor Szikszai,213,383,{1}{R},Incinerate deals 3 damage to target creature o...,"""Yes, I think 'toast' is an appropriate descri...",NaN,NaN,NaN,4

In [54]:
import numpy as np
rise_of_eldrazi[['flip_card_name', 'flip_subtype_a', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch', 'flip_toughness', 'split_card_name', 'split_mana_cost', 'split_subtype_a', 'split_text_box', 'loyalty_cost_a', 'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b', 'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty', 'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness', 'transform_card_name', 'transform_supertype', 'transform_subtype_a', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness', 'modal_card_name', 'modal_mana_cost', 'modal_supertype', 'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a', 'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name', 'lore_counter_a', 'lore_text_box_a', 'lore_counter_b', 'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a', 'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch', 'saga_toughness']] = np.nan

In [55]:
rise_of_eldrazi.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity', 'flip_card_name',
       'flip_subtype_a', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d',
       'flip_punch', 'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness'],
      dtype='object')

In [56]:
rise_of_eldrazi = rise_of_eldrazi[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name',
       'flip_subtype_a', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d',
       'flip_punch', 'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c',  'starting_loyalty', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [57]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,quantity,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,starting_loyalty,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,Ryan Pancoast,NaN,14,248,{2}{W},Flash\nWhen Affa Guard Hound enters the battle...,"Once a welcoming hub for explorers, Affa becam...",2.0,2.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,Mike Bierek,NaN,35,248,{2}{W},Enchant creature\nWhenever enchanted creature ...,"""If destiny's champions have arisen to fight t...",NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,Howard Lyon,NaN,37,248,{4}{W},Enchant creature\nEnchanted creature gets +3/+...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,Erica Yang,NaN,45,248,{4}{W},"Defender, flying",The kor's most righteous dead are given the gr...,4.0,5.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,Scott Chou,NaN,48,248,{2}{W},You gain 2 life. Then if you have more life th...,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,Steven Belledin,NaN,228,248,NaN,"{T}, Sacrifice Evolving Wilds: Search your lib...","Every wordl is an organism, able to grow new l...",NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,Matthew D. Wilson,NaN,35,383,{6}{W}{W}{W},"Flying\nAt the beginning of your upkeep, you m...","""You have not died until I consent.""",4.0,6.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,Greg Hildebrandt,NaN,189,383,{3}{R}{R},Beacon of Destruction deals 5 damage to target...,The Great Furnace's blessing is a spectacular ...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,Heather Hudson,NaN,50,383,{W},Flying (This creature can't be blocked except ...,"Its eye the glaring sun, its cry the keening w...",1.0,1.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,Zoltan Boros,Gabor Szikszai,213,383,{1}{R},Incinerate deals 3 damage to target creature o...,"""Yes, I think 'toast' is an appropriate descri...",NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
pd.concat([df, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
collection = pd.concat([df, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

In [62]:
# Rows 2009 and 2375 are completely empty
collection[collection.loc[:, 'card_name':'quantity'].isna().all(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
2009,3593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2375,912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
collection = collection.drop([2009, 2375])

In [68]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [69]:
collection[collection['artist_information_a'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
378,379.0,Suq'Ata Lancer,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Timeshifted Rare,NaN,NaN,69,121.0,2R,Haste\nFlanking (Whenever a creature without f...,"""Never stop 'til you see your lance come out t...",2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,380.0,Tectonic Fiend,NaN,NaN,Creature,Elemental,NaN,NaN,Time Spiral,Uncommon,NaN,NaN,181,301.0,4RR,"Echo 4RR (At the beginning of your upkeep, if ...","The barbarian of Pardia are long dead, but its...",7,7,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2109,3690.0,Cemetery Reaper,NaN,NaN,Creature,Zombie,NaN,NaN,M12,Rare,NaN,NaN,86.0,249.0,{1}{B}{B},Other Zombie creatures you control get +1/+1.\...,Every grave cradles a recruit.,2,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3149,1685.0,Territorial Baloth,NaN,NaN,Creature,Beast,NaN,NaN,Zendikar,Common,NaN,NaN,188,249.0,4G,Landfall — Whenever a land enters the battlefi...,Its territory is defined by wherever it is at ...,4,4.0,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3599,2135.0,Buried Ruin,NaN,NaN,Land,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,224,249.0,NaN,"T: Add 1 to your mana pool.\n2, T, Sacrifice B...",History has buried its treasures deep.,NaN,NaN,NaN,3,Franz Vohwinkel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3600,2136.0,Angel's Feather,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,202,249.0,2,"Whenever a player casts a white spell, you may...",The angel represents divine perfection; even t...,NaN,NaN,NaN,3,Alan Pollack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3601,2137.0,Crown of Empires,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,203,249.0,2,"3, T: Tap target creature. Gain control of tha...","""With this crown, assert your authority.""\n—Cr...",NaN,NaN,NaN,3,John Avon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3602,2138.0,Crumbling Colossus,NaN,Artifact,Creature,Golem,NaN,NaN,M12,Uncommon,NaN,NaN,204,249.0,5,Trample (If this creature would assign enough ...,NaN,7.0,4.0,NaN,4,Michael C. Hayes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3603,2139.0,Demon's Horn,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,205,249.0,2,"Whenever a player casts a black spell, you may...",Its curve mimics the twists of life and death.,NaN,NaN,NaN,8,Alan Pollack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3604,2140.0,Dragon's Claw,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,206,249.0,2,"Whenever a player casts a red spell, you may g...","""If there is a fire that never ceases to burn,...",NaN,NaN,NaN,8,Alan Pollack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3605,2141.0,Elixir of Immortality,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,Gabor Szikszai,208,249.0,1,"2, T: You gain 5 life. Shuffle Elixir of Immor...","""Bottled life. Not as tasty as I'm used to, ra...",NaN,NaN,NaN,6,Zoltan Boros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3606,2142.0,Greatsword,NaN,Artifact,Equipment,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,209,249.0,3,Equipped creature gets +3/+0.\nEquip 3 (3: Att...,NaN,NaN,NaN,NaN,4,Nic Klein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3607,2143.0,Kite Shield,NaN,Artifact,Equipment,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,210,249.0,0,Equipped creature gets +0/+3.\nEquip 3 (3: Att...,"""To my sword I owe my glory, but to my shield ...",NaN,NaN,NaN,3,Jim Pavelec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3608,2144.0,Kraken's Eye,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,211,249.0,2,"Whenever a player casts a blue spell, you may ...",It's seen the wonders of entire worlds trapped...,NaN,NaN,NaN,7,Alan Pollack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3609,2145.0,Rusted Sentinel,NaN,Artifact,Creature,Golem,NaN,NaN,M12,Uncommon,NaN,NaN,215,249.0,4,Rusted Sentinel enters the battlefield tapped.,It has to deliberate a moment on the best way ...,3.0,4.0,NaN,5,Jason Felix,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3610,2146.0,Scepter of Empires,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,216,249.0,3,T: Scepter of Empires deals 1 damage to target...,"""With this scepter, smite your enemies.""\n—Sce...",NaN,NaN,NaN,4,John Avon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3611,2147.0,Swiftfoot Boots,NaN,Artifact,Enchantment,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,219,249.0,2,Equipped creature has hexproof and haste. (It ...,NaN,NaN,NaN,NaN,5,Svetlin Velinov,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3612,2148.0,Thran Golem,NaN,Artifact,Creature,Golem,NaN,NaN,M12,Uncommon,NaN,NaN,220,249.0,5,"As long as Thran Golem is enchanted, it gets +...",The golems of the ancient Thran still draw pow...,3.0,3.0,NaN,9,Ron Spears,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3613,2149.0,Wurm's Tooth,NaN,Artifact,NaN,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,223,249.0,2,"Whenever a player casts a green spell, you may...","Jevna Nor lugged it around, bragging of his tr...",NaN,NaN,NaN,4,Alan Pollack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3614,2150.0,Alabaster Mage,NaN,NaN,Creature,Human,Wizard,NaN,M12,Uncommon,NaN,NaN,2,249.0,1W,1W: Target creature you control gains lifelink...,"""We hold sacred th epowers of light and life. ...",NaN,NaN,NaN,5,Izzy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3615,2151.0,Arbalest Elite,NaN,NaN,Creature,Human,Archer,NaN,M12,Uncommon,NaN,NaN,5,249.0,2WW,"2W, T: Arbalest Elite deals 3 damage to target...","There are few things as satisfying as a good, ...",2.0,3.0,NaN,4,Chris Rahn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3616,2152.0,Celestial Purge,NaN,NaN,Instant,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,11,249.0,1W,Exile target black or red permanent.,"""A world without evil? Boring. Give me vile fi...",NaN,NaN,NaN,2,David Palumbo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3617,2153.0,Elite Vanguard,NaN,NaN,Creature,Human,Soldier,NaN,M12,Uncommon,NaN,NaN,15,249.0,W,NaN,The vanguard is skilled at waging war alone. T...,2.0,1.0,NaN,6,Mark Tedin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3618,2154.0,Oblivion Ring,NaN,NaN,Enchantment,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,27,249.0,2W,"When Oblivion Ring enters the battlefield, exi...",NaN,NaN,NaN,NaN,1,Franz Vohwinkel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3619,2155.0,Roc Egg,NaN,NaN,Creature,Bird,NaN,NaN,M12,Uncommon,NaN,NaN,32,249.0,2W,Defender (This creature can't attack.)\nWhen R...,A thin shell lies between the roc and a world ...,0.0,3.0,NaN,6,Paul Bonner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3620,2156.0,Serra Angel,NaN,NaN,Creature,Angel,NaN,NaN,M12,Uncommon,NaN,NaN,33,249.0,3WW,Flying\nVigilance (Attacking creature doesn't ...,"Follow the light. In its absence, follow her.",4.0,4.0,NaN,8,Greg Staples,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3621,2157.0,Spirit Mantle,NaN,NaN,Enchantment,Aura,NaN,NaN,M12,Uncommon,NaN,NaN,35,249.0,1W,Enchant creature\nEnchanted creature gets +1/+...,The shield of unimpeachable purity is as stron...,NaN,NaN,NaN,2,Izzy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3622,2158.0,Alluring Siren,NaN,NaN,Creature,Siren,NaN,NaN,M12,Uncommon,NaN,NaN,42,249.0,1U,T: Target creature an opponent controls attack...,"She lures victims with promises of flesh, capt...",1.0,1.0,NaN,5,Chippy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3623,2159.0,Azure Mage,NaN,NaN,Creature,Human,Wizard,NaN,M12,Uncommon,NaN,NaN,45,249.0,1U,3U: Draw a card.,"""We draw our power from the infinite ocean of ...",2.0,1.0,NaN,5,Izzy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3624,2160.0,Belltower Sphinx,NaN,NaN,Creature,Sphinx,NaN,NaN,M12,Uncommon,NaN,NaN,46,249.0,4U,Flying\nWhenever a source deals damage to Bell...,NaN,3.0,5.0,NaN,5,Jim Nelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3625,2161.0,Flashfreeze,NaN,NaN,Instant,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,52,249.0,1U,Counter target red or green spell.,"""Is cold merely the absence of heat, or a forc...",NaN,NaN,NaN,4,Brian Despain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3626,2162.0,Levitation,NaN,NaN,Enchantment,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,61,249.0,2UU,Creatures you control have flying.,"""Why fight over scraps of land when there's so...",NaN,NaN,NaN,2,Jim Murray,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3627,2163.0,Master Thief,NaN,NaN,Creature,Human,Rogue,NaN,M12,Uncommon,NaN,NaN,64,249.0,2UU,"When Master Thief enters the battlefield, gain...",Possession is ten-tenths of the law.,2.0,2.0,NaN,8,Christopher Moeller,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3628,2164.0,Mind Control,NaN,NaN,Enchantment,Aura,NaN,NaN,M12,Uncommon,NaN,NaN,67,249.0,3UU,Enchant creature\nYou control enchanted creature.,"""Every primitive mind has a motive.\nEasy to f...",NaN,NaN,NaN,9,Ryan Pancoast,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3629,2165.0,Phantasmal Dragon,NaN,NaN,Creature,Dragon,Illusion,NaN,M12,Uncommon,NaN,NaN,71,249.0,2UU,Flying\nWhen Phantasmal Dragon becomes the tar...,Its hunger and ire are no less for being wroug...,5.0,5.0,NaN,5,Wayne Reynolds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3630,2166.0,Turn to Frog,NaN,NaN,Instant,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,78,249.0,1U,Target creature loses all abilities and become...,"""Ribbit.""",NaN,NaN,NaN,5,Warren Mahy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3631,2167.0,Consume Spirit,NaN,NaN,Sorcery,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,88,249.0,X1B,Spend only black mana on X.\nConsume Spirit de...,"""You clerics brag about your strength of spiri...",NaN,NaN,NaN,6,Justin Sweet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3632,2168.0,Deathmark,NaN,NaN,Sorcery,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,90,249.0,B,Destroy target green or white creature.,"""Let the final vision of doom be etched upon t...",NaN,NaN,NaN,2,Steven Belledin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3633,2169.0,Onyx Mage,NaN,NaN,Creature,Human,Wizard,NaN,M12,Uncommon,NaN,NaN,103,249.0,1B,1B: Target creature you control gains deathtou...,"""We wield death and darkness, powers that make...",2.0,1.0,NaN,1,Izzy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3634,2170.0,Reassembling Skeleton,NaN,NaN,Creature,Skeleton,Warrior,NaN,M12,Uncommon,NaN,NaN,104,249.0,1B,1B: Return Reassembling Skeleton from your gra...,"""They may show up with the wrong thigh bone or...",1.0,1.0,NaN,2,Austin Hsu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3635,2171.0,Sengir Vampire,NaN,NaN,Creature,Vampire,NaN,NaN,M12,Uncommon,NaN,NaN,107,249.0,3BB,Flying\nWhenever a creature dealt damage by Se...,"Empires rise and fall, but evil is eternal.",4.0,4.0,NaN,5,Kev Walker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3636,2172.0,Smallpox,NaN,NaN,Sorcery,NaN,NaN,NaN,M12,Uncommon,NaN,NaN,108,249.0,BB,"Each player loses 1 life, discards a card, sac...","Take away a few things, and a rebellion may en...",NaN,NaN,NaN,7,Ryan Pancoast,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
collection[collection['expansion_symbol'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1598,3219.0,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,Anson Maddocks,NaN,NaN,NaN,1B,Take target creature from any graveyard and pu...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1599,3220.0,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,Anson Maddocks,NaN,NaN,NaN,1B,Any creature in any graveyard comes into play ...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600,3221.0,Winter Orb,NaN,Artifact,NaN,NaN,NaN,NaN,NaN,NaN,Mark Tedin,NaN,NaN,NaN,2,No player may untap more than one land during ...,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,3577.0,Brushland,NaN,NaN,Land,NaN,NaN,NaN,NaN,NaN,Tom Wänerstrand,NaN,NaN,NaN,NaN,{T}: Add one colorless mana to your mana pool....,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:

collection[collection['card_name'].isin(['Soltari Priest', 'Benalish Cavalry', 'Knight of the Holy Nimbus', 'Serra Avenger', 'Calciderm', 'Shade of Troikair', 'Stonecloaker', 'Flagstones of Troikair', 'Fortify', 'Griffin Guide', 'Temporal Isolation', 'Mana Tithe', 'Honorable Passage', 'Cloudchaser Kestrel', 'Gemstone Caverns', 'Magus of the Disk', 'Pentarch Paladin', 'Sunlance'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
351,352.0,Griffin Guide,NaN,NaN,Enchantment,Aura,NaN,NaN,Time Spiral,Uncommon,Jim Nelson,NaN,21,301.0,2W,Enchant Creature\nEnchanted creature gets +2/+...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,402.0,Benalish Cavalry,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Common,Parente,NaN,4,301.0,1W,Flanking (Whenever a creature without flanking...,"""My people swore to protect Benalia to the end...",2,2,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,412.0,Temporal Isolation,NaN,NaN,Enchantment,Aura,NaN,NaN,Time Spiral,Common,Stephen Tappin,NaN,43,301.0,1W,Flash (You may play this spell any time you co...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,472.0,Knight of the Holy Nimbus,NaN,NaN,Creature,Human,Rebel,Knight,Time Spiral,Uncommon,Wayne England,NaN,26,301.0,WW,Flanking (Whenever a creature without flanking...,NaN,2,2,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,595.0,Shade of Troikair,NaN,NaN,Creature,Shade,NaN,NaN,Planar Chaos,Common,William O'Connor,NaN,18,165.0,3W,W: Shade of Troikair gets +1/+1 until end of t...,NaN,1,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,597.0,Sunlance,NaN,NaN,Sorcery,NaN,NaN,NaN,Planar Chaos,Common,Volkan Baga,NaN,31,165.0,W,Sunlance deals 3 damage to target nonwhite cre...,"""It's easy for the innocent to speak of justic...",NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1622,3243.0,Serra Avenger,NaN,NaN,Creature,Angel,NaN,NaN,Time Spiral,Rare,Scott M. Fishcer,NaN,40,301.0,WW,You can't play Serra Avenger during your first...,"""Those who endure in the face of suffering, th...",3,3,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,3635.0,Mana Tithe,NaN,NaN,Instant,NaN,NaN,NaN,Strixhaven: Mystical Archive,Rare,Robbie Trevino,NaN,8.0,63.0,{W},Counter target spell unless its controller pay...,"""The tyrant's bellow of rage trailed off into ...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:

collection[collection['card_name'].isin(['Muscle Sliver', 'Sinew Sliver', 'Crystalline Sliver', 'Gemhide Sliver', 'Hibernation Sliver', 'Winged Sliver', 'Harmonic Sliver', 'Quick Sliver', 'Sliver Overlord', 'Sliver Legion', 'Aether Vial', 'Swords to Plowshares', 'Brainstorm', 'Cavern of Souls', 'City of Brass', 'Reflecting Pool', 'Mutavault', 'Forbidden Orchard'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
451,452.0,Gemhide Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,596.0,Sinew Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1767,3388.0,Brainstorm,NaN,NaN,Instant,NaN,NaN,NaN,Commander: Political Puppets,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,3585.0,Reflecting Pool,NaN,NaN,Land,NaN,NaN,NaN,Shadowmoor,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2091,3672.0,Brainstorm,NaN,NaN,Instant,NaN,NaN,NaN,Strixhaven: Mystical Archive,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
collection[collection['card_name'].isin(['Inkmoth Nexus', 'Ichorclaw Myr', 'Phyrexian Crusader', 'Plague Stinger', 'Whispering Specter', 'Despise', 'Dismember', 'Gitaxian Probe', 'Mutagenic Growth', 'Virulent Wound', 'Go for the Throat', 'Grasp of Darkness', 'Marrow Shards', 'Mortarpod', 'Phyrexian Vatmother', 'Piston Sledge'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1672,1673,Phyrexian Crusader,NaN,NaN,Creature,Zombie,Knight,NaN,Mirrodin Besieged,Rare,Eric Deschamps,NaN,50,155.0,1BB,"First strike, protection from red and white\nI...",NaN,2,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1673,1674,Go for the Throat,NaN,NaN,Instant,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,David Rapoza,NaN,43,155.0,1B,Destroy target nonartifact creature.,Having flesh is increasingly a liability on Mi...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1677,1678,Gitaxian Probe,NaN,NaN,Sorcery,NaN,NaN,NaN,New Phyrexia,Common,Chippy,NaN,35,175.0,{U/P},({U/P} can be paid with either U or 2 life.)\n...,"""My flesh holds no secrets, monster. The spiri...",NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1680,1681,Dismember,NaN,NaN,Instant,NaN,NaN,NaN,New Phyrexia,Uncommon,Terese Nielsen,NaN,57,175.0,1{B/P}{B/P},({B/P} can be paid with either B or 2 life.)\n...,"""You serve Phyrexia. Your piees would better s...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3345,3346,Mortarpod,NaN,Artifact,Equipment,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,Eric Deschamps,NaN,115,155.0,2,Living weapon (When this Equipment enters the ...,NaN,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3349,3350,Piston Sledge,NaN,Artifact,Equipment,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,Pete Venters,NaN,124,155.0,3,"When Piston Sledge enters the battlefield, att...",Only the goblins could make a simple machine s...,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3430,3431,Go for the Throat,NaN,NaN,Instant,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,David Rapoza,NaN,43,155.0,1B,Destroy target nonartifact creature.,Having flesh is increasingly a liability on Mi...,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3436,3437,Virulent Wound,NaN,NaN,Instant,NaN,NaN,NaN,Mirrodin Besieged,Common,Whit Brachna,NaN,57,155.0,B,Put a -1/-1 counter on target creature. When t...,"Sadly, the extent of Gerkk's healing knowledge...",NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3458,3459,Ichorclaw Myr,NaN,Artifact,Creature,Myr,NaN,NaN,Scars of Mirrodin,Common,Eric Deschamps,NaN,166,249.0,2,Infect (This creature deals damage to creature...,NaN,1.0,1.0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3513,3514,Marrow Shards,NaN,NaN,Instant,NaN,NaN,NaN,New Phyrexia,Uncommon,Raymond Swanland,NaN,15,175.0,{W/P},({W/P} can be paid with either W or 2 life.)\n...,"""We are a single entity. Dissenters must be su...",NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3523,3524,Despise,NaN,NaN,Sorcery,NaN,NaN,NaN,New Phyrexia,Uncommon,Terese Nielsen,NaN,56,175.0,B,Target opponent reveals his or her hand. You c...,"""Truth is always a weapon in your enemies' han...",NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3565,3566,Gitaxian Probe,NaN,NaN,Sorcery,NaN,NaN,NaN,New Phyrexia,Common,Chippy,NaN,35,175.0,{U/P},({U/P} can be paid with either U or 2 life.)\n...,"""My flesh holds no secrets, monster. The spiri...",NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3593,3594,Mutagenic Growth,NaN,NaN,Instant,NaN,NaN,NaN,New Phyrexia,Common,Dave Kendall,NaN,116,175.0,{G/P},({G/P} can be paid with either G or 2 life.)\n...,"""Sympathy is for weaklings. Whoever survives, ...",NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
collection[collection['card_name'].isin(['Dissipate', 'Feeling of Dread', 'Think Twice', 'Thought Scour', 'Devastation Tide', 'Entreat the Angels', 'Temporal Mastery', 'Terminus', 'Tamiyo, the Moon Sage', 'Evolving Wilds', "Angel's Mercy", 'Cathedral Sanctifier', 'Geist of Saint Traft', 'Midnight Haunting', 'Snapcaster Mage'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
688,2309.0,Dissipate,NaN,NaN,Instant,NaN,NaN,NaN,Innistrad,Uncommon,Tomasz Jedruszek,NaN,53,264.0,1UU,Counter target spell. If that spell is counter...,"""This abomination never belonged in our world....",NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,2453.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Dark Ascension,Common,Cliff Childs,NaN,155,158.0,NaN,"T, Sacrifice Evolving Wilds: Search your libra...","""Our world is vast, but Thraben is its heart. ...",NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,2533.0,Feeling of Dread,NaN,NaN,Instant,NaN,NaN,NaN,Innistrad,Common,John Stanko,NaN,14,264.0,1W,Tap up to two target creatures.\nFlashback 1U ...,"People only say ""I'm sure it ws nothing"" when ...",NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,2618.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,Avacyn Restored,Common,Greg Staples,NaN,5,244.0,2WW,You gain 7 life.,"""I understand your fears. I pity your doubts. ...",NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,2621.0,Cathedral Sanctifier,NaN,NaN,Creature,Human,Cleric,NaN,Avacyn Restored,Common,Michael C. Hayes,NaN,11,244.0,W,When Cathedral Sanctifier enters the battlefie...,"""Evil will soon be vanquished. What Innistrad ...",1,1,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1147,2768.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,M13,Common,Steven Belledin,NaN,224,249.0,NaN,"T, Sacrifice Evolving Wilds: Search your libra...","Without the interfering hands of civilization,...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1589,3210.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Commander: Political Puppets,Common,Steven Belledin,NaN,272,318.0,NaN,"T, Sacrifice Evolving Wilds: Search your libra...","Every world is an organism, able to grow new l...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1753,3374.0,Geist of Saint Traft,Legendary,NaN,Creature,Spirit,Cleric,NaN,Innistrad,Mythic,Igor Kieryluk,NaN,213,264.0,1WU,Hexproof (This creature can't be the target of...,NaN,2,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1755,3376.0,Thought Scour,NaN,NaN,Instant,NaN,NaN,NaN,Dark Ascension,Common,David Rapoza,NaN,52,158.0,U,Target player puts the top two cards of his or...,"""As you inject the viscus vitae into the brain...",NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1762,3383.0,"Tamiyo, the Moon Sage",NaN,NaN,Planeswalker,Tamiyo,NaN,NaN,Avacyn Restored,Rare,Eric Deschamps,NaN,79,244.0,3UU,+1: Tap target permanent. It doesn't untap dur...,NaN,NaN,NaN,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1763,3384.0,Terminus,NaN,NaN,Sorcery,NaN,NaN,NaN,Avacyn Restored,Rare,James Paick,NaN,38,244.0,4WW,Put all creatures on the bottom of their owner...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2933,1469.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M10,Common,Andrew Robinson,NaN,2,249.0,2WW,You gain 7 life.,"""Until that day I cursed the angels, those unc...",NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3762,2298.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,NaN,NaN,4,249.0,2WW,You gain 7 life.,Angels appear before both the blessed and the ...,NaN,NaN,NaN,3,Andrew Robinson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3801,3971.0,Entreat the Angels,NaN,Sorcery,NaN,NaN,NaN,NaN,Avacyn Restored,Mythic,Todd Lockwood,NaN,20,NaN,{X}{X}{W}{W}{W},Put X 4/4 white Angel creature tokens with fly...,NaN,NaN,NaN,NaN,1.0,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3826,3996.0,Devastation Tide,NaN,Sorcery,NaN,NaN,NaN,NaN,Avacyn Restored,Rare,Raymond Swanland,NaN,48,NaN,{3}{U}{U},Return all nonland permanents to their owner's...,It's hard to argue with a force made of distan...,NaN,NaN,NaN,4.0,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3831,4001.0,"Tamiyo, the Moon Sage",NaN,Planeswalker,Tamiyo,NaN,NaN,NaN,Avacyn Restored,Mythic,Eric Deschamps,NaN,79,NaN,{3}{U}{U},NaN,NaN,NaN,NaN,4.0,NaN,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Tap target permanent. It doesn't untap during ...,-2,Draw a card for each tapped creature target pl...,-8.0,"You get an emblem with ""You have no maximum ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,Steven Belledin,NaN,228,248.0,NaN,"{T}, Sacrifice Evolving Wilds: Search your lib...","Every wordl is an organism, able to grow new l...",NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
collection[collection['card_name'].isin(['Ornithopter', 'Memnite', 'Frogmite', 'Arcbound Ravager', 'Master of Etherium', 'Cranial Plating', 'Thoughtcast', 'Thirst for Knowledge', 'Thoughtseize', 'Duress', 'Springleaf Drum', 'Seat of the Synod', 'Vault of Whispers', 'Darksteel Citadel', 'Blinkmoth Nexus'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1613,3234.0,Darksteel Citadel,NaN,Artifact,Land,NaN,NaN,NaN,Darksteel,Common,John Avon,NaN,164,165.0,NaN,"Darksteel Citadel is indestructible. (""Destroy...","Panopticon, forge of the Darksteel Eye, home o...",NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1630,3251.0,Springleaf Drum,NaN,Artifact,NaN,NaN,NaN,NaN,Lorwyn,Common,Cyril Van Der Haegen,NaN,261,301.0,1,"T, Tap an untapped creature you control: Add o...","After trying mudskippers for an afternoon, Scr...",NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1659,3280.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,Steven Belledin,NaN,96,249.0,B,Target opponent reveals his or her hand. You c...,"""Don't worry. I'm not going to deprive you of ...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1661,3282.0,Ornithopter,NaN,Artifact,Creature,Thopter,NaN,NaN,M10,Uncommon,Franz Vohwinkel,NaN,216,249.0,0,Flying,"Regardless of the century, plane, or species, ...",0,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1668,3289.0,Memnite,NaN,Artifact,Creature,Construct,NaN,NaN,Scars of Mirrodin,Uncommon,Svetlin Velinov,NaN,174,249.0,0,NaN,Reminders of Memnarch's reign still skirr acro...,1,1,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1759,3380.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,M13,Common,Steven Belledin,NaN,90,249.0,B,Target opponent reveals his or her hand. You c...,"""Don't worry. I'm not going to deprive you of ...",NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981,3602.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,Strixhaven: Mystical Archive,Uncommon,Kristina Collantes,NaN,29,63.0,{B},Target opponent reveals their hand. You choose...,"""Magic brought peace to the Vastlands but was ...",NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2962,1498.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,Steven Belledin,NaN,96,249.0,B,Target opponent reveals his or her hand. You c...,"""Don't worry. I'm not going to deprive you of ...",NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3291,1827.0,Memnite,NaN,Artifact,Creature,Construct,NaN,NaN,Scars of Mirrodin,Uncommon,Sverlin Velinov,NaN,174,249.0,0,NaN,Reminders of Memnarch's reign still skirr acro...,1.0,1.0,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
#pd.reset_option("all")
pd.set_option('display.max_columns', None)

In [30]:
collection['permanent_id'] = range(1, len(collection) +1)

In [31]:
collection

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4275,4276,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4277,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4278,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4279,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4280,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
# 34 rows are missing expansion_total_cards
# Row 911 is completely empty

In [112]:
df[df.iloc[:, 1:20].isna().all(axis=1)]

Empty DataFrame
Columns: [permanent_id, card_name, supertype, subtype_a, subtype_b, subtype_c, subtype_d, subtype_e, expansion_symbol, rarity, artist_information_a, artist_information_b, collectors_number, expansion_total_cards, mana_cost, text_box, flavor_text, punch, toughness, starting_loyalty, quantity, artist_information]
Index: []

[0 rows x 22 columns]

In [111]:
df = df.drop([2009, 2375])

In [28]:
df[df['expansion_total_cards'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information
6,7,Resistance Fighter,NaN,NaN,Creature,Soldier,NaN,NaN,Visions,Common,...,18,NaN,W,Sacrifice Resistance Fighter: Target creature ...,"""My soldiers fought without hesitation, died w...",1,1,NaN,1,NaN
7,8,Fireblast,NaN,NaN,Instant,NaN,NaN,NaN,Visions,Common,...,79,NaN,4RR,You may sacrifice two mountains instead of pay...,Embermages aren't well known for their diploma...,NaN,NaN,NaN,1,NaN
8,9,Lichenthrope,NaN,NaN,Creature,Lichenthrope,NaN,NaN,Visions,Common,...,112,NaN,3GG,"For each 1 damage dealt to Lichenthrope, put a...",NaN,5,5,NaN,4,NaN
9,10,Quirion Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Visions,Common,...,117,NaN,G,Return a forest you control to owners's hand: ...,"""Respect the earth, for it will one day be you...",1,1,NaN,2,NaN
10,11,Stampeding Wildebeests,NaN,NaN,Creature,Wildebeests,NaN,NaN,Visions,Common,...,121,NaN,2GG,"Trample\nDuring your upkeep, return a green cr...",Prayers for rain are answered with the thunder...,5,4,NaN,1,NaN
11,12,Lava Axe,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,137,NaN,4R,Lava Axe deals 5 damage to your opponent,"Swing your axe as a broom, to sweep away the foe",NaN,NaN,NaN,1,NaN
12,13,Volcanic Hammer,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,154,NaN,1R,Volcanic Hammer deals 3 damage to any one crea...,"Cast the weight as though it were a die, to se...",NaN,NaN,NaN,1,NaN
13,14,Contemplation,NaN,NaN,Enchantment,NaN,NaN,NaN,Stronghold,Common,...,4,NaN,1WW,"Whenever you successfully cast a spell, gain 1...","""How fascinating it is to watch the machinatio...",NaN,NaN,NaN,1,NaN
14,15,Soul Warden,NaN,NaN,Creature,Ceric,NaN,NaN,Exodus,Uncommon,...,21,NaN,W,"Whenever any other creature comes into play, g...",Count carefully the souls and see that none ar...,1,1,NaN,4,NaN
15,16,Talas Merchant,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,50,NaN,1U,NaN,The trader let loose a laugh that made all aro...,1,3,NaN,2,NaN
16,17,Air Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Portal 2,Uncommon,...,31,NaN,3UU,Flying,"As insubstantial, and as powerful, as the wind...",4,4,NaN,2,NaN
17,18,Touch of Brilliance,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,58,NaN,3U,NaN,NaN,NaN,NaN,NaN,2,NaN
18,19,Talas Researcher,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Rare,...,66,NaN,4U,"On your turn, before you attack, you may tap T...","From time, knowledge.\nFrom knowledge, power.",1,1,NaN,1,NaN
19,20,False Summoning,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,40,NaN,1U,Play False Summoning only in response to anoth...,NaN,NaN,NaN,NaN,2,NaN
20,21,Talas Air Ship,NaN,NaN,Creature,Ship,NaN,NaN,Portal 2,Common,...,48,NaN,3U,Flying,"""Their ships pollute our air as they themselve...",3,2,NaN,2,NaN
21,22,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,41,NaN,1UU,Play Mystic Denial only in response to another...,NaN,NaN,NaN,NaN,2,NaN
22,23,Talas Scout,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Common,...,52,NaN,1U,Flying,"""Scouting a battle before you fight it is just...",1,2,NaN,2,NaN
23,24,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Uncommon,...,32,NaN,2U,"On your turn, before you attack, you may tap A...",NaN,1,1,NaN,2,NaN
24,25,Exhaustion,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,37,NaN,2U,"At the beginning of your opponent's next turn,...",NaN,NaN,NaN,NaN,1,NaN
25,26,Talas Explorer,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,49,NaN,1U,Flying,When Talas Explorer comes into play from your ...,1,1,NaN,2,NaN
26,27,Time Ebb,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,57,NaN,2U,Return any one creature from play to the top o...,"""The ogre had come from out of the blue, so th...",NaN,NaN,NaN,2,NaN
27,28,Talas Warrior,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Rare,...,53,NaN,1UU,Talas Warrior can't be blocked,The sea is in their blood. Literally.,2,2,NaN,1,NaN
28,29,Monstrous Growth,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,133,NaN,1G,Any one creature gets +4/+4 until the end of t...,The nightstalker's little game of tease-the-sq...,NaN,NaN,NaN,2,NaN
29,30,Alluring Scent,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,121,NaN,1GG,"Choose any one creature. This turn, all creatu...",No earthly armor is protection against this sw...,NaN,NaN,NaN,1,NaN
30,31,Wild Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Uncommon,...,150,NaN,3G,Swampwalk (If defending player has any swamps ...,"It has the run of the swamps, and it knows it.",3,3,NaN,2,NaN
31,32,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,NaN,Portal 2,Uncommon,...,146,NaN,3GG,"If Sylvan Basilisk attacks and is blocked, des...",NaN,2,4,NaN,1,NaN
32,33,River Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Uncommon,...,144,NaN,3G,Islandwalk (If defending player has any island...,The bears had been isolated on an island for h...,3,3,NaN,2,NaN
33,34,Norwood Riders,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,139,NaN,3G,Norwood Riders can't be blocked by more than o...,"""Trade my moose? Sure—when I find a horse that...",3,3,NaN,2,NaN
34,35,Norwood Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Portal 2,Common,...,138,NaN,G,NaN,Some trees bear deadly fruit.,1,2,NaN,2,NaN
35,36,Norwood Archers,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,136,NaN,3G,Norwood Archers can block creatures with flying.,"""'Air superiority?' Not while our archers scan...",3,3,NaN,2,NaN
36,37,Golden Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,127,NaN,3G,NaN,The elvish scout was scrupulous about the trut...,4,3,NaN,2,NaN
37,38,Bear Cub,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,123,NaN,1G,NaN,Every little cub has its mother's teeth to gua...,2,2,NaN,3,NaN
38,39,Ironhoof Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Common,...,130,NaN,3GG,Ironhoof Ox can't be blocked by more than one ...,The good news is it's vegetarian. The bad news...,4,4,NaN,2,NaN
39,40,Angel of Fury,NaN,NaN,Creature,Angel,NaN,NaN,Portal 2,Rare,...,7,NaN,4WW,Flying\nIf Angel of Fury is put into your grav...,NaN,3,5,NaN,1,NaN
40,41,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,20,NaN,1WW,All your creatures get +2/+2 until the end of ...,NaN,NaN,NaN,NaN,1,NaN
1598,1599,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,...,NaN,NaN,1B,Take target creature from any graveyard and pu...,NaN,NaN,NaN,NaN,1.0,NaN
1599,1600,Animate Dead,NaN,NaN,Enchant,Dead,Creature,NaN,NaN,NaN,...,NaN,NaN,1B,Any creature in any graveyard comes into play ...,NaN,NaN,NaN,NaN,3.0,NaN
1600,1601,Winter Orb,NaN,Artifact,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2,No player may untap more than one land during ...,NaN,NaN,NaN,NaN,3.0,NaN
1757,1758,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,1991,"Ishgard, the Holy See",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,283.0,NaN,NaN,This land enters tapped.\n{T}: Add {W}.,"A great and proud nation devoted to Halone, th...",NaN,NaN,NaN,1.0,NaN
1991,1992,"Lindblum, Industrial Regency",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,285.0,NaN,NaN,This land enters tapped.\n{T}: Add {R}.,A city encircled by the ramparts of a massive ...,NaN,NaN,NaN,1.0,NaN
1993,1994,Brushland,NaN,NaN,Land,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,{T}: Add one colorless mana to your mana pool....,NaN,NaN,NaN,NaN,1.0,NaN
2028,2028,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,NaN,Starter 2000,Rare,...,NaN,NaN,{3}{W},Return target creature card from your graveyar...,NaN,NaN,NaN,NaN,1.0,NaN
2097,2097,"Jill, Shiva's Dominant",Legendary,NaN,Creature,Human,Noble,Warrior,Universes Beyond: Final Fantasy,Rare,...,58.0,NaN,{2}{U},"When Jill enters, return up to one other targe...","""I'm going to help you. To give you what you n...",2,2,NaN,1.0,NaN
2140,2140,The Darkness Crystal,Legendary,Artifact,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,96.0,NaN,{2}{B}{B},Black spells you cast cost {1} less to cast.\n...,NaN,NaN,NaN,NaN,1.0,NaN
2141,2141,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,278.0,NaN,{2}{R},Instant and sorcery spells you cast cost 1 les...,NaN,NaN,NaN,2.0,1.0,NaN

In [75]:
df.loc[df['expansion_symbol'] == 'Visions', 'expansion_total_cards'] = 167
df.loc[df['expansion_symbol'] == 'Portal', 'expansion_total_cards'] = 222
df.loc[df['expansion_symbol'] == 'Stronghold', 'expansion_total_cards'] = 143
df.loc[df['expansion_symbol'] == 'Exodus', 'expansion_total_cards'] = 143
df.loc[df['expansion_symbol'] == 'Portal 2', 'expansion_total_cards'] = 165
df.loc[df['expansion_symbol'] == 'Universes Beyond: Final Fantasy'] = 309

In [77]:
df['expansion_total_cards'] = df['expansion_total_cards'].astype(int)

In [117]:
collection[collection[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].apply(lambda x: x.str.contains('sliver', case=False, na=False)).any(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information_a,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information,expansion_total,flip_card_name,flip_subtype_a,flip_subtype_b,flip_subtype_c,flip_subtype_d,flip_punch,flip_toughness,split_card_name,split_mana_cost,split_subtype_a,split_text_box,loyalty_cost_a,loyalty_ability_a,loyalty_cost_b,loyalty_ability_b,loyalty_cost_c,loyalty_ability_c,leveler_tier_a,leveler_text_box_a,leveler_tier_a_punch,leveler_tier_a_toughness,leveler_tier_b,leveler_text_box_b,leveler_tier_b_punch,leveler_tier_b_toughness,transform_card_name,transform_supertype,transform_subtype_a,transform_subtype_b,transform_subtype_c,transform_text_box,transform_flavor_text,transform_punch,transform_toughness,modal_card_name,modal_mana_cost,modal_supertype,modal_subtype_c,modal_subtype_b,modal_subtype_a,modal_text_box,modal_punch,modal_toughness,saga_card_name,lore_counter_a,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
353,354.0,Quilled Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,John Matson,NaN,37,301.0,1W,"All Slivers have ""T: This creature deals 1 dam...","""They have long kept us under attack, but we d...",1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,374.0,Firewake Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,Anthony S. Waters,NaN,238,301.0,1RG,"All Slivers have haste and ""1, Sacrifice this ...","""They are here, and they are hungry. And what ...",1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
385,386.0,Might Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,Jeff Miracola,NaN,205,301.0,4G,All Slivers get +2/+2.,"""The colossal thing rumbled over the ridge, tr...",2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,400.0,Venser's Sliver,NaN,Artifact,Creature,Sliver,NaN,NaN,Time Spiral,Common,Carl Critchlow,NaN,267,301.0,5,NaN,Venser admired his handiwork and smiled. His f...,3,3,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,422.0,Screeching Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Stuart Griffin,NaN,75,301.0,U,"All Slivers have ""T: Target player puts the to...","""What wears down my people most, I think, is n...",1,1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,442.0,Bonesplitter Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Dany Orizio,NaN,149,301.0,3R,All Slivers get +2/+0.,As the time streams grew more and more unstabl...,2,2,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,452.0,Gemhide Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,John Matson,NaN,196,301.0,1G,"All Slivers have ""T: Add one mana of any color...","""The land is weary. Even Skyshroud is depleted...",1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457,458.0,Spinneret Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Michael Sutfin,NaN,219,301.0,1G,"All Slivers have ""This creature can block as t...",Each new generation of slivers evolves to assi...,2,2,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,475.0,Quilled Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,John Matson,NaN,37,301.0,1W,"All Slivers have ""T: This creature deals 1 dam...","""They have long kept us under attack, but we d...",1,1,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,478.0,Telekinetic Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,Randy Elliott,NaN,84,301.0,2UU,"All Slivers have ""T: Tap target permanent.""","""Slivers are guided only by simple instinct. A...",2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,481.0,Vampiric Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,Thomas M. Baxa,NaN,140,301.0,3B,"All Slivers have ""Whenever a creature dealt da...",They draw upon the strength of their hive and ...,3,3,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,488.0,Sidewinder Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Ron Spencer,NaN,41,301.0,W,All slivers have flanking. (Whenever a creatur...,"""They encircled our patrol with the stealth of...",1,1,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,489.0,Watcher Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Liz Danforth,NaN,45,301.0,3W,All Slivers get +0/+2.,"""I have spied them, wandering and watching—but...",2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,496.0,Shadow Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Warren Mahy,NaN,76,301.0,2U,All Slivers have shadow. (They can block or be...,"These slivers, trapped between worlds since th...",1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,500.0,Basal Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Drew Tucker,NaN,96,301.0,2B,"All slivers have ""Sacrifice this creature: Add...","""Fascinating...These creatures display the par...",2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,502.0,Mindlash Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Jeff Miracola,NaN,118,301.0,B,"All Slivers have ""1, Sacrifice this creature: ...",Though Dominaria's queenless slivers lack a si...,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,511.0,Two-Headed Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,Dany Orizio,NaN,183,301.0,1R,"All Slivers have ""This creature can't be block...","""That which would be a fatal mutation in any o...",1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,524.0,Dormant Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Uncommon,Lars Grant-West,NaN,156,165.0,2GU,"All Slivers have never and ""When this creature...","""It triggers the hive's period of Aetheric fer...",2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,533.0,Poultice Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,Randy Gallegos,NaN,11,165.0,2W,"All Slivers have ""2, T: Regenerate target Sliv...","""Its broad claw suggests a chitinous shield, b...",2,2,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,543.0,Synchronous Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,E. M. Gist,NaN,48,165.0,4U,All Slivers have vigilance.,"""Wish a twitch of its muscles, its timeline fo...",3,3,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
551,552.0,Spitting Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,Steve Ellis,NaN,80,165.0,4B,All Slivers have first strike.,"""Our lances' reach had been our saving grace i...",3,3,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552,553.0,Battering Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,Greg Staples,NaN,95,165.0,5R,All Slivers have trample.,"Covered with hard shell-like plates, these sli...",4,4,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,569.0,Reflex Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,Luca Zontini,NaN,138,165.0,3G,All Slivers have haste.,"""This sliver comes into the world a perfect pr...",2,2,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,581.0,Frenetic Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Uncommon,Luca Zontini,NaN,157,165.0,1UR,"All Slivers have ""0: If this creature is in pl...",NaN,2,2,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,596.0,Sinew Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,Steven Belledin,NaN,30,165.0,1W,All Slivers get +1/+1.,"As the muscle cords of the creature twitched, ...",1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,625.0,Lymph Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,Ittoku,NaN,26,180.0,4W,All Sliver creatures have absorb 1. (If a sour...,"Its skin remains in a flowing, liquid state th...",3,3,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
653,654.0,Virulent Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,Franz Vohwinkel,NaN,155,180.0,G,All Sliver creatures have poisonous 1. (Whenev...,NaN,1,1,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,671.0,Mesmeric Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,Michael Bruinsma,NaN,53,180.0,3U,"All Slivers have ""When this permanent comes in...",NaN,2,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,675.0,Frenzy Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,Glen Angus,NaN,85,180.0,1B,All Slivers creatures have frenzy 1. (Whenever...,"The Arturan conjurers took the strange, alien ...",1,1,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3775,3945.0,Pulmonic Sliver,NaN,Creature,Sliver,NaN,NaN,NaN,Time Spiral,Rare,Jeff Easley,NaN,36,NaN,{3}{W}{W},"All Slivers have flying and ""If this creature ...","Like a great bellows it hisses, and its kin, b...",3,3,NaN,1.0,NaN,301.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.tail()

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity,artist_information
3758,3759,Stampeding Rhino,NaN,NaN,Creature,Rhino,NaN,NaN,M12,Common,...,196,249.0,4G,Trample (If this creature would assign enough ...,The quickest way to get through the jungle is ...,4.0,4.0,NaN,3,Steven Belledin
3759,3760,Titanic Growth,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,198,249.0,1G,Target creature gets +4/+4 until end of turn.,"The pup looked over the treetops, eyeing the m...",NaN,NaN,NaN,11,Ryan Pancoast
3760,3761,Trollhide,NaN,NaN,Enchantment,Aura,NaN,NaN,M12,Common,...,199,249.0,2G,Enchant creature\nEnchanted creature gets +2/+...,NaN,NaN,NaN,NaN,9,Steven Belledin
3761,3762,Vastwood Gorger,NaN,NaN,Creature,Wurm,NaN,NaN,M12,Common,...,200,249.0,5G,NaN,The gorger's insect-like eyes pick up the slig...,5.0,6.0,NaN,6,Kieran Yanner
3762,3763,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,4,249.0,2WW,You gain 7 life.,Angels appear before both the blessed and the ...,NaN,NaN,NaN,3,Andrew Robinson

In [ ]:
import mysql.connector
try:
    # 1. Establish the connection
    db_connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="password",
        database="trading_card_collection"
    )

    if db_connection.is_connected():
        print("Successfully connected to the database")

    # 2. Create a cursor to execute SQL queries
    cursor = db_connection.cursor()
    cursor.execute("SELECT DATABASE();")
    record = cursor.fetchone()
    print("You're connected to the database:", record)

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    # 3. Always close the connection
    if 'db-connection' in locals() and db_connection.is_connected():
        cursor.close()
        db_connection.close()
        print("MySQL connection is closed")

In [ ]:
# 1. JUNCTION TABLE
# for each row, iterate through subtype columns
# if the subtype is nan, do nothing
# if the subtype is valid, add it to an array
# iterate through the array and query the parent table for the matching index
# insert the id and subtype into the junction table

In [ ]:
cursor.execute("CREATE TABLE permanent_junction_subtype (permanent_id INT,subtype_id INT,PRIMARY KEY (permanent_id, subtype_id));")

In [ ]:
row_subtypes = df.iloc[1059, 3:8].to_numpy()

In [ ]:
row_subtypes

In [ ]:
df.iloc[:, 1:1822] = df.iloc[:, 1:50].fillna(0)

In [ ]:
import math
import numpy as np

for i, row in enumerate(df, start=1):
    permanent_id = df.iloc[i, 1]
    subtypes = df.iloc[i, 3:8].to_numpy()
    for type in subtypes:
        #if math.isnan(type):
        if type == "":
            continue
        else:
            cursor.execute("SELECT subtype_id FROM subtype WHERE subtype = %s", (type))
            subtype_id = cursor.fetchone()[0]
            cursor.execute("INSERT INTO permanent_junction_subtype (permnent_id, subtype_id) VALUES (%s, %s)" (permanent_id, subtype_id))
            connection.commit()

In [ ]:
import pandas as pd
import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_database"
)
cursor = db.cursor()

target_cols = ['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']

for index, row in df.iterrows():
    for col in target_cols:
        val = row[col]

        if pd.isna(val):
            continue

        query_parent = "SELECT subtype_id FROM subtype WHERE subtype = %s"
        cursor.execute(query_parent, (val,))
        result = cursor.fetchone()

        if result:
            parent_id = result[0]
            insert_child = "INSERT INTO child_table (parent_id, df_index) VALUES (%s, %s)"
            cursor.execute(insert_child, (parent_id, index))

db.commit()
cursor.close()
db.close()

In [ ]:
# 2. PARENT TABLE
# create a list of all unique subtypes in the dataframe
# remove any instances of nan or blank subtypes
# find the longest subtype
# create table declaring subtype as VARCHAR() use the length of the longest subtype as the parameter for varchar

In [40]:
df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect',
       'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Sliver',
       'Eye', 'Gargoyle', 'Orgg', 'Avatar', 'Fungus', 'Kithkin',
       'Merfolk', 'Gorgon', 'Leech', 'Kor', 'Encahntment', 'Serpent',
       'Homarid', 'Orc', 'Shapeshifter', 'Shade', 'Wraith', 'Cyclops',
       'Tribal', 'Forest', 'Ouphe', 'Myr', 'Vampire', 'Bat', 'Curse',
       'Werewolf', 'Treefolk', 'Juggernaut', 'Construct', 'Fox',
       'Homunculus', 'Devil', 'Boar', 'Scarecrow', 'Elk', 'Demon',
       'Lizard', 'Kraken', 'Gate', 'Fish', 'Leviathan', 'Jellyfish',
       'Hommunculus', 'Vedalken', 'Crocodile', 'Eldrazi', 'Drone', 'Ally',
       'Planeswalker', 'Venser', 'Sphinx', 'Slith', 'Worm', 'Koth',
       'Thopter', 'Enchatment', 'Dragon', 'Encahantment', 'Enchant',
       'Dead', "Urza's", 'Jace', 'Praetor', 'Ooze', 'Archon', 'Rhino',
       'Gideon', 'Tamiyo', 'Mana Source', 'Ajani', 'Desert', 'Lesson',
       'Dog', 'Djinn', 'Warlock', 'Specter', 'Fog', 'Dwarf', 'Squirrel',
       'Relic', 'Town', 'Noble', 'Rowan', 'Instinct', 'Island', 'Hag',
       'Noggle', 'Gobiln', 'Artificer', 'Unicorn', 'Antelope', 'Funugs',
       'Trap', 'Surrakar', 'Horse', 'Gremlin', 'Hellion', 'Siren',
       'Dragon ', 'Salamander', 'Creatue'], dtype=object)

In [41]:
subtype_arr = df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

In [42]:
max(subtype_arr, key=len)

'Lichenthrope'

In [43]:
len(max(subtype_arr, key=len))

12

In [15]:
longest = len(max(subtype_arr, key=len))

In [ ]:
# create a dataframe from the array of uniques

In [16]:
subtype_df = pd.DataFrame(subtype_arr)

In [17]:
subtype_df

               0
0    Enchantment
1           Aura
2       Creature
3       Illusion
4       Artifact
..           ...
131         Fish
132    Crocodile
133         Boar
134     Surrakar
135      Thopter

[136 rows x 1 columns]

In [22]:
subtype_df['subtype_id'] = range(1, len(subtype_df) + 1)

In [23]:
subtype_df

         subtype  subtype_id
0    Enchantment           1
1           Aura           2
2       Creature           3
3       Illusion           4
4       Artifact           5
..           ...         ...
131         Fish         132
132    Crocodile         133
133         Boar         134
134     Surrakar         135
135      Thopter         136

[136 rows x 2 columns]

In [19]:
subtype_df = subtype_df.rename(columns={0: 'subtype'})

In [24]:
subtype_df

         subtype  subtype_id
0    Enchantment           1
1           Aura           2
2       Creature           3
3       Illusion           4
4       Artifact           5
..           ...         ...
131         Fish         132
132    Crocodile         133
133         Boar         134
134     Surrakar         135
135      Thopter         136

[136 rows x 2 columns]

In [26]:
subtype_df = subtype_df[['subtype_id', 'subtype']]

In [27]:
subtype_df

     subtype_id      subtype
0             1  Enchantment
1             2         Aura
2             3     Creature
3             4     Illusion
4             5     Artifact
..          ...          ...
131         132         Fish
132         133    Crocodile
133         134         Boar
134         135     Surrakar
135         136      Thopter

[136 rows x 2 columns]

In [28]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_collection"
)
cursor = conn.cursor()

# Create the table manually
cursor.execute("""
    CREATE TABLE IF NOT EXISTS subtype (
        subtype_id INT,
        subtype VARCHAR(%s)
    )
    """, (longest,))

In [29]:
# Prepare the data as a list of tuples
data_to_insert = [tuple(x) for x in subtype_df.values]

# SQL query with placeholders
sql = "INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)"

# Execute and commit
cursor.executemany(sql, data_to_insert)
conn.commit() # Vital: changes won't save without this

print(f"{cursor.rowcount} records inserted.")
cursor.close()
conn.close()

136 records inserted.

In [ ]:
#cursor.execute("CREATE TABLE IF NOT EXISTS subtype (subtype_id INT, subtype VARCHAR(%s) PRIMARY KEY", (longest,))

In [ ]:
#for index, subtype in enumerate(subtypes, start=1):
    #cursor.execute("INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)" (index, subtype))

In [79]:
expansion_symbol_df = df[['expansion_symbol', 'expansion_total_cards']].drop_duplicates()

In [80]:
expansion_symbol_df

           expansion_symbol  expansion_total_cards
0                   Ice Age                    383
5                 Alliances                    144
6                   Visions                    167
11                   Portal                    222
13               Stronghold                    143
14                   Exodus                    143
15                 Portal 2                    165
41              Urza's Saga                    350
47            Urza's Legacy                    143
48             Starter 1999                    173
60        Mercadian Masques                    350
61            Sixth Edition                    350
110                 Nemesis                    143
115                Prophecy                    143
116                Invasion                    350
119         Seventh Edition                    350
122              Planeshift                    143
126                 Odyssey                    350
143                 Torment                    143
144               Judgement                    143
176                 Legions                    145
178                 Scourge                    143
179                Mirrodin                    306
193               Darksteel                    165
197              Fifth Dawn                    165
200             Fifth Dawn                     165
204   Champions of Kamigawa                    306
208   Betrayers of Kamigawa                    165
210           Ninth Edition                    350
215                 Ravnica                    306
255               Guildpact                    165
293          Eighth Edition                    350
310              Dissension                    180
328                Coldsnap                    155
341             Time Spiral                    121
342             Time Spiral                    301
395            Time Spiral                     301
422             Time Sprial                    301
515            Planar Chaos                    165
571           Planar Chaos                     165
604             Futuresight                    180
618             Futuresight                    150
678                  Lorwyn                    301
876             Morningtide                    150
971              Shadowmoor                    301
1111             Shdaowmoor                    301
1162               Eventide                    180
1232               Eventide                    108
1270        Shards of Alara                    249
1369                Conflux                    145
1424           Alara Reborn                    145
1447                    M10                    249
1510                   M10                     249
1529          Tenth Edition                    383
1662               Zendikar                    249
1748              Worldwake                    145
1750              Wordlwake                    145
1799        Rise of Eldrazi                    248
1805                    M11                    249

In [81]:
expansion_symbol_df['expansion_symbol_id'] = range(1, len(expansion_symbol_df) + 1)

In [82]:
expansion_symbol_df

           expansion_symbol  expansion_total_cards  expansion_symbol_id
0                   Ice Age                    383                    1
5                 Alliances                    144                    2
6                   Visions                    167                    3
11                   Portal                    222                    4
13               Stronghold                    143                    5
14                   Exodus                    143                    6
15                 Portal 2                    165                    7
41              Urza's Saga                    350                    8
47            Urza's Legacy                    143                    9
48             Starter 1999                    173                   10
60        Mercadian Masques                    350                   11
61            Sixth Edition                    350                   12
110                 Nemesis                    143                   13
115                Prophecy                    143                   14
116                Invasion                    350                   15
119         Seventh Edition                    350                   16
122              Planeshift                    143                   17
126                 Odyssey                    350                   18
143                 Torment                    143                   19
144               Judgement                    143                   20
176                 Legions                    145                   21
178                 Scourge                    143                   22
179                Mirrodin                    306                   23
193               Darksteel                    165                   24
197              Fifth Dawn                    165                   25
200             Fifth Dawn                     165                   26
204   Champions of Kamigawa                    306                   27
208   Betrayers of Kamigawa                    165                   28
210           Ninth Edition                    350                   29
215                 Ravnica                    306                   30
255               Guildpact                    165                   31
293          Eighth Edition                    350                   32
310              Dissension                    180                   33
328                Coldsnap                    155                   34
341             Time Spiral                    121                   35
342             Time Spiral                    301                   36
395            Time Spiral                     301                   37
422             Time Sprial                    301                   38
515            Planar Chaos                    165                   39
571           Planar Chaos                     165                   40
604             Futuresight                    180                   41
618             Futuresight                    150                   42
678                  Lorwyn                    301                   43
876             Morningtide                    150                   44
971              Shadowmoor                    301                   45
1111             Shdaowmoor                    301                   46
1162               Eventide                    180                   47
1232               Eventide                    108                   48
1270        Shards of Alara                    249                   49
1369                Conflux                    145                   50
1424           Alara Reborn                    145                   51
1447                    M10                    249                   52
1510                   M10                     249                   53
1529          Tenth Edition                    383                   54
1662               Zendikar                    249                   55
1748              Worldwake                    145                   56
1750              Wordlwake                    145                   57
1799        Rise of Eldrazi                    248                   58
1805                    M11                    249                   59

In [83]:
expansion_symbol_df = expansion_symbol_df[['expansion_symbol_id', 'expansion_symbol', 'expansion_total_cards']]

In [84]:
expansion_symbol_df

      expansion_symbol_id       expansion_symbol  expansion_total_cards
0                       1                Ice Age                    383
5                       2              Alliances                    144
6                       3                Visions                    167
11                      4                 Portal                    222
13                      5             Stronghold                    143
14                      6                 Exodus                    143
15                      7               Portal 2                    165
41                      8            Urza's Saga                    350
47                      9          Urza's Legacy                    143
48                     10           Starter 1999                    173
60                     11      Mercadian Masques                    350
61                     12          Sixth Edition                    350
110                    13                Nemesis                    143
115                    14               Prophecy                    143
116                    15               Invasion                    350
119                    16        Seventh Edition                    350
122                    17             Planeshift                    143
126                    18                Odyssey                    350
143                    19                Torment                    143
144                    20              Judgement                    143
176                    21                Legions                    145
178                    22                Scourge                    143
179                    23               Mirrodin                    306
193                    24              Darksteel                    165
197                    25             Fifth Dawn                    165
200                    26            Fifth Dawn                     165
204                    27  Champions of Kamigawa                    306
208                    28  Betrayers of Kamigawa                    165
210                    29          Ninth Edition                    350
215                    30                Ravnica                    306
255                    31              Guildpact                    165
293                    32         Eighth Edition                    350
310                    33             Dissension                    180
328                    34               Coldsnap                    155
341                    35            Time Spiral                    121
342                    36            Time Spiral                    301
395                    37           Time Spiral                     301
422                    38            Time Sprial                    301
515                    39           Planar Chaos                    165
571                    40          Planar Chaos                     165
604                    41            Futuresight                    180
618                    42            Futuresight                    150
678                    43                 Lorwyn                    301
876                    44            Morningtide                    150
971                    45             Shadowmoor                    301
1111                   46             Shdaowmoor                    301
1162                   47               Eventide                    180
1232                   48               Eventide                    108
1270                   49        Shards of Alara                    249
1369                   50                Conflux                    145
1424                   51           Alara Reborn                    145
1447                   52                    M10                    249
1510                   53                   M10                     249
1529                   54          Tenth Edition                    383
1662                   55               Zendikar                    249
1748                   56              Worldwake                    145
1750                   57              Wordlwake                    145
1799                   58        Rise of Eldrazi                    248
1805                   59                    M11                    249

In [85]:
df[df['expansion_symbol'] == 'Fifth Dawn ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
200,201,Spark Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Fifth Dawn,Common,John Avon,79,165,R,"Trample, haste\nAt end of turn, sacrifice Spar...","""Vulshok shamans summon spark elementals to bu...",3,1,NaN,5

In [86]:
df[df['expansion_symbol'] == 'Time Sprial']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
422,423,Snapback,NaN,NaN,Instant,NaN,NaN,NaN,Time Sprial,Common,Alan Pollack,78,301,1U,You may remove a blue card in your hand from t...,"""If it returns years hence, our knowledge of h...",NaN,NaN,NaN,3

In [87]:
df[df['expansion_symbol'] == 'Time Spiral ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
395,396,Terramorphic Expanse,NaN,NaN,Land,NaN,NaN,NaN,Time Spiral,Common,Dan Scott,279,301,NaN,"T, Sacrifice Terramorphic Expanse: Search your...",Take two steps north into the unsettled future...,NaN,NaN,NaN,3

In [103]:
df[df['expansion_symbol'] == 'Planar Chaos ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
571,572,Vitaspore Thallid,NaN,NaN,Creature,Fungus,NaN,NaN,Planar Chaos,Common,Christopher Moeller,141,165,1G,"At the beginning of your upkeep, put a spore c...",NaN,1,1,NaN,3
587,588,Kor Dirge,NaN,NaN,Instant,NaN,NaN,NaN,Planar Chaos,Uncommon,Alex Horley-Orlandelli,87,165,2B,All damage that would be dealt this turn to ta...,Rath's new evincar eliminated the brutish mogg...,NaN,NaN,NaN,3

In [88]:
df[(df['expansion_symbol'] == 'Futuresight') & (df['expansion_total_cards'] == 150)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
618,619,Utopia Mycon,NaN,NaN,Creature,Fungus,NaN,NaN,Futuresight,Uncommon,Anthony S. Waters,140,150,G,"At the beginning of your upkeep, put a spore c...",NaN,0,2,NaN,1

In [89]:
df[df['expansion_symbol'] == 'Shdaowmoor']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1111,1112,Firespout,NaN,NaN,Sorcery,NaN,NaN,NaN,Shdaowmoor,Uncommon,Jeff Miracola,205,301,2{R/G},Firespout deals 3w damage to each creature wit...,NaN,NaN,NaN,NaN,4.0

In [90]:
df[(df['expansion_symbol'] == 'Eventide') & (df['expansion_total_cards'] == 108)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1232,1233,Noggle Hedge-Mage,NaN,NaN,Creature,Noggle,Wizard,NaN,Eventide,Uncommon,Rebecca Guay,27,108,2U,Target player draws a card.\nRetrace (You may ...,Oona grants her favored subjects a dream from ...,NaN,NaN,NaN,4.0

In [91]:
df[df['expansion_symbol'] == 'Wordlwake']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1750,1751,Loam Lion,NaN,NaN,Creature,Cat,NaN,NaN,Wordlwake,Uncommon,Daniel Ljunggren,13,145,W,Loam Lion gets +1/+2 as long as you control a ...,"In Zendikar, today's grassland could be tomorr...",1,1.0,NaN,1

In [92]:
df[df['expansion_symbol'] == 'M10 ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1510,1511,Panic Attack,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,Izzy,150,249,2R,Up to three target creatures can't block this ...,"""What do they see in the throes of panic? I'm ...",NaN,NaN,NaN,2

In [93]:
df.loc[200, 'expansion_symbol'] = 'Fifth Dawn'

In [94]:
df.loc[422, 'expansion_symbol'] = 'Time Spiral'

In [95]:
df.loc[395, 'expansion_symbol'] = 'Time Spiral'

In [96]:
df.loc[618, 'expansion_total_cards'] = 180

In [106]:
df.loc[571, 'expansion_symbol'] = 'Planar Chaos'

In [107]:
df.loc[587, 'expansion_symbol'] = 'Planar Chaos'

In [97]:
df.loc[1111, 'expansion_symbol'] = 'Shadowmoor'

In [98]:
df.loc[1232, 'expansion_total_cards'] = 180

In [99]:
df.loc[1750, 'expansion_symbol'] = 'Worldwake'

In [100]:
df.loc[1510, 'expansion_symbol'] = 'M10'

In [109]:
df[['expansion_symbol', 'expansion_total_cards']].drop_duplicates()

           expansion_symbol  expansion_total_cards
0                   Ice Age                    383
5                 Alliances                    144
6                   Visions                    167
11                   Portal                    222
13               Stronghold                    143
14                   Exodus                    143
15                 Portal 2                    165
41              Urza's Saga                    350
47            Urza's Legacy                    143
48             Starter 1999                    173
60        Mercadian Masques                    350
61            Sixth Edition                    350
110                 Nemesis                    143
115                Prophecy                    143
116                Invasion                    350
119         Seventh Edition                    350
122              Planeshift                    143
126                 Odyssey                    350
143                 Torment                    143
144               Judgement                    143
176                 Legions                    145
178                 Scourge                    143
179                Mirrodin                    306
193               Darksteel                    165
197              Fifth Dawn                    165
204   Champions of Kamigawa                    306
208   Betrayers of Kamigawa                    165
210           Ninth Edition                    350
215                 Ravnica                    306
255               Guildpact                    165
293          Eighth Edition                    350
310              Dissension                    180
328                Coldsnap                    155
341             Time Spiral                    121
342             Time Spiral                    301
515            Planar Chaos                    165
604             Futuresight                    180
678                  Lorwyn                    301
876             Morningtide                    150
971              Shadowmoor                    301
1162               Eventide                    180
1270        Shards of Alara                    249
1369                Conflux                    145
1424           Alara Reborn                    145
1447                    M10                    249
1529          Tenth Edition                    383
1662               Zendikar                    249
1748              Worldwake                    145
1799        Rise of Eldrazi                    248
1805                    M11                    249

In [110]:
expansion_symbol_df = df[['expansion_symbol', 'expansion_total_cards']].drop_duplicates()

In [111]:
expansion_symbol_df['expansion_symbol_id'] = range(1, len(expansion_symbol_df) + 1)

In [113]:
expansion_symbol_df = expansion_symbol_df[['expansion_symbol_id', 'expansion_symbol', 'expansion_total_cards']]

In [114]:
expansion_symbol_df

      expansion_symbol_id       expansion_symbol  expansion_total_cards
0                       1                Ice Age                    383
5                       2              Alliances                    144
6                       3                Visions                    167
11                      4                 Portal                    222
13                      5             Stronghold                    143
14                      6                 Exodus                    143
15                      7               Portal 2                    165
41                      8            Urza's Saga                    350
47                      9          Urza's Legacy                    143
48                     10           Starter 1999                    173
60                     11      Mercadian Masques                    350
61                     12          Sixth Edition                    350
110                    13                Nemesis                    143
115                    14               Prophecy                    143
116                    15               Invasion                    350
119                    16        Seventh Edition                    350
122                    17             Planeshift                    143
126                    18                Odyssey                    350
143                    19                Torment                    143
144                    20              Judgement                    143
176                    21                Legions                    145
178                    22                Scourge                    143
179                    23               Mirrodin                    306
193                    24              Darksteel                    165
197                    25             Fifth Dawn                    165
204                    26  Champions of Kamigawa                    306
208                    27  Betrayers of Kamigawa                    165
210                    28          Ninth Edition                    350
215                    29                Ravnica                    306
255                    30              Guildpact                    165
293                    31         Eighth Edition                    350
310                    32             Dissension                    180
328                    33               Coldsnap                    155
341                    34            Time Spiral                    121
342                    35            Time Spiral                    301
515                    36           Planar Chaos                    165
604                    37            Futuresight                    180
678                    38                 Lorwyn                    301
876                    39            Morningtide                    150
971                    40             Shadowmoor                    301
1162                   41               Eventide                    180
1270                   42        Shards of Alara                    249
1369                   43                Conflux                    145
1424                   44           Alara Reborn                    145
1447                   45                    M10                    249
1529                   46          Tenth Edition                    383
1662                   47               Zendikar                    249
1748                   48              Worldwake                    145
1799                   49        Rise of Eldrazi                    248
1805                   50                    M11                    249