In [317]:
import pandas as pd
import glob

# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17/*.csv")

# 2. Use list comprehension to read all files and concat them
df = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [318]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3763 entries, 0 to 3762
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           3762 non-null   float64
 1   card_name              3761 non-null   object
 2   supertype              35 non-null     object
 3   subtype_a              332 non-null    object
 4   subtype_b              3619 non-null   object
 5   subtype_c              2326 non-null   object
 6   subtype_d              1093 non-null   object
 7   subtype_e              58 non-null     object
 8   expansion_symbol       3756 non-null   object
 9   rarity                 3751 non-null   object
 10  artist_information_a   3756 non-null   object
 11  artist_information_b   91 non-null     object
 12  collectors_number      3755 non-null   object
 13  expansion_total_cards  3715 non-null   float64
 14  mana_cost              3625 non-null   object
 15  text_box               3647 non-null   object
 16  flavor_text            2803 non-null   object
 17  punch                  2006 non-null   object
 18  toughness              2003 non-null   object
 19  starting_loyalty       9 non-null      object
 20  quantity               3748 non-null   object
dtypes: float64(2), object(19)
memory usage: 617.5+ KB

In [319]:
harry_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet1.csv")

In [320]:
harry_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              211 non-null    int64
 1   card_name                 211 non-null    object
 2   supertype                 28 non-null     object
 3   subtype_a                 211 non-null    object
 4   subtype_b                 119 non-null    object
 5   subtype_c                 65 non-null     object
 6   subtype_d                 2 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          211 non-null    object
 10  rarity                    211 non-null    object
 11  artist_information_a      210 non-null    object
 12  artist_information_b      8 non-null      object
 13  collectors_number         210 non-null    object
 14  expansion_total           202 non-null    float64
 15  mana_cost                 209 non-null    object
 16  text_box                  207 non-null    object
 17  flavor_text               125 non-null    object
 18  punch                     103 non-null    object
 19  toughness                 103 non-null    object
 20  quantity                  210 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           1 non-null      object
 29  split_mana_cost           1 non-null      object
 30  split_subtype_a           1 non-null      object
 31  split_text_box            1 non-null      object
 32  loyalty_cost_a            3 non-null      float64
 33  loyalty_ability_a         3 non-null      object
 34  loyalty_cost_b            4 non-null      object
 35  loyalty_ability_b         4 non-null      object
 36  loyalty_cost_c            4 non-null      float64
 37  loyalty_ability_c         4 non-null      object
 38  starting_loyalty          4 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       1 non-null      object
 48  transform_supertype       0 non-null      float64
 49  transform_subtype_a       1 non-null      object
 50  transform_subtype_b       1 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        1 non-null      object
 53  transform_flavor_text     0 non-null      float64
 54  transform_punch           1 non-null      float64
 55  transform_toughness       1 non-null      float64
 56  modal_card_name           4 non-null      object
 57  modal_mana_cost           4 non-null      object
 58  modal_supertype           2 non-null      object
 59  modal_subtype_c           4 non-null      object
 60  modal_subtype_b           2 non-null      object
 61  modal_subtype_a           2 non-null      object
 62  modal_text_box            4 non-null      object
 63  modal_punch               2 non-null      float64
 64  modal_toughness           2 non-null      float64
 65  saga_card_name            1 non-null      object
 66  lore_counter_a            1 non-null      object
 67  lore_text_box_a           1 non-null      object
 68  lore_counter_b            1 non-null      object
 69  lore_counter_text_box     1 non-null      object
 70  saga_supertype            1 non-null      object
 71  saga_subtype_a            1 non-null      object
 72  saga_subtype_b            1 non-null      object
 73  saga_subtype_c            1 non-null      object
 74  saga_subtype_d            1 non-null      object
 75  saga_punch                1 non-null      float64
 76  saga_toughness            1 non-null      float64
dtypes: float64(31), int64(1), object(45)
memory usage: 127.1+ KB

In [321]:
harry_binder = harry_binder.drop(columns='subtype_d.1')

In [322]:
harry_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [323]:
spencer_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet2.csv")

In [324]:
spencer_binder

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_d.1,subtype_e,expansion_symbol,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,3933,Angel's Grace,NaN,Instant,NaN,NaN,NaN,NaN,NaN,Time Spiral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3934,Chronosavant,NaN,Creature,Giant,NaN,NaN,NaN,NaN,Time Spiral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3935,Mangara of Corondor,Legendary,Creature,Human,Wizard,NaN,NaN,NaN,Time Spiral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3936,Opal Guardian,NaN,Enchantment,NaN,NaN,NaN,NaN,NaN,Time Spiral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3937,Heroes Remembered,NaN,Sorcery,NaN,NaN,NaN,NaN,NaN,Time Spiral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,4104,Kher Keep,Legendary,Land,NaN,NaN,NaN,NaN,NaN,Time Spiral,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,4105,Contested War Zone,NaN,Land,NaN,NaN,NaN,NaN,NaN,Mirrodin Besieged,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,4106,Sunpetal Grove,NaN,Land,NaN,NaN,NaN,NaN,NaN,M12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,4107,Nephalia Drownyard,NaN,Land,NaN,NaN,NaN,NaN,NaN,Innistrad,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,4108,Alchemist's Refuge,NaN,Land,NaN,NaN,NaN,NaN,NaN,Avacyn Restored,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [325]:
spencer_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              176 non-null    int64
 1   card_name                 176 non-null    object
 2   supertype                 16 non-null     object
 3   subtype_a                 176 non-null    object
 4   subtype_b                 111 non-null    object
 5   subtype_c                 56 non-null     object
 6   subtype_d                 3 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          176 non-null    object
 10  rarity                    176 non-null    object
 11  artist_information_a      169 non-null    object
 12  artist_information_b      5 non-null      object
 13  collectors_number         176 non-null    object
 14  expansion_total           176 non-null    int64
 15  mana_cost                 170 non-null    object
 16  text_box                  168 non-null    object
 17  flavor_text               96 non-null     object
 18  punch                     93 non-null     object
 19  toughness                 93 non-null     object
 20  quantity                  171 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           0 non-null      float64
 29  split_mana_cost           0 non-null      float64
 30  split_subtype_a           0 non-null      float64
 31  split_text_box            0 non-null      float64
 32  loyalty_cost_a            8 non-null      float64
 33  loyalty_ability_a         8 non-null      object
 34  loyalty_cost_b            8 non-null      object
 35  loyalty_ability_b         8 non-null      object
 36  loyalty_cost_c            8 non-null      float64
 37  loyalty_ability_c         8 non-null      object
 38  starting_loyalty          8 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       4 non-null      object
 48  transform_supertype       3 non-null      object
 49  transform_subtype_a       4 non-null      object
 50  transform_subtype_b       3 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        4 non-null      object
 53  transform_flavor_text     2 non-null      object
 54  transform_punch           4 non-null      float64
 55  transform_toughness       4 non-null      float64
 56  modal_card_name           0 non-null      float64
 57  modal_mana_cost           0 non-null      float64
 58  modal_supertype           0 non-null      float64
 59  modal_subtype_c           0 non-null      float64
 60  modal_subtype_b           0 non-null      float64
 61  modal_subtype_a           0 non-null      float64
 62  modal_text_box            0 non-null      float64
 63  modal_punch               0 non-null      float64
 64  modal_toughness           0 non-null      float64
 65  saga_card_name            0 non-null      float64
 66  lore_counter_a            0 non-null      float64
 67  lore_text_box_a           0 non-null      float64
 68  lore_counter_b            0 non-null      float64
 69  lore_counter_text_box     0 non-null      float64
 70  saga_supertype            0 non-null      float64
 71  saga_subtype_a            0 non-null      float64
 72  saga_subtype_b            0 non-null      float64
 73  saga_subtype_c            0 non-null      float64
 74  saga_subtype_d            0 non-null      float64
 75  saga_punch                0 non-null      float64
 76  saga_toughness            0 non-null      float64
dtypes: float64(49), int64(2), object(26)
memory usage: 106.0+ KB

In [326]:
spencer_binder = spencer_binder.drop(columns='subtype_d.1')

In [327]:
spencer_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [328]:
rise_of_eldrazi = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet3.csv")

In [329]:
rise_of_eldrazi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           130 non-null    int64
 1   card_name              130 non-null    object
 2   supertype              1 non-null      object
 3   subtype_a              4 non-null      object
 4   subtype_b              129 non-null    object
 5   subtype_c              91 non-null     object
 6   subtype_d              46 non-null     object
 7   subtype_e              0 non-null      float64
 8   expansion_symbol       130 non-null    object
 9   rarity                 130 non-null    object
 10  artist_information_a   130 non-null    object
 11  artist_information_b   6 non-null      object
 12  collectors_number      130 non-null    int64
 13  expansion_total_cards  130 non-null    int64
 14  mana_cost              129 non-null    object
 15  text_box               127 non-null    object
 16  flavor_text            99 non-null     object
 17  punch                  74 non-null     float64
 18  toughness              74 non-null     float64
 19  starting_loyalty       0 non-null      float64
 20  quantity               130 non-null    int64
dtypes: float64(4), int64(4), object(13)
memory usage: 21.5+ KB

In [330]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,artist_information_b,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,14,248,{2}{W},Flash\nWhen Affa Guard Hound enters the battle...,"Once a welcoming hub for explorers, Affa becam...",2.0,2.0,NaN,2
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,35,248,{2}{W},Enchant creature\nWhenever enchanted creature ...,"""If destiny's champions have arisen to fight t...",NaN,NaN,NaN,4
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,37,248,{4}{W},Enchant creature\nEnchanted creature gets +3/+...,NaN,NaN,NaN,NaN,1
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,...,NaN,45,248,{4}{W},"Defender, flying",The kor's most righteous dead are given the gr...,4.0,5.0,NaN,2
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,48,248,{2}{W},You gain 2 life. Then if you have more life th...,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,228,248,NaN,"{T}, Sacrifice Evolving Wilds: Search your lib...","Every wordl is an organism, able to grow new l...",NaN,NaN,NaN,1
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,35,383,{6}{W}{W}{W},"Flying\nAt the beginning of your upkeep, you m...","""You have not died until I consent.""",4.0,6.0,NaN,1
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,189,383,{3}{R}{R},Beacon of Destruction deals 5 damage to target...,The Great Furnace's blessing is a spectacular ...,NaN,NaN,NaN,1
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,50,383,{W},Flying (This creature can't be blocked except ...,"Its eye the glaring sun, its cry the keening w...",1.0,1.0,NaN,3
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,Gabor Szikszai,213,383,{1}{R},Incinerate deals 3 damage to target creature o...,"""Yes, I think 'toast' is an appropriate descri...",NaN,NaN,NaN,4

In [331]:
import numpy as np
rise_of_eldrazi[['flip_card_name', 'flip_subtype_a', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch', 'flip_toughness', 'split_card_name', 'split_mana_cost', 'split_subtype_a', 'split_text_box', 'loyalty_cost_a', 'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b', 'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty', 'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch', 'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b', 'leveler_tier_b_punch', 'leveler_tier_b_toughness', 'transform_card_name', 'transform_supertype', 'transform_subtype_a', 'transform_subtype_b', 'transform_subtype_c', 'transform_text_box', 'transform_flavor_text', 'transform_punch', 'transform_toughness', 'modal_card_name', 'modal_mana_cost', 'modal_supertype', 'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a', 'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name', 'lore_counter_a', 'lore_text_box_a', 'lore_counter_b', 'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a', 'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch', 'saga_toughness']] = np.nan

In [332]:
rise_of_eldrazi.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity', 'flip_card_name',
       'flip_subtype_a', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d',
       'flip_punch', 'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness'],
      dtype='object')

In [333]:
rise_of_eldrazi = rise_of_eldrazi[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name',
       'flip_subtype_a', 'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d',
       'flip_punch', 'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [334]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [335]:
pd.concat([df, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [336]:
collection = pd.concat([df, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

In [337]:
collection

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [338]:
collection.tail()

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [339]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [340]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [341]:
# Rows 2009 and 2375 are completely empty, this was likely a data entry error
collection[collection.loc[:, 'card_name':'quantity'].isna().all(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
2009,3593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2375,912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [342]:
# Not to worry, I can drop these two rows just remember to re-index the permanent_id column
collection = collection.drop([2009, 2375])

In [343]:
#collection['permanent_id'] = range(1, len(collection) +1)

In [344]:
collection[collection['artist_information_a'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
378,379.0,Suq'Ata Lancer,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Timeshifted Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,380.0,Tectonic Fiend,NaN,NaN,Creature,Elemental,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2109,3690.0,Cemetery Reaper,NaN,NaN,Creature,Zombie,NaN,NaN,M12,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3149,1685.0,Territorial Baloth,NaN,NaN,Creature,Beast,NaN,NaN,Zendikar,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3879,4049.0,Curse of Stalked Prey,NaN,Enchantment,Aura,Curse,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,4050.0,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3881,4051.0,Stormkirk Noble,NaN,Creature,Vampire,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3882,4052.0,Hellrider,NaN,Creature,Devil,NaN,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3883,4053.0,Markov Blademaster,NaN,Creature,Vampire,Warrior,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3884,4054.0,"Gisela, Blade of Goldnight",Legendary,Creature,Angel,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3885,4055.0,Hound of Griselbrand,NaN,Creature,Elemental,Hound,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [345]:
collection.at[378, 'artist_information_a'] = 'Jeff Miracola'
collection.at[379, 'artist_information_a'] = 'Mark Tedin'
collection.at[2109, 'artist_information_a'] = 'Dave Allsop'
collection.at[3149, 'artist_information_a'] = 'Jesper Ejsing'
collection.at[3879, 'artist_information_a'] = 'Christopher Moeller'
collection.at[3880, 'artist_information_a'] = 'David Rapoza'
collection.at[3881, 'artist_information_a'] = 'James Ryman'
collection.at[3882, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3883, 'artist_information_a'] = 'Jana Schirmer'
collection.at[3883, 'artist_information_b'] = 'Johannes Voss'
collection.at[3884, 'artist_information_a'] = 'Jason Chan'
collection.at[3885, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3948, 'artist_information_a'] = 'Christopher Moeller'

In [374]:
collection[collection['expansion_symbol'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1993,3577.0,Brushland,NaN,NaN,Land,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [347]:
collection.loc[1757, ['subtype_b', 'subtype_c', 'expansion_symbol', 'rarity', 'artist_information_a', 'collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'punch', 'toughness', 'quantity']] = ['Creature', 'Ooze', 'M12', 'Uncommon', 'Karl Kopinski', 161, 249, '{3}{G}{G}', 'Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) When Acidic Slime enters the battlefield, destroy target artifact, enchantment, or land.', 2, 2, 1]

In [348]:
collection.iloc[[1757]]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1757,3378.0,Acidic Slime,NaN,NaN,Creature,Ooze,NaN,NaN,M12,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [349]:
collection.loc[1598, ['subtype_b', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', 'Fourth Edition', 'Uncommon', 118, 378, '{1}{B}', 'Take target creature from any graveyard and put it directly into play under your control with -1/-0. Treat this creature as though it were just summoned. If Animate Dead is removed, bury the creature in its owner\'s graveyard.', 1]

In [350]:
collection.iloc[[1598]]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1598,3219.0,Animate Dead,NaN,NaN,Enchantment,Dead,Creature,NaN,Fourth Edition,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [351]:
collection.loc[1599, ['subtype_b', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', 'Revised Edition', 'Uncommon', 93, 306, '{1}{B}', 'Enchant creature card in a graveyard\nWhen this Aura enters, if it\'s on the battlefield, it loses "enchant creature card in a graveyard" and gains "enchant creature put onto the battlefield with this Aura." Return enchanted creature card to the battlefield under your control and attach this Aura to it. When this Aura leaves the battlefield, that creature\'s controller sacrifices it.', 1]

In [352]:
collection.loc[[1599]]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1599,3220.0,Animate Dead,NaN,NaN,Enchantment,Dead,Creature,NaN,Revised Edition,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [353]:
collection.loc[1600, ['subtype_b', 'expansion_symbol', 'rarity', 'artist_information_a','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Artifact', 'Revised Edition', 'Rare', 'Mark Tedin', 280, 306, '{2}', 'A player may not untap more than one land during the untap phase of each of his or her turns.', 1]

In [354]:
collection.loc[[1600]]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1600,3221.0,Winter Orb,NaN,Artifact,Artifact,NaN,NaN,NaN,Revised Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [355]:
collection.loc[4280, ['card_name', 'subtype_b', 'expansion_symbol', 'rarity', 'artist_information_a', 'collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Winter Orb', 'Artifact', 'Fourth Edition', 'Rare', 'Mark Tedin', 280, 306, '{2}', 'No player may untap more than one land during his or her untap phase.', 2]

In [356]:
collection.loc[[4280]]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
4280,NaN,Winter Orb,NaN,NaN,Artifact,NaN,NaN,NaN,Fourth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [376]:
collection.loc[1993, ['card_name', 'subtype_b', 'expansion_symbol', 'rarity', 'artist_information', 'collectors_number', 'expansion_total_cards', 'text_box', 'quantity']] = ['Brushland', 'Land', 'Fifth Edition', 'Rare', 'Tom Wänerstrand', 414, 449, '{T}: Add one colorless mana to your mana pool.\n{T}: Add {G} or {W} to your mana pool.\nBrushland deals 1 damage to you.', 1]

In [378]:
collection.loc[[1993]]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness,artist_information
1993,3577.0,Brushland,NaN,NaN,Land,NaN,NaN,NaN,Fifth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tom Wänerstrand

In [357]:

collection[collection['card_name'].isin(['Soltari Priest', 'Benalish Cavalry', 'Knight of the Holy Nimbus', 'Serra Avenger', 'Calciderm', 'Shade of Troikair', 'Stonecloaker', 'Flagstones of Troikair', 'Fortify', 'Griffin Guide', 'Temporal Isolation', 'Mana Tithe', 'Honorable Passage', 'Cloudchaser Kestrel', 'Gemstone Caverns', 'Magus of the Disk', 'Pentarch Paladin', 'Sunlance'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
351,352.0,Griffin Guide,NaN,NaN,Enchantment,Aura,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,402.0,Benalish Cavalry,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,412.0,Temporal Isolation,NaN,NaN,Enchantment,Aura,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
471,472.0,Knight of the Holy Nimbus,NaN,NaN,Creature,Human,Rebel,Knight,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,595.0,Shade of Troikair,NaN,NaN,Creature,Shade,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,597.0,Sunlance,NaN,NaN,Sorcery,NaN,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1622,3243.0,Serra Avenger,NaN,NaN,Creature,Angel,NaN,NaN,Time Spiral,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,3635.0,Mana Tithe,NaN,NaN,Instant,NaN,NaN,NaN,Strixhaven: Mystical Archive,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [358]:

collection[collection['card_name'].isin(['Muscle Sliver', 'Sinew Sliver', 'Crystalline Sliver', 'Gemhide Sliver', 'Hibernation Sliver', 'Winged Sliver', 'Harmonic Sliver', 'Quick Sliver', 'Sliver Overlord', 'Sliver Legion', 'Aether Vial', 'Swords to Plowshares', 'Brainstorm', 'Cavern of Souls', 'City of Brass', 'Reflecting Pool', 'Mutavault', 'Forbidden Orchard'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
451,452.0,Gemhide Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,596.0,Sinew Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1767,3388.0,Brainstorm,NaN,NaN,Instant,NaN,NaN,NaN,Commander: Political Puppets,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,3585.0,Reflecting Pool,NaN,NaN,Land,NaN,NaN,NaN,Shadowmoor,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2091,3672.0,Brainstorm,NaN,NaN,Instant,NaN,NaN,NaN,Strixhaven: Mystical Archive,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [359]:
# This is a closer look at all of the slivers
collection[collection[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].apply(lambda x: x.str.contains('sliver', case=False, na=False)).any(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
353,354.0,Quilled Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,374.0,Firewake Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
385,386.0,Might Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,400.0,Venser's Sliver,NaN,Artifact,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,422.0,Screeching Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
441,442.0,Bonesplitter Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,452.0,Gemhide Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457,458.0,Spinneret Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474,475.0,Quilled Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
477,478.0,Telekinetic Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,481.0,Vampiric Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,488.0,Sidewinder Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
488,489.0,Watcher Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,496.0,Shadow Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,500.0,Basal Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
501,502.0,Mindlash Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,511.0,Two-Headed Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Time Spiral,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,524.0,Dormant Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
532,533.0,Poultice Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,543.0,Synchronous Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
551,552.0,Spitting Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552,553.0,Battering Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
568,569.0,Reflex Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
580,581.0,Frenetic Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,596.0,Sinew Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Planar Chaos,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,625.0,Lymph Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
653,654.0,Virulent Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,671.0,Mesmeric Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,675.0,Frenzy Sliver,NaN,NaN,Creature,Sliver,NaN,NaN,Futuresight,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3775,3945.0,Pulmonic Sliver,NaN,Creature,Sliver,NaN,NaN,NaN,Time Spiral,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [360]:
collection[collection['card_name'].isin(['Inkmoth Nexus', 'Ichorclaw Myr', 'Phyrexian Crusader', 'Plague Stinger', 'Whispering Specter', 'Despise', 'Dismember', 'Gitaxian Probe', 'Mutagenic Growth', 'Virulent Wound', 'Go for the Throat', 'Grasp of Darkness', 'Marrow Shards', 'Mortarpod', 'Phyrexian Vatmother', 'Piston Sledge'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1672,3293.0,Phyrexian Crusader,NaN,NaN,Creature,Zombie,Knight,NaN,Mirrodin Besieged,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1673,3294.0,Go for the Throat,NaN,NaN,Instant,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1677,3298.0,Gitaxian Probe,NaN,NaN,Sorcery,NaN,NaN,NaN,New Phyrexia,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1680,3301.0,Dismember,NaN,NaN,Instant,NaN,NaN,NaN,New Phyrexia,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3347,1883.0,Mortarpod,NaN,Artifact,Equipment,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3351,1887.0,Piston Sledge,NaN,Artifact,Equipment,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3432,1968.0,Go for the Throat,NaN,NaN,Instant,NaN,NaN,NaN,Mirrodin Besieged,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3438,1974.0,Virulent Wound,NaN,NaN,Instant,NaN,NaN,NaN,Mirrodin Besieged,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3460,1996.0,Ichorclaw Myr,NaN,Artifact,Creature,Myr,NaN,NaN,Scars of Mirrodin,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3515,2051.0,Marrow Shards,NaN,NaN,Instant,NaN,NaN,NaN,New Phyrexia,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3525,2061.0,Despise,NaN,NaN,Sorcery,NaN,NaN,NaN,New Phyrexia,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3567,2103.0,Gitaxian Probe,NaN,NaN,Sorcery,NaN,NaN,NaN,New Phyrexia,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3595,2131.0,Mutagenic Growth,NaN,NaN,Instant,NaN,NaN,NaN,New Phyrexia,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [361]:
collection[collection['card_name'].isin(['Dissipate', 'Feeling of Dread', 'Think Twice', 'Thought Scour', 'Devastation Tide', 'Entreat the Angels', 'Temporal Mastery', 'Terminus', 'Tamiyo, the Moon Sage', 'Evolving Wilds', "Angel's Mercy", 'Cathedral Sanctifier', 'Geist of Saint Traft', 'Midnight Haunting', 'Snapcaster Mage'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
688,2309.0,Dissipate,NaN,NaN,Instant,NaN,NaN,NaN,Innistrad,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
832,2453.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,2533.0,Feeling of Dread,NaN,NaN,Instant,NaN,NaN,NaN,Innistrad,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,2618.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,Avacyn Restored,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,2621.0,Cathedral Sanctifier,NaN,NaN,Creature,Human,Cleric,NaN,Avacyn Restored,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1147,2768.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,M13,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1589,3210.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Commander: Political Puppets,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1753,3374.0,Geist of Saint Traft,Legendary,NaN,Creature,Spirit,Cleric,NaN,Innistrad,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1755,3376.0,Thought Scour,NaN,NaN,Instant,NaN,NaN,NaN,Dark Ascension,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1762,3383.0,"Tamiyo, the Moon Sage",NaN,NaN,Planeswalker,Tamiyo,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1763,3384.0,Terminus,NaN,NaN,Sorcery,NaN,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2933,1469.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M10,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3762,2298.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3801,3971.0,Entreat the Angels,NaN,Sorcery,NaN,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3826,3996.0,Devastation Tide,NaN,Sorcery,NaN,NaN,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3831,4001.0,"Tamiyo, the Moon Sage",NaN,Planeswalker,Tamiyo,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4275,4234.0,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [362]:
collection[collection['card_name'].isin(['Ornithopter', 'Memnite', 'Frogmite', 'Arcbound Ravager', 'Master of Etherium', 'Cranial Plating', 'Thoughtcast', 'Thirst for Knowledge', 'Thoughtseize', 'Duress', 'Springleaf Drum', 'Seat of the Synod', 'Vault of Whispers', 'Darksteel Citadel', 'Blinkmoth Nexus'])]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1613,3234.0,Darksteel Citadel,NaN,Artifact,Land,NaN,NaN,NaN,Darksteel,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1630,3251.0,Springleaf Drum,NaN,Artifact,NaN,NaN,NaN,NaN,Lorwyn,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1659,3280.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1661,3282.0,Ornithopter,NaN,Artifact,Creature,Thopter,NaN,NaN,M10,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1668,3289.0,Memnite,NaN,Artifact,Creature,Construct,NaN,NaN,Scars of Mirrodin,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1759,3380.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,M13,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981,3602.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,Strixhaven: Mystical Archive,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2962,1498.0,Duress,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3291,1827.0,Memnite,NaN,Artifact,Creature,Construct,NaN,NaN,Scars of Mirrodin,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [363]:
collection

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4276,4235.0,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4277,4236.0,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4278,4237.0,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4279,4238.0,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4280,NaN,Winter Orb,NaN,NaN,Artifact,NaN,NaN,NaN,Fourth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [364]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [365]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [366]:
collection[collection['expansion_total_cards'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
6,7.0,Resistance Fighter,NaN,NaN,Creature,Soldier,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8.0,Fireblast,NaN,NaN,Instant,NaN,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9.0,Lichenthrope,NaN,NaN,Creature,Lichenthrope,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10.0,Quirion Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11.0,Stampeding Wildebeests,NaN,NaN,Creature,Wildebeests,NaN,NaN,Visions,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12.0,Lava Axe,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13.0,Volcanic Hammer,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14.0,Contemplation,NaN,NaN,Enchantment,NaN,NaN,NaN,Stronghold,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15.0,Soul Warden,NaN,NaN,Creature,Ceric,NaN,NaN,Exodus,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16.0,Talas Merchant,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17.0,Air Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18.0,Touch of Brilliance,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19.0,Talas Researcher,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20.0,False Summoning,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21.0,Talas Air Ship,NaN,NaN,Creature,Ship,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22.0,Mystic Denial,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23.0,Talas Scout,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24.0,Apprentice Sorcerer,NaN,NaN,Creature,Wizard,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25.0,Exhaustion,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26.0,Talas Explorer,NaN,NaN,Creature,Merchant,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27.0,Time Ebb,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28.0,Talas Warrior,NaN,NaN,Creature,Pirate,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29.0,Monstrous Growth,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30.0,Alluring Scent,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31.0,Wild Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32.0,Sylvan Basalisk,NaN,NaN,Creature,Basilisk,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33.0,River Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34.0,Norwood Riders,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35.0,Norwood Ranger,NaN,NaN,Creature,Elf,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36.0,Norwood Archers,NaN,NaN,Creature,Elves,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37.0,Golden Bear,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38.0,Bear Cub,NaN,NaN,Creature,Bear,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39.0,Ironhoof Ox,NaN,NaN,Creature,Ox,NaN,NaN,Portal 2,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40.0,Angel of Fury,NaN,NaN,Creature,Angel,NaN,NaN,Portal 2,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41.0,Righteous Charge,NaN,NaN,Sorcery,NaN,NaN,NaN,Portal 2,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,3574.0,"Ishgard, the Holy See",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991,3575.0,"Lindblum, Industrial Regency",NaN,NaN,Land,Town,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,3577.0,Brushland,NaN,NaN,Land,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028,3612.0,Breath of Life,NaN,NaN,Sorcery,NaN,NaN,NaN,Starter 2000,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2097,3678.0,"Jill, Shiva's Dominant",Legendary,NaN,Creature,Human,Noble,Warrior,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,3721.0,The Darkness Crystal,Legendary,Artifact,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,NaN,"Rowan, Scholar of Sparks",Legendary,NaN,Planeswalker,Rowan,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3939,3722.0,"Rowan, Scholar of Sparks",Legendary,Planeswalker,Rowan,NaN,NaN,NaN,Strixhaven,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3976,3759.0,"Raubahn, Bull of Ala Mhigo",Legendary,Creature,Human,Warrior,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4054,3837.0,Summoner's Grimoire,NaN,Artifact,Equipment,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4055,3838.0,A Realm Reborn,NaN,Enchantment,NaN,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4100,3883.0,The Regalia,Legendary,Artifact,Vehicle,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4101,3884.0,"Ultima, Origin of Oblivion",Legendary,Creature,God,NaN,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4145,3928.0,"Sin, Spira's Punishment",Legendary,Creature,Leviathan,Avatar,NaN,NaN,Universes Beyond: Final Fantasy,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4146,3929.0,"Joshua, Phoenix's Dominant",Legendary,Creature,Human,Noble,Wizard,NaN,Universes Beyond: Final Fantasy,Rare,...,Rising Flames — Phoenix deals 2 damage to each...,III,Flames of Rebirth — Return any number of targe...,Legendary,Enchantment,Creature,Saga,Phoenix,4.0,4.0

In [367]:
collection[collection['expansion_symbol'] == 'Modern Masters']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
1314,2935.0,Etched Oracle,NaN,Artifact,Creature,Wizard,NaN,NaN,Modern Masters,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1315,2936.0,Electrolyze,NaN,NaN,Instant,NaN,NaN,NaN,Modern Masters,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1316,2937.0,Grinning Ignus,NaN,NaN,Creature,Elemental,NaN,NaN,Modern Masters,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1317,2938.0,Otherworldly Journey,NaN,NaN,Instant,Arcane,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1318,2939.0,Dampen Thought,NaN,NaN,Instant,Arcane,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1319,2940.0,Mothdust Changeling,NaN,NaN,Creature,Shapeshifter,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,2941.0,Petals of Insight,NaN,NaN,Sorcery,Arcane,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321,2942.0,Absorb Vis,NaN,NaN,Sorcery,NaN,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1322,2943.0,Warren Pilferers,NaN,NaN,Creature,Goblin,Rogue,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1323,2944.0,Rift Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1324,2945.0,Thundering Giant,NaN,NaN,Creature,Giant,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1325,2946.0,Torrent of Stone,NaN,NaN,Instant,Arcane,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1326,2947.0,Kodama's Reach,NaN,NaN,Sorcery,Arcane,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1327,2948.0,Nantuko Shaman,NaN,NaN,Creature,Insect,Shaman,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328,2949.0,Search for Tomorrow,NaN,NaN,Sorcery,NaN,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329,2950.0,Thallid,NaN,NaN,Creature,Fungus,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1330,2951.0,Thallid Shell-Dweller,NaN,NaN,Creature,Fungus,NaN,NaN,Modern Masters,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2120,3701.0,Bridge from Below,NaN,NaN,Enchantment,NaN,NaN,NaN,Modern Masters,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [368]:
collection.loc[collection['expansion_symbol'] == 'Visions', 'expansion_total_cards'] = 167
collection.loc[collection['expansion_symbol'] == 'Portal', 'expansion_total_cards'] = 222
collection.loc[collection['expansion_symbol'] == 'Stronghold', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Exodus', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Portal 2', 'expansion_total_cards'] = 165
collection.loc[collection['expansion_symbol'] == 'Universes Beyond: Final Fantasy', 'expansion_total_cards'] = 309
collection.loc[collection['expansion_symbol'] == 'Starter 2000', 'expansion_total_cards'] = 20
collection.loc[collection['expansion_symbol'] == 'Strixhaven', 'expansion_total_cards'] = 393
collection.loc[collection['expansion_symbol'] == 'Morningtide', 'expansion_total_cards'] = 150

In [369]:
collection['collectors_number'] = collection['collectors_number'].str.replace(r"[a-zA-Z]", "", regex=True)

In [ ]:
collection.info()

In [ ]:
collection['expansion_total_cards'] = collection['expansion_total_cards'].astype(int)

In [ ]:
collection[collection['expansion_symbol'] == 'Lorwyn'].sort_values(by='collectors_number')

In [ ]:
import mysql.connector
try:
    # 1. Establish the connection
    db_connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="password",
        database="trading_card_collection"
    )

    if db_connection.is_connected():
        print("Successfully connected to the database")

    # 2. Create a cursor to execute SQL queries
    cursor = db_connection.cursor()
    cursor.execute("SELECT DATABASE();")
    record = cursor.fetchone()
    print("You're connected to the database:", record)

except mysql.connector.Error as err:
    print(f"Error: {err}")

finally:
    # 3. Always close the connection
    if 'db-connection' in locals() and db_connection.is_connected():
        cursor.close()
        db_connection.close()
        print("MySQL connection is closed")

In [ ]:
# 1. JUNCTION TABLE
# for each row, iterate through subtype columns
# if the subtype is nan, do nothing
# if the subtype is valid, add it to an array
# iterate through the array and query the parent table for the matching index
# insert the id and subtype into the junction table

In [ ]:
cursor.execute("CREATE TABLE permanent_junction_subtype (permanent_id INT,subtype_id INT,PRIMARY KEY (permanent_id, subtype_id));")

In [ ]:
row_subtypes = df.iloc[1059, 3:8].to_numpy()

In [ ]:
row_subtypes

In [ ]:
df.iloc[:, 1:1822] = df.iloc[:, 1:50].fillna(0)

In [ ]:
import math
import numpy as np

for i, row in enumerate(df, start=1):
    permanent_id = df.iloc[i, 1]
    subtypes = df.iloc[i, 3:8].to_numpy()
    for type in subtypes:
        #if math.isnan(type):
        if type == "":
            continue
        else:
            cursor.execute("SELECT subtype_id FROM subtype WHERE subtype = %s", (type))
            subtype_id = cursor.fetchone()[0]
            cursor.execute("INSERT INTO permanent_junction_subtype (permnent_id, subtype_id) VALUES (%s, %s)" (permanent_id, subtype_id))
            connection.commit()

In [ ]:
import pandas as pd
import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_database"
)
cursor = db.cursor()

target_cols = ['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']

for index, row in df.iterrows():
    for col in target_cols:
        val = row[col]

        if pd.isna(val):
            continue

        query_parent = "SELECT subtype_id FROM subtype WHERE subtype = %s"
        cursor.execute(query_parent, (val,))
        result = cursor.fetchone()

        if result:
            parent_id = result[0]
            insert_child = "INSERT INTO child_table (parent_id, df_index) VALUES (%s, %s)"
            cursor.execute(insert_child, (parent_id, index))

db.commit()
cursor.close()
db.close()

In [ ]:
# 2. PARENT TABLE
# create a list of all unique subtypes in the dataframe
# remove any instances of nan or blank subtypes
# find the longest subtype
# create table declaring subtype as VARCHAR() use the length of the longest subtype as the parameter for varchar

In [40]:
df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

array(['Enchantment', 'Aura', 'Creature', 'Illusion', 'Artifact',
       'Soldier', 'Instant', 'Lichenthrope', 'Elf', 'Wildebeests',
       'Sorcery', 'Ceric', 'Merchant', 'Elemental', 'Wizard', 'Ship',
       'Pirate', 'Ox', 'Basilisk', 'Bear', 'Elves', 'Angel', 'Cleric',
       'Imp', 'Viashino', 'Wolf', 'Knight', 'Griffin', 'Thief', 'Zombie',
       'Rat', 'Rebel', 'Pegasus', 'Bird', 'Drake', 'Thrull', 'Skeleton',
       'Horror', 'Ghost', 'Minotaur', 'Tiger', 'Wall', 'Spider', 'Cat',
       'Warrior', 'Wurm', 'Elephant', 'Golem', 'Mercenary', 'Spellshaper',
       'Land', 'Beast', 'Kavu', 'Nomad', 'Mystic', 'Hound', 'Insect',
       'Druid', 'Incarnation', 'Nightmare', 'Crab', 'Barbarian',
       'Centaur', 'Spirit', 'Equipment', 'Troll', 'Human', 'Shaman',
       'Arcane', 'Monk', 'Turtle', 'Goblin', 'Advisor', 'Dryad',
       'Assassin', 'Ogre', 'Berserker', 'Rogue', 'Archer', 'Giant',
       'Frog', 'Mutant', 'Faerie', 'Scout', 'Snake', 'Plant', 'Sliver',
       'Eye', 'Gargoyle', 'Orgg', 'Avatar', 'Fungus', 'Kithkin',
       'Merfolk', 'Gorgon', 'Leech', 'Kor', 'Encahntment', 'Serpent',
       'Homarid', 'Orc', 'Shapeshifter', 'Shade', 'Wraith', 'Cyclops',
       'Tribal', 'Forest', 'Ouphe', 'Myr', 'Vampire', 'Bat', 'Curse',
       'Werewolf', 'Treefolk', 'Juggernaut', 'Construct', 'Fox',
       'Homunculus', 'Devil', 'Boar', 'Scarecrow', 'Elk', 'Demon',
       'Lizard', 'Kraken', 'Gate', 'Fish', 'Leviathan', 'Jellyfish',
       'Hommunculus', 'Vedalken', 'Crocodile', 'Eldrazi', 'Drone', 'Ally',
       'Planeswalker', 'Venser', 'Sphinx', 'Slith', 'Worm', 'Koth',
       'Thopter', 'Enchatment', 'Dragon', 'Encahantment', 'Enchant',
       'Dead', "Urza's", 'Jace', 'Praetor', 'Ooze', 'Archon', 'Rhino',
       'Gideon', 'Tamiyo', 'Mana Source', 'Ajani', 'Desert', 'Lesson',
       'Dog', 'Djinn', 'Warlock', 'Specter', 'Fog', 'Dwarf', 'Squirrel',
       'Relic', 'Town', 'Noble', 'Rowan', 'Instinct', 'Island', 'Hag',
       'Noggle', 'Gobiln', 'Artificer', 'Unicorn', 'Antelope', 'Funugs',
       'Trap', 'Surrakar', 'Horse', 'Gremlin', 'Hellion', 'Siren',
       'Dragon ', 'Salamander', 'Creatue'], dtype=object)

In [41]:
subtype_arr = df[['subtype_a', 'subtype_b', 'subtype_c', 'subtype_d', 'subtype_e']].stack().dropna().unique()

In [42]:
max(subtype_arr, key=len)

'Lichenthrope'

In [43]:
len(max(subtype_arr, key=len))

12

In [15]:
longest = len(max(subtype_arr, key=len))

In [ ]:
# create a dataframe from the array of uniques

In [16]:
subtype_df = pd.DataFrame(subtype_arr)

In [17]:
subtype_df

               0
0    Enchantment
1           Aura
2       Creature
3       Illusion
4       Artifact
..           ...
131         Fish
132    Crocodile
133         Boar
134     Surrakar
135      Thopter

[136 rows x 1 columns]

In [22]:
subtype_df['subtype_id'] = range(1, len(subtype_df) + 1)

In [23]:
subtype_df

         subtype  subtype_id
0    Enchantment           1
1           Aura           2
2       Creature           3
3       Illusion           4
4       Artifact           5
..           ...         ...
131         Fish         132
132    Crocodile         133
133         Boar         134
134     Surrakar         135
135      Thopter         136

[136 rows x 2 columns]

In [19]:
subtype_df = subtype_df.rename(columns={0: 'subtype'})

In [24]:
subtype_df

         subtype  subtype_id
0    Enchantment           1
1           Aura           2
2       Creature           3
3       Illusion           4
4       Artifact           5
..           ...         ...
131         Fish         132
132    Crocodile         133
133         Boar         134
134     Surrakar         135
135      Thopter         136

[136 rows x 2 columns]

In [26]:
subtype_df = subtype_df[['subtype_id', 'subtype']]

In [27]:
subtype_df

     subtype_id      subtype
0             1  Enchantment
1             2         Aura
2             3     Creature
3             4     Illusion
4             5     Artifact
..          ...          ...
131         132         Fish
132         133    Crocodile
133         134         Boar
134         135     Surrakar
135         136      Thopter

[136 rows x 2 columns]

In [28]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="password",
    database="trading_card_collection"
)
cursor = conn.cursor()

# Create the table manually
cursor.execute("""
    CREATE TABLE IF NOT EXISTS subtype (
        subtype_id INT,
        subtype VARCHAR(%s)
    )
    """, (longest,))

In [29]:
# Prepare the data as a list of tuples
data_to_insert = [tuple(x) for x in subtype_df.values]

# SQL query with placeholders
sql = "INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)"

# Execute and commit
cursor.executemany(sql, data_to_insert)
conn.commit() # Vital: changes won't save without this

print(f"{cursor.rowcount} records inserted.")
cursor.close()
conn.close()

136 records inserted.

In [ ]:
#cursor.execute("CREATE TABLE IF NOT EXISTS subtype (subtype_id INT, subtype VARCHAR(%s) PRIMARY KEY", (longest,))

In [ ]:
#for index, subtype in enumerate(subtypes, start=1):
    #cursor.execute("INSERT INTO subtype (subtype_id, subtype) VALUES (%s, %s)" (index, subtype))

In [79]:
expansion_symbol_df = df[['expansion_symbol', 'expansion_total_cards']].drop_duplicates()

In [80]:
expansion_symbol_df

           expansion_symbol  expansion_total_cards
0                   Ice Age                    383
5                 Alliances                    144
6                   Visions                    167
11                   Portal                    222
13               Stronghold                    143
14                   Exodus                    143
15                 Portal 2                    165
41              Urza's Saga                    350
47            Urza's Legacy                    143
48             Starter 1999                    173
60        Mercadian Masques                    350
61            Sixth Edition                    350
110                 Nemesis                    143
115                Prophecy                    143
116                Invasion                    350
119         Seventh Edition                    350
122              Planeshift                    143
126                 Odyssey                    350
143                 Torment                    143
144               Judgement                    143
176                 Legions                    145
178                 Scourge                    143
179                Mirrodin                    306
193               Darksteel                    165
197              Fifth Dawn                    165
200             Fifth Dawn                     165
204   Champions of Kamigawa                    306
208   Betrayers of Kamigawa                    165
210           Ninth Edition                    350
215                 Ravnica                    306
255               Guildpact                    165
293          Eighth Edition                    350
310              Dissension                    180
328                Coldsnap                    155
341             Time Spiral                    121
342             Time Spiral                    301
395            Time Spiral                     301
422             Time Sprial                    301
515            Planar Chaos                    165
571           Planar Chaos                     165
604             Futuresight                    180
618             Futuresight                    150
678                  Lorwyn                    301
876             Morningtide                    150
971              Shadowmoor                    301
1111             Shdaowmoor                    301
1162               Eventide                    180
1232               Eventide                    108
1270        Shards of Alara                    249
1369                Conflux                    145
1424           Alara Reborn                    145
1447                    M10                    249
1510                   M10                     249
1529          Tenth Edition                    383
1662               Zendikar                    249
1748              Worldwake                    145
1750              Wordlwake                    145
1799        Rise of Eldrazi                    248
1805                    M11                    249

In [81]:
expansion_symbol_df['expansion_symbol_id'] = range(1, len(expansion_symbol_df) + 1)

In [82]:
expansion_symbol_df

           expansion_symbol  expansion_total_cards  expansion_symbol_id
0                   Ice Age                    383                    1
5                 Alliances                    144                    2
6                   Visions                    167                    3
11                   Portal                    222                    4
13               Stronghold                    143                    5
14                   Exodus                    143                    6
15                 Portal 2                    165                    7
41              Urza's Saga                    350                    8
47            Urza's Legacy                    143                    9
48             Starter 1999                    173                   10
60        Mercadian Masques                    350                   11
61            Sixth Edition                    350                   12
110                 Nemesis                    143                   13
115                Prophecy                    143                   14
116                Invasion                    350                   15
119         Seventh Edition                    350                   16
122              Planeshift                    143                   17
126                 Odyssey                    350                   18
143                 Torment                    143                   19
144               Judgement                    143                   20
176                 Legions                    145                   21
178                 Scourge                    143                   22
179                Mirrodin                    306                   23
193               Darksteel                    165                   24
197              Fifth Dawn                    165                   25
200             Fifth Dawn                     165                   26
204   Champions of Kamigawa                    306                   27
208   Betrayers of Kamigawa                    165                   28
210           Ninth Edition                    350                   29
215                 Ravnica                    306                   30
255               Guildpact                    165                   31
293          Eighth Edition                    350                   32
310              Dissension                    180                   33
328                Coldsnap                    155                   34
341             Time Spiral                    121                   35
342             Time Spiral                    301                   36
395            Time Spiral                     301                   37
422             Time Sprial                    301                   38
515            Planar Chaos                    165                   39
571           Planar Chaos                     165                   40
604             Futuresight                    180                   41
618             Futuresight                    150                   42
678                  Lorwyn                    301                   43
876             Morningtide                    150                   44
971              Shadowmoor                    301                   45
1111             Shdaowmoor                    301                   46
1162               Eventide                    180                   47
1232               Eventide                    108                   48
1270        Shards of Alara                    249                   49
1369                Conflux                    145                   50
1424           Alara Reborn                    145                   51
1447                    M10                    249                   52
1510                   M10                     249                   53
1529          Tenth Edition                    383                   54
1662               Zendikar                    249                   55
1748              Worldwake                    145                   56
1750              Wordlwake                    145                   57
1799        Rise of Eldrazi                    248                   58
1805                    M11                    249                   59

In [83]:
expansion_symbol_df = expansion_symbol_df[['expansion_symbol_id', 'expansion_symbol', 'expansion_total_cards']]

In [84]:
expansion_symbol_df

      expansion_symbol_id       expansion_symbol  expansion_total_cards
0                       1                Ice Age                    383
5                       2              Alliances                    144
6                       3                Visions                    167
11                      4                 Portal                    222
13                      5             Stronghold                    143
14                      6                 Exodus                    143
15                      7               Portal 2                    165
41                      8            Urza's Saga                    350
47                      9          Urza's Legacy                    143
48                     10           Starter 1999                    173
60                     11      Mercadian Masques                    350
61                     12          Sixth Edition                    350
110                    13                Nemesis                    143
115                    14               Prophecy                    143
116                    15               Invasion                    350
119                    16        Seventh Edition                    350
122                    17             Planeshift                    143
126                    18                Odyssey                    350
143                    19                Torment                    143
144                    20              Judgement                    143
176                    21                Legions                    145
178                    22                Scourge                    143
179                    23               Mirrodin                    306
193                    24              Darksteel                    165
197                    25             Fifth Dawn                    165
200                    26            Fifth Dawn                     165
204                    27  Champions of Kamigawa                    306
208                    28  Betrayers of Kamigawa                    165
210                    29          Ninth Edition                    350
215                    30                Ravnica                    306
255                    31              Guildpact                    165
293                    32         Eighth Edition                    350
310                    33             Dissension                    180
328                    34               Coldsnap                    155
341                    35            Time Spiral                    121
342                    36            Time Spiral                    301
395                    37           Time Spiral                     301
422                    38            Time Sprial                    301
515                    39           Planar Chaos                    165
571                    40          Planar Chaos                     165
604                    41            Futuresight                    180
618                    42            Futuresight                    150
678                    43                 Lorwyn                    301
876                    44            Morningtide                    150
971                    45             Shadowmoor                    301
1111                   46             Shdaowmoor                    301
1162                   47               Eventide                    180
1232                   48               Eventide                    108
1270                   49        Shards of Alara                    249
1369                   50                Conflux                    145
1424                   51           Alara Reborn                    145
1447                   52                    M10                    249
1510                   53                   M10                     249
1529                   54          Tenth Edition                    383
1662                   55               Zendikar                    249
1748                   56              Worldwake                    145
1750                   57              Wordlwake                    145
1799                   58        Rise of Eldrazi                    248
1805                   59                    M11                    249

In [85]:
df[df['expansion_symbol'] == 'Fifth Dawn ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
200,201,Spark Elemental,NaN,NaN,Creature,Elemental,NaN,NaN,Fifth Dawn,Common,John Avon,79,165,R,"Trample, haste\nAt end of turn, sacrifice Spar...","""Vulshok shamans summon spark elementals to bu...",3,1,NaN,5

In [86]:
df[df['expansion_symbol'] == 'Time Sprial']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
422,423,Snapback,NaN,NaN,Instant,NaN,NaN,NaN,Time Sprial,Common,Alan Pollack,78,301,1U,You may remove a blue card in your hand from t...,"""If it returns years hence, our knowledge of h...",NaN,NaN,NaN,3

In [87]:
df[df['expansion_symbol'] == 'Time Spiral ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
395,396,Terramorphic Expanse,NaN,NaN,Land,NaN,NaN,NaN,Time Spiral,Common,Dan Scott,279,301,NaN,"T, Sacrifice Terramorphic Expanse: Search your...",Take two steps north into the unsettled future...,NaN,NaN,NaN,3

In [103]:
df[df['expansion_symbol'] == 'Planar Chaos ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
571,572,Vitaspore Thallid,NaN,NaN,Creature,Fungus,NaN,NaN,Planar Chaos,Common,Christopher Moeller,141,165,1G,"At the beginning of your upkeep, put a spore c...",NaN,1,1,NaN,3
587,588,Kor Dirge,NaN,NaN,Instant,NaN,NaN,NaN,Planar Chaos,Uncommon,Alex Horley-Orlandelli,87,165,2B,All damage that would be dealt this turn to ta...,Rath's new evincar eliminated the brutish mogg...,NaN,NaN,NaN,3

In [88]:
df[(df['expansion_symbol'] == 'Futuresight') & (df['expansion_total_cards'] == 150)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
618,619,Utopia Mycon,NaN,NaN,Creature,Fungus,NaN,NaN,Futuresight,Uncommon,Anthony S. Waters,140,150,G,"At the beginning of your upkeep, put a spore c...",NaN,0,2,NaN,1

In [89]:
df[df['expansion_symbol'] == 'Shdaowmoor']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1111,1112,Firespout,NaN,NaN,Sorcery,NaN,NaN,NaN,Shdaowmoor,Uncommon,Jeff Miracola,205,301,2{R/G},Firespout deals 3w damage to each creature wit...,NaN,NaN,NaN,NaN,4.0

In [90]:
df[(df['expansion_symbol'] == 'Eventide') & (df['expansion_total_cards'] == 108)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1232,1233,Noggle Hedge-Mage,NaN,NaN,Creature,Noggle,Wizard,NaN,Eventide,Uncommon,Rebecca Guay,27,108,2U,Target player draws a card.\nRetrace (You may ...,Oona grants her favored subjects a dream from ...,NaN,NaN,NaN,4.0

In [91]:
df[df['expansion_symbol'] == 'Wordlwake']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1750,1751,Loam Lion,NaN,NaN,Creature,Cat,NaN,NaN,Wordlwake,Uncommon,Daniel Ljunggren,13,145,W,Loam Lion gets +1/+2 as long as you control a ...,"In Zendikar, today's grassland could be tomorr...",1,1.0,NaN,1

In [92]:
df[df['expansion_symbol'] == 'M10 ']

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,artist_information,collectors_number,expansion_total_cards,mana_cost,text_box,flavor_text,punch,toughness,starting_loyalty,quantity
1510,1511,Panic Attack,NaN,NaN,Sorcery,NaN,NaN,NaN,M10,Common,Izzy,150,249,2R,Up to three target creatures can't block this ...,"""What do they see in the throes of panic? I'm ...",NaN,NaN,NaN,2

In [93]:
df.loc[200, 'expansion_symbol'] = 'Fifth Dawn'

In [94]:
df.loc[422, 'expansion_symbol'] = 'Time Spiral'

In [95]:
df.loc[395, 'expansion_symbol'] = 'Time Spiral'

In [96]:
df.loc[618, 'expansion_total_cards'] = 180

In [106]:
df.loc[571, 'expansion_symbol'] = 'Planar Chaos'

In [107]:
df.loc[587, 'expansion_symbol'] = 'Planar Chaos'

In [97]:
df.loc[1111, 'expansion_symbol'] = 'Shadowmoor'

In [98]:
df.loc[1232, 'expansion_total_cards'] = 180

In [99]:
df.loc[1750, 'expansion_symbol'] = 'Worldwake'

In [100]:
df.loc[1510, 'expansion_symbol'] = 'M10'

In [109]:
df[['expansion_symbol', 'expansion_total_cards']].drop_duplicates()

           expansion_symbol  expansion_total_cards
0                   Ice Age                    383
5                 Alliances                    144
6                   Visions                    167
11                   Portal                    222
13               Stronghold                    143
14                   Exodus                    143
15                 Portal 2                    165
41              Urza's Saga                    350
47            Urza's Legacy                    143
48             Starter 1999                    173
60        Mercadian Masques                    350
61            Sixth Edition                    350
110                 Nemesis                    143
115                Prophecy                    143
116                Invasion                    350
119         Seventh Edition                    350
122              Planeshift                    143
126                 Odyssey                    350
143                 Torment                    143
144               Judgement                    143
176                 Legions                    145
178                 Scourge                    143
179                Mirrodin                    306
193               Darksteel                    165
197              Fifth Dawn                    165
204   Champions of Kamigawa                    306
208   Betrayers of Kamigawa                    165
210           Ninth Edition                    350
215                 Ravnica                    306
255               Guildpact                    165
293          Eighth Edition                    350
310              Dissension                    180
328                Coldsnap                    155
341             Time Spiral                    121
342             Time Spiral                    301
515            Planar Chaos                    165
604             Futuresight                    180
678                  Lorwyn                    301
876             Morningtide                    150
971              Shadowmoor                    301
1162               Eventide                    180
1270        Shards of Alara                    249
1369                Conflux                    145
1424           Alara Reborn                    145
1447                    M10                    249
1529          Tenth Edition                    383
1662               Zendikar                    249
1748              Worldwake                    145
1799        Rise of Eldrazi                    248
1805                    M11                    249

In [110]:
expansion_symbol_df = df[['expansion_symbol', 'expansion_total_cards']].drop_duplicates()

In [111]:
expansion_symbol_df['expansion_symbol_id'] = range(1, len(expansion_symbol_df) + 1)

In [113]:
expansion_symbol_df = expansion_symbol_df[['expansion_symbol_id', 'expansion_symbol', 'expansion_total_cards']]

In [114]:
expansion_symbol_df

      expansion_symbol_id       expansion_symbol  expansion_total_cards
0                       1                Ice Age                    383
5                       2              Alliances                    144
6                       3                Visions                    167
11                      4                 Portal                    222
13                      5             Stronghold                    143
14                      6                 Exodus                    143
15                      7               Portal 2                    165
41                      8            Urza's Saga                    350
47                      9          Urza's Legacy                    143
48                     10           Starter 1999                    173
60                     11      Mercadian Masques                    350
61                     12          Sixth Edition                    350
110                    13                Nemesis                    143
115                    14               Prophecy                    143
116                    15               Invasion                    350
119                    16        Seventh Edition                    350
122                    17             Planeshift                    143
126                    18                Odyssey                    350
143                    19                Torment                    143
144                    20              Judgement                    143
176                    21                Legions                    145
178                    22                Scourge                    143
179                    23               Mirrodin                    306
193                    24              Darksteel                    165
197                    25             Fifth Dawn                    165
204                    26  Champions of Kamigawa                    306
208                    27  Betrayers of Kamigawa                    165
210                    28          Ninth Edition                    350
215                    29                Ravnica                    306
255                    30              Guildpact                    165
293                    31         Eighth Edition                    350
310                    32             Dissension                    180
328                    33               Coldsnap                    155
341                    34            Time Spiral                    121
342                    35            Time Spiral                    301
515                    36           Planar Chaos                    165
604                    37            Futuresight                    180
678                    38                 Lorwyn                    301
876                    39            Morningtide                    150
971                    40             Shadowmoor                    301
1162                   41               Eventide                    180
1270                   42        Shards of Alara                    249
1369                   43                Conflux                    145
1424                   44           Alara Reborn                    145
1447                   45                    M10                    249
1529                   46          Tenth Edition                    383
1662                   47               Zendikar                    249
1748                   48              Worldwake                    145
1799                   49        Rise of Eldrazi                    248
1805                   50                    M11                    249