In [1]:
import pandas as pd
import glob
# 1. Get a list of all CSV file paths in the directory
all_files = glob.glob("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17/*.csv")
# 2. Use list comprehension to read all files and concat them
ice_age_strixhaven = pd.concat([pd.read_csv(f) for f in all_files], ignore_index=True)

In [2]:
ice_age_strixhaven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3763 entries, 0 to 3762
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           3762 non-null   float64
 1   card_name              3761 non-null   object
 2   supertype              35 non-null     object
 3   subtype_a              332 non-null    object
 4   subtype_b              3619 non-null   object
 5   subtype_c              2326 non-null   object
 6   subtype_d              1093 non-null   object
 7   subtype_e              58 non-null     object
 8   expansion_symbol       3756 non-null   object
 9   rarity                 3751 non-null   object
 10  artist_information_a   3756 non-null   object
 11  artist_information_b   91 non-null     object
 12  collectors_number      3755 non-null   object
 13  expansion_total_cards  3715 non-null   float64
 14  mana_cost              3625 non-null   object
 15  text_box               3647 non-null   object
 16  flavor_text            2803 non-null   object
 17  punch                  2006 non-null   object
 18  toughness              2003 non-null   object
 19  starting_loyalty       9 non-null      object
 20  quantity               3748 non-null   object
dtypes: float64(2), object(19)
memory usage: 617.5+ KB

In [3]:
harry_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet1.csv")

In [4]:
harry_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              211 non-null    int64
 1   card_name                 211 non-null    object
 2   supertype                 28 non-null     object
 3   subtype_a                 211 non-null    object
 4   subtype_b                 119 non-null    object
 5   subtype_c                 65 non-null     object
 6   subtype_d                 2 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          211 non-null    object
 10  rarity                    211 non-null    object
 11  artist_information_a      210 non-null    object
 12  artist_information_b      8 non-null      object
 13  collectors_number         210 non-null    object
 14  expansion_total           202 non-null    float64
 15  mana_cost                 209 non-null    object
 16  text_box                  207 non-null    object
 17  flavor_text               125 non-null    object
 18  punch                     103 non-null    object
 19  toughness                 103 non-null    object
 20  quantity                  210 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           1 non-null      object
 29  split_mana_cost           1 non-null      object
 30  split_subtype_a           1 non-null      object
 31  split_text_box            1 non-null      object
 32  loyalty_cost_a            3 non-null      float64
 33  loyalty_ability_a         3 non-null      object
 34  loyalty_cost_b            4 non-null      object
 35  loyalty_ability_b         4 non-null      object
 36  loyalty_cost_c            4 non-null      float64
 37  loyalty_ability_c         4 non-null      object
 38  starting_loyalty          4 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       1 non-null      object
 48  transform_supertype       0 non-null      float64
 49  transform_subtype_a       1 non-null      object
 50  transform_subtype_b       1 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        1 non-null      object
 53  transform_flavor_text     0 non-null      float64
 54  transform_punch           1 non-null      float64
 55  transform_toughness       1 non-null      float64
 56  modal_card_name           4 non-null      object
 57  modal_mana_cost           4 non-null      object
 58  modal_supertype           2 non-null      object
 59  modal_subtype_c           4 non-null      object
 60  modal_subtype_b           2 non-null      object
 61  modal_subtype_a           2 non-null      object
 62  modal_text_box            4 non-null      object
 63  modal_punch               2 non-null      float64
 64  modal_toughness           2 non-null      float64
 65  saga_card_name            1 non-null      object
 66  lore_counter_a            1 non-null      object
 67  lore_text_box_a           1 non-null      object
 68  lore_counter_b            1 non-null      object
 69  lore_counter_text_box     1 non-null      object
 70  saga_supertype            1 non-null      object
 71  saga_subtype_a            1 non-null      object
 72  saga_subtype_b            1 non-null      object
 73  saga_subtype_c            1 non-null      object
 74  saga_subtype_d            1 non-null      object
 75  saga_punch                1 non-null      float64
 76  saga_toughness            1 non-null      float64
dtypes: float64(31), int64(1), object(45)
memory usage: 127.1+ KB

In [5]:
harry_binder = harry_binder.drop(columns='subtype_d.1')

In [6]:
harry_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [7]:
spencer_binder = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet2.csv")

In [8]:
spencer_binder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   permanent_id              176 non-null    int64
 1   card_name                 176 non-null    object
 2   supertype                 16 non-null     object
 3   subtype_a                 176 non-null    object
 4   subtype_b                 111 non-null    object
 5   subtype_c                 56 non-null     object
 6   subtype_d                 3 non-null      object
 7   subtype_d.1               0 non-null      float64
 8   subtype_e                 0 non-null      float64
 9   expansion_symbol          176 non-null    object
 10  rarity                    176 non-null    object
 11  artist_information_a      169 non-null    object
 12  artist_information_b      5 non-null      object
 13  collectors_number         176 non-null    object
 14  expansion_total           176 non-null    int64
 15  mana_cost                 170 non-null    object
 16  text_box                  168 non-null    object
 17  flavor_text               96 non-null     object
 18  punch                     93 non-null     object
 19  toughness                 93 non-null     object
 20  quantity                  171 non-null    float64
 21  flip_card_name            0 non-null      float64
 22  flip_subtype_a            0 non-null      float64
 23  flip_subtype_b            0 non-null      float64
 24  flip_subtype_c            0 non-null      float64
 25  flip_subtype_d            0 non-null      float64
 26  flip_punch                0 non-null      float64
 27  flip_toughness            0 non-null      float64
 28  split_card_name           0 non-null      float64
 29  split_mana_cost           0 non-null      float64
 30  split_subtype_a           0 non-null      float64
 31  split_text_box            0 non-null      float64
 32  loyalty_cost_a            8 non-null      float64
 33  loyalty_ability_a         8 non-null      object
 34  loyalty_cost_b            8 non-null      object
 35  loyalty_ability_b         8 non-null      object
 36  loyalty_cost_c            8 non-null      float64
 37  loyalty_ability_c         8 non-null      object
 38  starting_loyalty          8 non-null      float64
 39  leveler_tier_a            0 non-null      float64
 40  leveler_text_box_a        0 non-null      float64
 41  leveler_tier_a_punch      0 non-null      float64
 42  leveler_tier_a_toughness  0 non-null      float64
 43  leveler_tier_b            0 non-null      float64
 44  leveler_text_box_b        0 non-null      float64
 45  leveler_tier_b_punch      0 non-null      float64
 46  leveler_tier_b_toughness  0 non-null      float64
 47  transform_card_name       4 non-null      object
 48  transform_supertype       3 non-null      object
 49  transform_subtype_a       4 non-null      object
 50  transform_subtype_b       3 non-null      object
 51  transform_subtype_c       0 non-null      float64
 52  transform_text_box        4 non-null      object
 53  transform_flavor_text     2 non-null      object
 54  transform_punch           4 non-null      float64
 55  transform_toughness       4 non-null      float64
 56  modal_card_name           0 non-null      float64
 57  modal_mana_cost           0 non-null      float64
 58  modal_supertype           0 non-null      float64
 59  modal_subtype_c           0 non-null      float64
 60  modal_subtype_b           0 non-null      float64
 61  modal_subtype_a           0 non-null      float64
 62  modal_text_box            0 non-null      float64
 63  modal_punch               0 non-null      float64
 64  modal_toughness           0 non-null      float64
 65  saga_card_name            0 non-null      float64
 66  lore_counter_a            0 non-null      float64
 67  lore_text_box_a           0 non-null      float64
 68  lore_counter_b            0 non-null      float64
 69  lore_counter_text_box     0 non-null      float64
 70  saga_supertype            0 non-null      float64
 71  saga_subtype_a            0 non-null      float64
 72  saga_subtype_b            0 non-null      float64
 73  saga_subtype_c            0 non-null      float64
 74  saga_subtype_d            0 non-null      float64
 75  saga_punch                0 non-null      float64
 76  saga_toughness            0 non-null      float64
dtypes: float64(49), int64(2), object(26)
memory usage: 106.0+ KB

In [9]:
spencer_binder.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_d.1', 'subtype_e',
       'expansion_symbol', 'rarity', 'artist_information_a',
       'artist_information_b', 'collectors_number', 'expansion_total',
       'mana_cost', 'text_box', 'flavor_text', 'punch', 'toughness',
       'quantity', 'flip_card_name', 'flip_subtype_a', 'flip_subtype_b',
       'flip_subtype_c', 'flip_subtype_d', 'flip_punch', 'flip_toughness',
       'split_card_name', 'split_mana_cost', 'split_subtype_a',
       'split_text_box', 'loyalty_cost_a', 'loyalty_ability_a',
       'loyalty_cost_b', 'loyalty_ability_b', 'loyalty_cost_c',
       'loyalty_ability_c', 'starting_loyalty', 'leveler_tier_a',
       'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness'],
      dtype='object')

In [10]:
spencer_binder = spencer_binder.drop(columns='subtype_d.1')

In [11]:
spencer_binder.rename(columns={'expansion_total': 'expansion_total_cards'}, inplace=True)

In [12]:
rise_of_eldrazi = pd.read_csv("C:/Users/Spencer/Desktop/02_TCDB_Trading_Card_Database/Trading_Card_Collection_Download_2026_07_17_v02/Untitled spreadsheet - Sheet3.csv")

In [13]:
rise_of_eldrazi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   permanent_id           130 non-null    int64
 1   card_name              130 non-null    object
 2   supertype              1 non-null      object
 3   subtype_a              4 non-null      object
 4   subtype_b              129 non-null    object
 5   subtype_c              91 non-null     object
 6   subtype_d              46 non-null     object
 7   subtype_e              0 non-null      float64
 8   expansion_symbol       130 non-null    object
 9   rarity                 130 non-null    object
 10  artist_information_a   130 non-null    object
 11  artist_information_b   6 non-null      object
 12  collectors_number      130 non-null    int64
 13  expansion_total_cards  130 non-null    int64
 14  mana_cost              129 non-null    object
 15  text_box               127 non-null    object
 16  flavor_text            99 non-null     object
 17  punch                  74 non-null     float64
 18  toughness              74 non-null     float64
 19  starting_loyalty       0 non-null      float64
 20  quantity               130 non-null    int64
dtypes: float64(4), int64(4), object(13)
memory usage: 21.5+ KB

In [14]:
rise_of_eldrazi.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity'],
      dtype='object')

In [15]:
import numpy as np
# Add columns to the eldrazi sheet, fill with nan
rise_of_eldrazi[['flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']] = np.nan

In [16]:
# Reorder the columns so starting loyalty is positioned with the planeswalker attributes
rise_of_eldrazi = rise_of_eldrazi[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [17]:
rise_of_eldrazi

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,4109,Affa Guard Hound,NaN,NaN,Creature,Hound,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4110,Luminous Wake,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4111,Mammoth Umbra,NaN,NaN,Enchantment,Aura,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4112,Soulbound Guardians,NaN,NaN,Creature,Kor,Spirit,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4113,Survival Cache,NaN,NaN,Sorcery,NaN,NaN,NaN,Rise of Eldrazi,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,4234,Evolving Wilds,NaN,NaN,Land,NaN,NaN,NaN,Rise of Eldrazi,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,4235,Reya Dawnbringer,Legendary,NaN,Creature,Angel,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,4236,Beacon of Destruction,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,4237,Suntail Hawk,NaN,NaN,Creature,Bird,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,4238,Incinerate,NaN,NaN,Instant,NaN,NaN,NaN,Tenth Edition,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
ice_age_strixhaven.columns

Index(['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'starting_loyalty', 'quantity'],
      dtype='object')

In [21]:
ice_age_strixhaven[['flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']] = np.nan

In [22]:
ice_age_strixhaven = ice_age_strixhaven[['permanent_id', 'card_name', 'supertype', 'subtype_a', 'subtype_b',
       'subtype_c', 'subtype_d', 'subtype_e', 'expansion_symbol', 'rarity',
       'artist_information_a', 'artist_information_b', 'collectors_number',
       'expansion_total_cards', 'mana_cost', 'text_box', 'flavor_text',
       'punch', 'toughness', 'quantity', 'flip_card_name', 'flip_subtype_a',
       'flip_subtype_b', 'flip_subtype_c', 'flip_subtype_d', 'flip_punch',
       'flip_toughness', 'split_card_name', 'split_mana_cost',
       'split_subtype_a', 'split_text_box', 'loyalty_cost_a',
       'loyalty_ability_a', 'loyalty_cost_b', 'loyalty_ability_b',
       'loyalty_cost_c', 'loyalty_ability_c', 'starting_loyalty',
       'leveler_tier_a', 'leveler_text_box_a', 'leveler_tier_a_punch',
       'leveler_tier_a_toughness', 'leveler_tier_b', 'leveler_text_box_b',
       'leveler_tier_b_punch', 'leveler_tier_b_toughness',
       'transform_card_name', 'transform_supertype', 'transform_subtype_a',
       'transform_subtype_b', 'transform_subtype_c', 'transform_text_box',
       'transform_flavor_text', 'transform_punch', 'transform_toughness',
       'modal_card_name', 'modal_mana_cost', 'modal_supertype',
       'modal_subtype_c', 'modal_subtype_b', 'modal_subtype_a',
       'modal_text_box', 'modal_punch', 'modal_toughness', 'saga_card_name',
       'lore_counter_a', 'lore_text_box_a', 'lore_counter_b',
       'lore_counter_text_box', 'saga_supertype', 'saga_subtype_a',
       'saga_subtype_b', 'saga_subtype_c', 'saga_subtype_d', 'saga_punch',
       'saga_toughness']]

In [23]:
ice_age_strixhaven

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
0,1.0,Essence Flare,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Iceberg,NaN,NaN,Enchantment,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Mistfolk,NaN,NaN,Creature,Illusion,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Snow Devil,NaN,NaN,Enchantment,Aura,NaN,NaN,Ice Age,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Arcum's Weathervane,NaN,Artifact,NaN,NaN,NaN,NaN,Ice Age,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3758,2294.0,Stampeding Rhino,NaN,NaN,Creature,Rhino,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3759,2295.0,Titanic Growth,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3760,2296.0,Trollhide,NaN,NaN,Enchantment,Aura,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3761,2297.0,Vastwood Gorger,NaN,NaN,Creature,Wurm,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3762,2298.0,Angel's Mercy,NaN,NaN,Instant,NaN,NaN,NaN,M12,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
collection = pd.concat([ice_age_strixhaven, spencer_binder, harry_binder, rise_of_eldrazi], ignore_index=True)

In [25]:
collection[collection.loc[:, 'card_name':'quantity'].isna().all(axis=1)]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
2009,3593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2375,912.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
collection = collection.drop([2009, 2375])

In [27]:
collection[collection['artist_information_a'].isna()]

,permanent_id,card_name,supertype,subtype_a,subtype_b,subtype_c,subtype_d,subtype_e,expansion_symbol,rarity,...,lore_text_box_a,lore_counter_b,lore_counter_text_box,saga_supertype,saga_subtype_a,saga_subtype_b,saga_subtype_c,saga_subtype_d,saga_punch,saga_toughness
378,379.0,Suq'Ata Lancer,NaN,NaN,Creature,Human,Knight,NaN,Time Spiral,Timeshifted Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,380.0,Tectonic Fiend,NaN,NaN,Creature,Elemental,NaN,NaN,Time Spiral,Uncommon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1757,3378.0,Acidic Slime,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2109,3690.0,Cemetery Reaper,NaN,NaN,Creature,Zombie,NaN,NaN,M12,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3149,1685.0,Territorial Baloth,NaN,NaN,Creature,Beast,NaN,NaN,Zendikar,Common,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3879,4049.0,Curse of Stalked Prey,NaN,Enchantment,Aura,Curse,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3880,4050.0,Kruin Outlaw,NaN,Creature,Human,Rogue,Werewolf,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3881,4051.0,Stormkirk Noble,NaN,Creature,Vampire,NaN,NaN,NaN,Innistrad,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3882,4052.0,Hellrider,NaN,Creature,Devil,NaN,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3883,4053.0,Markov Blademaster,NaN,Creature,Vampire,Warrior,NaN,NaN,Dark Ascension,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3884,4054.0,"Gisela, Blade of Goldnight",Legendary,Creature,Angel,NaN,NaN,NaN,Avacyn Restored,Mythic,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3885,4055.0,Hound of Griselbrand,NaN,Creature,Elemental,Hound,NaN,NaN,Avacyn Restored,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3948,3731.0,Titan's Revenge,NaN,Sorcery,NaN,NaN,NaN,NaN,Morningtide,Rare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
collection.at[378, 'artist_information_a'] = 'Jeff Miracola'
collection.at[379, 'artist_information_a'] = 'Mark Tedin'
collection.at[2109, 'artist_information_a'] = 'Dave Allsop'
collection.at[3149, 'artist_information_a'] = 'Jesper Ejsing'
collection.at[3879, 'artist_information_a'] = 'Christopher Moeller'
collection.at[3880, 'artist_information_a'] = 'David Rapoza'
collection.at[3881, 'artist_information_a'] = 'James Ryman'
collection.at[3882, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3883, 'artist_information_a'] = 'Jana Schirmer'
collection.at[3883, 'artist_information_b'] = 'Johannes Voss'
collection.at[3884, 'artist_information_a'] = 'Jason Chan'
collection.at[3885, 'artist_information_a'] = 'Svetlin Velinov'
collection.at[3948, 'artist_information_a'] = 'Christopher Moeller'

In [58]:
collection[collection['expansion_symbol'].isna()]

Empty DataFrame
Columns: [permanent_id, card_name, supertype, subtype_a, subtype_b, subtype_c, subtype_d, subtype_e, expansion_symbol, rarity, artist_information_a, artist_information_b, collectors_number, expansion_total_cards, mana_cost, text_box, flavor_text, punch, toughness, quantity, flip_card_name, flip_subtype_a, flip_subtype_b, flip_subtype_c, flip_subtype_d, flip_punch, flip_toughness, split_card_name, split_mana_cost, split_subtype_a, split_text_box, loyalty_cost_a, loyalty_ability_a, loyalty_cost_b, loyalty_ability_b, loyalty_cost_c, loyalty_ability_c, starting_loyalty, leveler_tier_a, leveler_text_box_a, leveler_tier_a_punch, leveler_tier_a_toughness, leveler_tier_b, leveler_text_box_b, leveler_tier_b_punch, leveler_tier_b_toughness, transform_card_name, transform_supertype, transform_subtype_a, transform_subtype_b, transform_subtype_c, transform_text_box, transform_flavor_text, transform_punch, transform_toughness, modal_card_name, modal_mana_cost, modal_supertype, modal_subtype_c, modal_subtype_b, modal_subtype_a, modal_text_box, modal_punch, modal_toughness, saga_card_name, lore_counter_a, lore_text_box_a, lore_counter_b, lore_counter_text_box, saga_supertype, saga_subtype_a, saga_subtype_b, saga_subtype_c, saga_subtype_d, saga_punch, saga_toughness, artist_information]
Index: []

In [30]:
collection.loc[1598, ['subtype_b', 'subtype_c', 'subtype_d', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', np.nan, np.nan, 'Fourth Edition', 'Uncommon', 118, 378, '{1}{B}', 'Take target creature from any graveyard and put it directly into play under your control with -1/-0. Treat this creature as though it were just summoned. If Animate Dead is removed, bury the creature in its owner\'s graveyard.', 1]
collection.loc[1599, ['subtype_b', 'subtype_c', 'subtype_d', 'expansion_symbol', 'rarity','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Enchantment', np.nan, np.nan, 'Revised Edition', 'Uncommon', 93, 306, '{1}{B}', 'Enchant creature card in a graveyard\nWhen this Aura enters, if it\'s on the battlefield, it loses "enchant creature card in a graveyard" and gains "enchant creature put onto the battlefield with this Aura." Return enchanted creature card to the battlefield under your control and attach this Aura to it. When this Aura leaves the battlefield, that creature\'s controller sacrifices it.', 1]
collection.loc[1600, ['subtype_b', 'expansion_symbol', 'rarity', 'artist_information_a','collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'quantity']] = ['Artifact', 'Revised Edition', 'Rare', 'Mark Tedin', 280, 306, '{2}', 'A player may not untap more than one land during the untap phase of each of his or her turns.', 1]
collection.loc[1757, ['subtype_b', 'subtype_c', 'expansion_symbol', 'rarity', 'artist_information_a', 'collectors_number', 'expansion_total_cards', 'mana_cost', 'text_box', 'punch', 'toughness', 'quantity']] = ['Creature', 'Ooze', 'M12', 'Uncommon', 'Karl Kopinski', 161, 249, '{3}{G}{G}', 'Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.) When Acidic Slime enters the battlefield, destroy target artifact, enchantment, or land.', 2, 2, 1]
collection.loc[1993, ['card_name', 'subtype_b', 'expansion_symbol', 'rarity', 'artist_information', 'collectors_number', 'expansion_total_cards', 'text_box', 'quantity']] = ['Brushland', 'Land', 'Fifth Edition', 'Rare', 'Tom Wänerstrand', 414, 449, '{T}: Add one colorless mana to your mana pool.\n{T}: Add {G} or {W} to your mana pool.\nBrushland deals 1 damage to you.', 1]

In [35]:
collection[collection['expansion_total_cards'].isna()]

Empty DataFrame
Columns: [permanent_id, card_name, supertype, subtype_a, subtype_b, subtype_c, subtype_d, subtype_e, expansion_symbol, rarity, artist_information_a, artist_information_b, collectors_number, expansion_total_cards, mana_cost, text_box, flavor_text, punch, toughness, quantity, flip_card_name, flip_subtype_a, flip_subtype_b, flip_subtype_c, flip_subtype_d, flip_punch, flip_toughness, split_card_name, split_mana_cost, split_subtype_a, split_text_box, loyalty_cost_a, loyalty_ability_a, loyalty_cost_b, loyalty_ability_b, loyalty_cost_c, loyalty_ability_c, starting_loyalty, leveler_tier_a, leveler_text_box_a, leveler_tier_a_punch, leveler_tier_a_toughness, leveler_tier_b, leveler_text_box_b, leveler_tier_b_punch, leveler_tier_b_toughness, transform_card_name, transform_supertype, transform_subtype_a, transform_subtype_b, transform_subtype_c, transform_text_box, transform_flavor_text, transform_punch, transform_toughness, modal_card_name, modal_mana_cost, modal_supertype, modal_subtype_c, modal_subtype_b, modal_subtype_a, modal_text_box, modal_punch, modal_toughness, saga_card_name, lore_counter_a, lore_text_box_a, lore_counter_b, lore_counter_text_box, saga_supertype, saga_subtype_a, saga_subtype_b, saga_subtype_c, saga_subtype_d, saga_punch, saga_toughness, artist_information]
Index: []

In [32]:
collection.loc[collection['expansion_symbol'] == 'Visions', 'expansion_total_cards'] = 167
collection.loc[collection['expansion_symbol'] == 'Portal', 'expansion_total_cards'] = 222
collection.loc[collection['expansion_symbol'] == 'Stronghold', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Exodus', 'expansion_total_cards'] = 143
collection.loc[collection['expansion_symbol'] == 'Portal 2', 'expansion_total_cards'] = 165
collection.loc[collection['expansion_symbol'] == 'Universes Beyond: Final Fantasy', 'expansion_total_cards'] = 309
collection.loc[collection['expansion_symbol'] == 'Starter 2000', 'expansion_total_cards'] = 20
collection.loc[collection['expansion_symbol'] == 'Strixhaven', 'expansion_total_cards'] = 393
collection.loc[collection['expansion_symbol'] == 'Morningtide', 'expansion_total_cards'] = 150

In [39]:
# Some of the cards are double-faced and the collectors number is followed with an a or b depending on the face
collection[collection['collectors_number'].str.contains('[a-zA-Z]', na=False)]

Empty DataFrame
Columns: [permanent_id, card_name, supertype, subtype_a, subtype_b, subtype_c, subtype_d, subtype_e, expansion_symbol, rarity, artist_information_a, artist_information_b, collectors_number, expansion_total_cards, mana_cost, text_box, flavor_text, punch, toughness, quantity, flip_card_name, flip_subtype_a, flip_subtype_b, flip_subtype_c, flip_subtype_d, flip_punch, flip_toughness, split_card_name, split_mana_cost, split_subtype_a, split_text_box, loyalty_cost_a, loyalty_ability_a, loyalty_cost_b, loyalty_ability_b, loyalty_cost_c, loyalty_ability_c, starting_loyalty, leveler_tier_a, leveler_text_box_a, leveler_tier_a_punch, leveler_tier_a_toughness, leveler_tier_b, leveler_text_box_b, leveler_tier_b_punch, leveler_tier_b_toughness, transform_card_name, transform_supertype, transform_subtype_a, transform_subtype_b, transform_subtype_c, transform_text_box, transform_flavor_text, transform_punch, transform_toughness, modal_card_name, modal_mana_cost, modal_supertype, modal_subtype_c, modal_subtype_b, modal_subtype_a, modal_text_box, modal_punch, modal_toughness, saga_card_name, lore_counter_a, lore_text_box_a, lore_counter_b, lore_counter_text_box, saga_supertype, saga_subtype_a, saga_subtype_b, saga_subtype_c, saga_subtype_d, saga_punch, saga_toughness, artist_information]
Index: []

In [38]:
collection.loc[5, ['collectors_number']] = 57
collection.loc[678, ['collectors_number']] = 8
collection.loc[686, ['collectors_number']] = 47
collection.loc[700, ['collectors_number']] = 114
collection.loc[705, ['collectors_number']] = 145
collection.loc[712, ['collectors_number']] = 182
collection.loc[717, ['collectors_number']] = 208
collection.loc[742, ['collectors_number']] = 38
collection.loc[797, ['collectors_number']] = 165
collection.loc[800, ['collectors_number']] = 168
collection.loc[808, ['collectors_number']] = 185
collection.loc[818, ['collectors_number']] = 209
collection.loc[826, ['collectors_number']] = 146
collection.loc[837, ['collectors_number']] = 13
collection.loc[936, ['collectors_number']] = 81
collection.loc[942, ['collectors_number']] = 122
collection.loc[963, ['collectors_number']] = 55
collection.loc[975, ['collectors_number']] = 94
collection.loc[984, ['collectors_number']] = 125
collection.loc[1752, ['collectors_number']] = 51
collection.loc[3822, ['collectors_number']] = 64
collection.loc[3960, ['collectors_number']] = 152

In [56]:
collection[collection['collectors_number'].isna()]

Empty DataFrame
Columns: [permanent_id, card_name, supertype, subtype_a, subtype_b, subtype_c, subtype_d, subtype_e, expansion_symbol, rarity, artist_information_a, artist_information_b, collectors_number, expansion_total_cards, mana_cost, text_box, flavor_text, punch, toughness, quantity, flip_card_name, flip_subtype_a, flip_subtype_b, flip_subtype_c, flip_subtype_d, flip_punch, flip_toughness, split_card_name, split_mana_cost, split_subtype_a, split_text_box, loyalty_cost_a, loyalty_ability_a, loyalty_cost_b, loyalty_ability_b, loyalty_cost_c, loyalty_ability_c, starting_loyalty, leveler_tier_a, leveler_text_box_a, leveler_tier_a_punch, leveler_tier_a_toughness, leveler_tier_b, leveler_text_box_b, leveler_tier_b_punch, leveler_tier_b_toughness, transform_card_name, transform_supertype, transform_subtype_a, transform_subtype_b, transform_subtype_c, transform_text_box, transform_flavor_text, transform_punch, transform_toughness, modal_card_name, modal_mana_cost, modal_supertype, modal_subtype_c, modal_subtype_b, modal_subtype_a, modal_text_box, modal_punch, modal_toughness, saga_card_name, lore_counter_a, lore_text_box_a, lore_counter_b, lore_counter_text_box, saga_supertype, saga_subtype_a, saga_subtype_b, saga_subtype_c, saga_subtype_d, saga_punch, saga_toughness, artist_information]
Index: []

In [51]:
collection.loc[2028, ['collectors_number']] = 3
collection.loc[3948, ['collectors_number']] = 110

In [ ]:
collection['collectors_number'] = collection['collectors_number'].astype('Int64')

In [53]:
collection['expansion_total_cards'] = collection['expansion_total_cards'].astype(int)

In [ ]:
collection[collection['expansion_symbol'] == 'Lorwyn'].sort_values(by='collectors_number')

In [ ]:
collection

In [43]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')